### ISSUE TITLE
Google Home is reporting multiple lights instead of one

### ISSUE THREAD

**Issue by tomas-bara** [mikejac/node-red-contrib-google-smarthome#1]
Hello,

I recently started using your library and I want to thank you! :-) Nice work.

**Bug:**

When I'm using On/Off node and work in node-red as usual Google starts after some time (multiple Deploys) reporting "Ok turning Off 2 lights" Instead of "Ok turning Off Office Light".

- In this "Google Room" I have only one light
- This problem starts after some time
- Unlinking App and linking again will help for some time

But I'm not sure how to help, Is there way to give you some report, etc.?

I'm using latest version from official NPM.

Thank you

**Comment by whoamicz** [comment]
And sometimes Google will report "Sorry I can not reach XYZ" and do nothing or will say this error bu do it correctly.

**Comment by mikejac** [comment]
Hi @whoamicz, I lost track of what is and what is not in the published versions. However, I've just published a new version (0.0.11). Would you mind updating your installation?

Also, in this version you can enable debug output in the configuration node. The log is written the same place as logs from Node-RED.

However, from what you write it seems to me that it's Google that for some reason gets things messed up...

/michael

**Comment by whoamicz** [comment]
Hi,

the thing with duplicate devices is problem in google, it woks OK when usign Home App and switching lights but it is broken when using voice commands.

I did debugging in API and result from voice looks like this:
`[
	{
		"devices": [
			{
				"customData": {},
				"id": "0123456789"
			},
			{
				"customData": {},
				"id": "0123456789"
			}
		],
		"execution": [
			{
				"command": "action.devices.commands.OnOff",
				"params": {
					"on": true
				}
			}
		]
	}
]`

and from app like this:

`[
	{
		"devices": [
			{
				"customData": {},
				"id": "0123456789"
			}
		],
		"execution": [
			{
				"command": "action.devices.commands.OnOff",
				"params": {
					"on": true
				}
			}
		]
	}
]`

So I think you can close this issue. 

But about "Sorry I can not reach App Name right now" after success command  I'm not able to debug where is problem.
