### ISSUE TITLE
Feature request - tv channel support

### ISSUE THREAD

**Issue by STDevMan** [mikejac/node-red-contrib-google-smarthome#101]
not sure if this is possible or already achievable...

I don't believe there is a tv device?

I would like to ask google to set my tv to channel 1234 by asking. And have it work with any number. I use to do this with Broadlink/google but I have since moved broadlink to nodered local control and lost this feature

I would then convert the 1234 input into seperate node red remote button pushes

thanks

**Comment by ckhmer1** [comment]
Hi,
this is still available, the media devices node support the TV devices.

**Comment by STDevMan** [comment]
sweet. Great work!
