### ISSUE TITLE
Passing commands and variables to media device

### ISSUE THREAD

**Issue by rockstar2020** [mikejac/node-red-contrib-google-smarthome#104]
Hi @mikejac,
It's so great to see you're adding new devices specially I'm excited to see the media device, but I have a problem which I'm hoping you could give me a hint to fix it. 
The issue is that I can turn on/off or change volume of a media device using a voice command on Google home but no other commands gets passed to the device in node-red.
For example when I say "stop my receiver" google responds "sure" but no json message is passed to the media device node. 
Additionally I was wondering if there's a way to pass a string variable to the media device by using a voice command like "play matrix on my receiver".

Many thanks for constantly enhancing this awesome project. 
Cheers

**Comment by ChutneyMary** [comment]
I'd also welcome further instructions on how to employ the media device.
As an example, I wish to have 3 input options - HDMI1, HDMI2 and HDMI3. I can see there's an input.json saved to the Node-Red folder, but I'm not sure how to influence the available inputs on the media device. If I understand correctly, the available inputs need to be defined in the inputs.json to enable voice control of each. Any guidance welcome.

**Comment by ckhmer1** [comment]
Hi,
try starting from the following flow:

[{"id":"985701ca.58de9","type":"google-media","z":"6575ac93.01c874","client":"","name":"Example Television","topic":"tv","device_type":"TV","has_apps":false,"has_channels":true,"has_inputs":false,"has_media_state":false,"has_on_off":false,"has_transport_control":false,"has_modes":true,"has_toggles":true,"available_applications_file":"applications.json","available_channels_file":"channels.json","available_inputs_file":"inputs.json","command_only_input_selector":"","ordered_inputs":"","support_activity_state":false,"support_playback_state":false,"command_only_on_off":false,"query_only_on_off":false,"supported_commands":[],"volume_max_level":"50","can_mute_and_unmute":"","volume_default_percentage":40,"level_step_size":1,"command_only_volume":false,"available_modes_file":"modes.json","command_only_modes":false,"query_only_modes":false,"available_toggles_file":"toggles.json","command_only_toggles":false,"query_only_toggles":false,"passthru":false,"x":550,"y":200,"wires":[["48723761.d78bb8"]]},{"id":"48723761.d78bb8","type":"function","z":"6575ac93.01c874","name":"Split","func":"return [\n    { payload: msg.payload.online },\n];","outputs":1,"noerr":0,"x":730,"y":200,"wires":[["6f5daaf0.f5dce4"]],"outputLabels":["online"]},{"id":"6637f52f.da97cc","type":"change","z":"6575ac93.01c874","name":"topic = online","rules":[{"t":"set","p":"topic","pt":"msg","to":"online","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":200,"wires":[["985701ca.58de9"]]},{"id":"4d3983f6.6f373c","type":"function","z":"6575ac93.01c874","name":"","func":"let msg1={\"topic\": msg.topic};\nlet lang=msg.lang || 'en';\nlet toggles = [];\nmsg1.payload = toggles;\nmsg.payload.forEach(toggle => {\n    if (typeof toggle == \"string\") {\n        let new_toggle = {};\n        let key = toggle.replace(/ /g, '_');\n        if (!key.toLowerCase().endsWith(\"toggle\")) {\n            key = key + \"_toggle\";\n        }\n        new_toggle['name'] = key.toLowerCase();\n        new_toggle['name_values'] = [{\n            \"lang\": lang,\n            \"name_synonym\": [ toggle ]\n        }];\n        toggles.push(new_toggle);\n    } else if (typeof toggle == \"object\") {\n        let key = toggle['key'];\n        let names = toggle['names'];\n        if (key == undefined) {\n            key = names[0].replace(/ /g, '_');\n        }\n        if (!key.toLowerCase().endsWith(\"toggle\")) {\n            key = key + \"_toggle\";\n        }\n        let new_toggle = {};\n        new_toggle['name'] = key.toLowerCase();\n        new_toggle['name_values'] = [{\n            \"lang\": lang,\n            \"name_synonym\": names\n        }];\n        toggles.push(new_toggle);\n    }\n});\n\nreturn msg1;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":300,"y":240,"wires":[["985701ca.58de9"]]},{"id":"2cfd736e.156d5c","type":"function","z":"6575ac93.01c874","name":"","func":"const topic = msg.topic.toLowerCase().slice(0, -1);\nlet msg1={\"topic\": msg.topic};\nlet lang=msg.lang || 'en';\nlet objs = [];\nmsg1.payload = objs;\nmsg.payload.forEach(obj => {\n    if (typeof obj == \"string\") {\n        let new_obj = {};\n        let key = obj.replace(/ /g, '_').toLowerCase();\n        if (!key.endsWith(topic)) {\n            key = key + \"_\" + topic;\n        }\n        new_obj['key'] = key;\n        new_obj['names'] = [{\n            \"lang\": lang,\n            \"name_synonym\": [ obj ]\n        }];\n        objs.push(new_obj);\n    } else if (typeof obj == \"object\") {\n        let new_obj = {};\n        let key = obj['key'];\n        let names = obj['names'];\n        if (key == undefined) {\n            key = names[0];\n        }\n        key = key.replace(/ /g, '_').toLowerCase();\n        if (!key.endsWith(topic)) {\n            key = key + \"_\" + topic;\n        }\n        new_obj['key'] = key;\n        let new_objt = {};\n        new_obj['key'] = key;\n        new_obj['names'] = [{\n            \"lang\": lang,\n            \"name_synonym\": names\n        }];\n        objs.push(new_obj);\n    }\n});\n\nreturn msg1;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":300,"y":280,"wires":[["985701ca.58de9"]]},{"id":"387845e5.5e2f5a","type":"inject","z":"6575ac93.01c874","name":"Channels","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Channels","payload":"[{\"key\":\"rai1\",\"names\":[\"Rai 1\"],\"number\":\"1\"},{\"key\":\"rai1_hd\",\"names\":[\"Rai 1 HD\"],\"number\":\"501\"},{\"key\":\"rai2\",\"names\":[\"Rai 2\"],\"number\":\"2\"},{\"key\":\"rai2_hd\",\"names\":[\"Rai 2 HD\"],\"number\":\"502\"},{\"key\":\"rai3\",\"names\":[\"Rai 3\"],\"number\":\"3\"},{\"key\":\"rai3_hd\",\"names\":[\"Rai 3 HD\"],\"number\":\"503\"},{\"key\":\"realtime\",\"names\":[\"Realtime\"],\"number\":\"31\"}]","payloadType":"json","x":120,"y":360,"wires":[["985701ca.58de9"]]},{"id":"3b17441c.9a3f0c","type":"inject","z":"6575ac93.01c874","name":"Modes","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Modes","payload":"[{\"name\":\"load_mode\",\"name_values\":[{\"name_synonym\":[\"load\",\"size\",\"load size\"],\"lang\":\"en\"}],\"settings\":[{\"setting_name\":\"small_load\",\"setting_values\":[{\"setting_synonym\":[\"small\",\"half\"],\"lang\":\"en\"}]},{\"setting_name\":\"medium_load\",\"setting_values\":[{\"setting_synonym\":[\"medium\",\"normal\"],\"lang\":\"en\"}]},{\"setting_name\":\"large_load\",\"setting_values\":[{\"setting_synonym\":[\"large\",\"full\"],\"lang\":\"en\"}]}],\"ordered\":true},{\"name\":\"temp_mode\",\"name_values\":[{\"name_synonym\":[\"temperature\",\"temp\"],\"lang\":\"en\"}],\"settings\":[{\"setting_name\":\"hot_temp\",\"setting_values\":[{\"setting_synonym\":[\"hot\",\"white\"],\"lang\":\"en\"}]},{\"setting_name\":\"warm_temp\",\"setting_values\":[{\"setting_synonym\":[\"warm\",\"color\"],\"lang\":\"en\"}]},{\"setting_name\":\"cold_temp\",\"setting_values\":[{\"setting_synonym\":[\"cold\",\"delicate\"],\"lang\":\"en\"}]}],\"ordered\":false}]","payloadType":"json","x":110,"y":400,"wires":[["985701ca.58de9"]]},{"id":"6f5daaf0.f5dce4","type":"mqtt out","z":"6575ac93.01c874","name":"","topic":"home/tv/set-power","qos":"","retain":"","broker":"","x":920,"y":200,"wires":[]},{"id":"980e90e8.c7796","type":"mqtt in","z":"6575ac93.01c874","name":"","topic":"home/tv/power","qos":"2","datatype":"auto","broker":"","x":120,"y":200,"wires":[["6637f52f.da97cc"]]},{"id":"8a2472a.979da9","type":"inject","z":"6575ac93.01c874","name":"Toggles","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"toggles","payload":"[\"quiet\",{\"key\":\"extra_bass\",\"names\":[\"Extra bass\",\"Loud bass\",\"Powerful bass\"]},{\"names\":[\"Energy Saving\",\"Low Energy\"]}]","payloadType":"json","x":110,"y":240,"wires":[["4d3983f6.6f373c"]]},{"id":"ce4d650b.8098a8","type":"inject","z":"6575ac93.01c874","name":"Inputs","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Inputs","payload":"[\"hdmi 1\",{\"key\":\"hdmi_2\",\"names\":[\"hdmi 2\",\"Second HDMI\",\"DVD Reader\",\"DVD\"]},{\"names\":[\"hdmi 3\",\"Third HDMI\",\"Playstation 5\",\"PS5\"]}]","payloadType":"json","x":110,"y":280,"wires":[["2cfd736e.156d5c"]]},{"id":"7fa56940.bf6298","type":"inject","z":"6575ac93.01c874","name":"Apps","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Applications","payload":"[\"YouTube\",{\"key\":\"video\",\"names\":[\"Google Vide\",\"Video\"]},{\"names\":[\"Amazon Prime Video\",\"Prime Video\"]}]","payloadType":"json","x":110,"y":320,"wires":[["2cfd736e.156d5c"]]}]

**Comment by ChutneyMary** [comment]
Thanks, but I can't import that flow. Node-Red throws an error -

SyntaxError: Unexpected token t in JSON at position 1587
"let msg1={" t opic" : msg.

I've searched through your flow in a text editor but those spaces around t don't exist. Weird...?

**Comment by ckhmer1** [comment]
Hi,
I've added a new request for updating the flow.
Pull request #105, "Updated Media TV Flow", contains the same flow. Could you please try to copy from there?
Thanks

**Comment by ChutneyMary** [comment]
That flow imports fine. I won't have a chance to play around with it for a couple of days but that looks very helpful!

**Comment by rockstar2020** [comment]
Thanks @ckhmer1,
It is indeed very helpful to look your example flow. 
I did manage to import it but after deployment and triggering the inject nodes (Inputs, Apps, ...) I'm still not able to trigger a voice command to for example change the input ot channel.
What am I missing in the process?
Cheers

**Comment by rockstar2020** [comment]
@ckhmer1, if it helps this is the error that the device is spitting out when I run a voice command to change the channel to 1:

object
msg: "Error in HttpActions:reportState()"
org_msg: object
code: 400
message: "Request contains an invalid argument."
status: "INVALID_ARGUMENT"
data: object
states: object
online: true
currentApplication: ""
currentInput: ""
activityState: "INACTIVE"
playbackState: "STOPPED"
on: false
currentVolume: 40
isMuted: false
currentToggleSettings: object
currentModeSettings: object
currentChannel: "rai1"

**Comment by ckhmer1** [comment]
Could you please show me the reportState() from the log?

**Comment by rockstar2020** [comment]
Where can I find the reportState() log?

**Comment by ckhmer1** [comment]
If you use docker, you can try "docker logs -f node-red", where node-red is the container name, otherwise try to look in the .node-red folder or /var/log

**Comment by Caprico85** [comment]
reportState() errors are usually also listed in Node-RED's debug panel.

![image](https://user-images.githubusercontent.com/2081806/107189507-ca769e80-69e9-11eb-83b3-1d0b5304a2d0.png)

**Comment by rockstar2020** [comment]
What I copied above is basically what I can see in the debug panel.
Unfortunately I don't know what's causing this error. 
In spite of this error, voice commands are getting executed and passed to Node-Red flawlessly.

On a separate note I was wondering if there's a way to pass string ingredient via voice command to media device. Basically I'd like to replace what IFTTT integration does with my smart home setup. 

Many thanks in advance. 

Pasting the error from the debug window for your reference::

object
msg: "Error in HttpActions:reportState()"
org_msg: object
code: 400
message: "Request contains an invalid argument."
status: "INVALID_ARGUMENT"

**Comment by ckhmer1** [comment]
In what you have copied from the debug window, there are several objects closed, like the following:

currentToggleSettings: object
currentModeSettings: object

Could you please post the complete info from the error message?
Thanks

**Comment by rockstar2020** [comment]
Here is the full error message:

![image](https://user-images.githubusercontent.com/35903046/107445920-664bfb80-6b0b-11eb-9d37-14c2b3736473.png)

**Comment by ckhmer1** [comment]
Hi,
thanks for the info.
I'm sorry, but I didn't realize that the "currentChannel" is not a status for Google. Google doesn't want to know which is the current channel.
Removing it from the status prevents the flow to know which channel is currently set.

@Caprico85 is there a way to pass further information to the exit message?
In my opinion, all nodes should return all the info and an array with the properties that have been changed.
At least, a new flag, for have a message in output also if no property has been changed receiving a command from Google.
What do You think about it?

**Comment by ckhmer1** [comment]
Hi,
I've sent two merge requests fixing this problem.
Unfortunately, I only can test them in emulation mode.
If you want, You can apply them manually and let me know.
Thanks
Claudio

**Comment by rockstar2020** [comment]
Thanks @ckhmer1.
I will give it a try.
There's also one outstanding question (not a bug report) which I'm hoping you can answer.
Is there any way to pass text variable via voice command to Google home using any of the existing nodes?
I am currently using IFTTT but at times IFTTT server is not accessible which is frsutrating.

Many thanks

**Comment by ckhmer1** [comment]
Hi,
This project is using the Google Actions Smart Home feature.
As far as I know, it is not possible to pass any text variable.
If you want to have it, You should create a new Actions Project, in Dialogflow, with your own sentences, and with a different backend server.

Could You please let me know if the fixes are ok for You?
Thanks
Claudio

**Comment by rockstar2020** [comment]
Hi,
Yes I know the option to use Dialogflow but the problem is that you have to first talk to Dialogflow agent and then pass the commands which is not what I want. I think for now my best and only option is IFTTT.
Thanks for your help anyway.

As for the error, looks like the changes you made fixed the issue. I'm not receiving that error message anymore.
Much appreciate your help.
I'll be closing this issue.

Cheers

**Comment by rockstar2020** [comment]
Sorry, I just noticed that I'm not able to turn any device on or off after making the manual changes you recommended.
Yes, the error message is gone but the commend to turn the device ON doesn't work.
Below is a snapshot of debug window after I ran the command on Google Assistant to turn the device ON. As you see the state is OFF:


![image](https://user-images.githubusercontent.com/35903046/107882412-25f7cf00-6eb7-11eb-8d75-458cb57eee12.png)

**Comment by ckhmer1** [comment]
Hi,
I'm sorry for that.
I've updated my patch, now should work.

Best Regards
Claudio

**Comment by rockstar2020** [comment]
Hi @ckhmer1.
Your code works now. No errors and I can turn the devices on and off. Thank you!
But there's one thing little thing I observed which is not a big issue but I'm interested to know what you think could cause it.
When I type a command like "change TV channel to TVO" on my phone's Google Assistant, the command gets executed properly and I get the correct JSON message in my node red. But google assistant keeps the 3 dots constantly blinking. I think it is expecting a status update back from the device which is not getting. I may be wrong. It doesn't seem to be normal.

Executing via a voice command is flawless though.

Cheers

**Comment by ckhmer1** [comment]
Hi,
I've updated my patch, now it should be fixed.

Could You please let me know if it is ok for you?

Thanks
Claudio

**Comment by rockstar2020** [comment]
Hi Claudio,
I made the changes but still the 3 dots keep blinking.

Cheers

**Comment by ckhmer1** [comment]
Hi,
really I don't know why this is happening, and it is only happening on channel commands.
The response to Google seems correct.

I'm lack ideas.

Claudio

**Comment by rockstar2020** [comment]
Thanks for your efforts Claudio.
As mentioned beofre it is not a big deal but thought of sharing it with you hoping that troubleshooting it might lead to solving other bugs.
I'll close this issue now.
Much appreciate your help.

**Comment by ckhmer1** [comment]
Hi,
I've updated the pull request adding the channel number in the output payload, to use for sending IR commands.

Best Regards
