### ISSUE TITLE
Help for understand

### ISSUE THREAD

**Issue by coxifred** [mikejac/node-red-contrib-google-smarthome#106]
First of all : Congratulations for your module ! Google creates a huge gaz factory to manipulate connected objects, and you succeed to simplify.

Context :
    - node-red-contrib-google-smarthome is installed, linked perfectly with google.

My problem is that i don't receive anything from the output of a node (light, ..).
It's probably a misunderstanding but can you help me.

Here is a snapshot of my flow, as you see Bibliotheque Node is switching from ON to OFF (because i'm switching it on my smartphone on google home app). But nothing appears un debug window (of course setted to current flow)

Something linked to the output topic ?
Thanks

![Snap](https://github.com/coxifred/Sandbox/blob/master/smartHome.gif?raw=true)

**Comment by coxifred** [comment]
Mhh, i'm just recreate the light node from zero, and it's working now.

For information, before, i just changed the name of the light (not recreated), after that, radio silence, cache somewhere ?

**Comment by coxifred** [comment]
Sanity cleaning missing

**Comment by ckhmer1** [comment]
Did You try to restart node-red?
