### ISSUE TITLE
Error in HttpActions:reportState() - mediaDeeplink

### ISSUE THREAD

**Issue by Achronite** [mikejac/node-red-contrib-google-smarthome#107]
If you request a media player to play something it can send a media link to a 'Media Device', this then carries a mediaDeeplink in the states object from the 'Management' node, for example with the command "play The Killers on Amplifier:

```
{"msg":"Error in HttpActions:reportState()","org_msg":{"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT"},"data":{"states":{...
"6a5bd236.a5879c":{"online":true,"currentInput":"","activityState":"INACTIVE","playbackState":"PAUSED","on":false,"currentVolume":40,"isMuted":false,"mediaDeeplink":"{\"listId\":\"RDEMCa4ZRwGHEx7YkdtvgaZ0qQ\",\"logInfo\":\"ehpSREVNQ2E0WlJ3R0hFeDdZa2R0dmdhWjBxUYIBC0xRY01PSThkTWFz\",\"preferAudioContent\":false,\"searchQuery\":\"The Killers\",\"serializedYtTrackingMessage\":\"CAAQ6LYCIhMI-JaBrOHf7gIVe9MRCB2mygMV\",\"videoId\":\"LQcMOI8dMas\"}"}}}}
```

Can you add this state parameter so it does not produce an error?  It may be helpful to support local media searching in the future.

Great work by the way!  You have a new user.

**Comment by ckhmer1** [comment]
Hi,
could you please post the logs that include the request and the response?
Thanks

**Comment by Achronite** [comment]
The 'request' was made via a voice command to google assistant, this results in the following 'response' in the node-red log file, which is being reported every hour:
`
Feb 12 14:13:44 pi3 Node-RED[15334]: HttpActions:reportState(): postData = {"requestId":"2xaeal7N6m5xtPkRCnx9wh","agentUserId":"0","payload":{"devices":{"states":{"1f597a0a.ab513e":{"temperatureAmbientCelsius":0.9,"temperatureSetpointCelsius":0.9,"humidityAmbientPercent":67},"8c4ec4cb.5fe64":{"online":true,"on":true},"7bdaaf7b.11713":{"online":true,"on":false},"6a5bd236.a5879c":{"online":true,"currentInput":"","activityState":"INACTIVE","playbackState":"PAUSED","on":false,"currentVolume":40,"isMuted":false,"mediaDeeplink":"{\"listId\":\"RDEMCa4ZRwGHEx7YkdtvgaZ0qQ\",\"logInfo\":\"ehpSREVNQ2E0WlJ3R0hFeDdZa2R0dmdhWjBxUYIBC0xRY01PSThkTWFz\",\"preferAudioContent\":false,\"searchQuery\":\"The Killers\",\"serializedYtTrackingMessage\":\"CAAQ6LYCIhMI-JaBrOHf7gIVe9MRCB2mygMV\",\"videoId\":\"LQcMOI8dMas\"}"}}}}}
`

**Comment by ckhmer1** [comment]
Hi,
The patches I've in the pull request should fix also this problem.

Best regards
Claudio

**Comment by ckhmer1** [comment]
did you try the latest version?

**Comment by Achronite** [comment]
I've tried to reproduce the problem, but it looks like google have closed the media play options for the device.  It now says "I can't do that here, but you can ask me to play it on one of your other devices".

**Comment by ckhmer1** [comment]
Could you please help me to reproduce the problem sharing how to configure a node like yours and which question did you ask to google?

**Comment by Achronite** [comment]
As I said, I can't reproduce the problem.  It looks like the capability to pass a deepMediaLink (which was a youtube link in my case) no longer works; it seems like it was a bit of a loophole anyway; I couldn't find any [traits ](https://developers.google.com/assistant/smarthome/traits/mediastate) that allow you to play media (or as in my case pass a search string) for the device.  Do you have any ideas how a search could be passed through to node-red?

**Comment by ckhmer1** [comment]
Hi,
using the smart home API it should be not possible to pass arbitrary text.
