### ISSUE TITLE
Request to add Mode to Thermostat

### ISSUE THREAD

**Issue by ChutneyMary** [mikejac/node-red-contrib-google-smarthome#111]
Hi all. I have a few thermostats in use and hope someone might look at finishing off the code with 'Mode' support. ie. Heat, Cool, Dry etc. All other aspects are working fine.

**Comment by ckhmer1** [comment]
Hi,
You can try the brand new node "Google Device". It is a generic node, select the thermostat type, configure the temperature setting section and enable the humidity setting section if you need it.

**Comment by ChutneyMary** [comment]
Nice! Thanks for incorporating that.

[https://drive.google.com/file/d/1QtFeRL9xQO5xsg-JpjzopPPB72O4zFyz/view](url)

**Comment by Caprico85** [comment]
As we are migrating to @ckhmer1's Google Device, the old thermostat node won't be changed anymore. Therefore I'll close this issue.
