### ISSUE TITLE
[request] Garage Door Device

### ISSUE THREAD

**Issue by h4rdw0rk1ngdud3** [mikejac/node-red-contrib-google-smarthome#117]
Hello there,

first of all... this is a great project, thanks for that!

I am not able to implement it by myself but i would love to see a garage door device in a feature release.

For now i fake the garage door by a switch. So "open" is "on" and "closed" is "off" and i use google assistant routines to create the more human versions "open/close garage door", but on devices that don't support routines it's "garage door on/off". 
And in german this is even more inappropriate.
I know thats a bit picky, but it's just a wish  :-)

Best Regards

**Comment by Caprico85** [comment]
You could probably also fake the garage door with a window device. Windows can be opened and closed too. That would be a much more natural way to control the garage door.

**Comment by h4rdw0rk1ngdud3** [comment]
You are absolutly right, a window would be much closer to a garage door. But I didn't know that a window in Google Home can be controlled. I thought a window is just representing the state. 
At least the Google Home app doesn't have a visualization of a window (at least in germany).
But i will try this, maybe the voice commands will work as expected.

Thanks for the idea.

**Comment by Caprico85** [comment]
Yeah, unfortunately the app doesn't visualize windows (and sensors too). But it can be controlled via voice. Interestingly it is visualized on Smart Displays.

**Comment by h4rdw0rk1ngdud3** [comment]
I changed to window device now and it works well. Thanks for this great advice!
Maybe google will add a visualization for these devices in the future (I am missing this for sensors too).

**Comment by ckhmer1** [comment]
Hi,
you can use the brand new "Google Device" node. It is a generic node, just select "Garage" in the device type and you have done it.

**Comment by ckhmer1** [comment]
Hi,
did You try the "Google Device" node? Is it ok for You?

Thanks

**Comment by ChutneyMary** [comment]
I can report the Google Device node set as Garage works fine with 'Open' and 'Close'.

Interesting learning curve to get here. I'd previously defined the Garage door as a Blind to utilise the Open/Close commands. My wife has a habit of saying 'Hey Google, open all the blinds' which results in the blinds and the garage door opening... :þ

The visualisation of a garage door is shown in the Google Home app, but isn't animated to show the current status.
The visualisation of a garage door isn't shown on a Smart Display (under Rooms in the menu structure). However, when the voice command is given, a visualisation is briefly shown of whether the Garage Door status is open or closed.

A query can be made - 'Is the garage door open?' or 'Is the garage door closed?' which brings up the correct visualisation.

**Comment by Caprico85** [comment]
That's the old problem of visualisations. Some devices are visualised, some aren't, some only partly. Unfortunately nothing we can do here, visualisations has to be implemented by Google.

Nevertheless, garage doors are implemented, I'm closing this now.
