### ISSUE TITLE
Missing Bridge error

### ISSUE THREAD

**Issue by Paul-Reed** [mikejac/node-red-contrib-google-smarthome#119]
Hi. Just followed the setup guide, and when I deploy the Management node (setup as per the guide) I get the following error reported in the node-red log;

`19 Mar 20:49:31 - [error] [google-mgmt:Smarthome] missing bridge`

![smartnode](https://user-images.githubusercontent.com/973580/111841259-9ac68a80-88f5-11eb-92e4-acdefc5a5c8b.JPG)

and in the debug;

![smarthomeerror](https://user-images.githubusercontent.com/973580/111841171-736fbd80-88f5-11eb-863f-975735869bc7.JPG)

Not sure where I have gone wrong?

**Comment by Caprico85** [comment]
It seems a JSON file is corrupted. Judging by the message there is a newline somewhere it should'nt be. Perhaps you opened one the files in an editor and accidentally inserted a wrong newline or switched to the wrong line endings format (CRLF vs. LF).

There are mainly two JSON files this module uses:

**JWT Token**
This is the file you downloaded in the step [Enable HomeGraph API](https://github.com/mikejac/node-red-contrib-google-smarthome#enable-homegraph-api). Create a new key to get a new key file. Preferably copy the file around using SFTP (or some other file transfer) and not via clipboard to avoid altering the file.

**Auth Storage**
This is the file google-smarthome-auth-*.json in your Node-Red's user directory (where your settings.js, flows.json etc. lives). Delete this file. It will be recreated as needed.

**Comment by Paul-Reed** [comment]
Thanks for the reply Michael.
I think it was the JWT token that was corrupt, because I obtained a new key file and moved the file instead of copying/pasting it (I also had a typo in the node config - port number) and now it's working fine 👍 

Thank you
