### ISSUE TITLE
Fireplace device not online / configuration mode

### ISSUE THREAD

**Issue by limpens** [mikejac/node-red-contrib-google-smarthome#120]
I previously used the 'On/Off Fan' device to control my pellet-stove, this works nice.
Since the recent addition of the 'On/Off Fireplace', I thought to swap the device from fan to fireplace.

Unfortunately, the fireplace symbol shows up in the Google Home app with a small cog over the icon, which is the only action available, to configure the device.

Using the different methods of reporting the state (payload with online, payload with online/on in object) doesn't change the state in the home app.
Reverting from the fireplace device to fan resolved the state. Am I missing something?
Sincerely and thanks for the great work!

**Comment by Caprico85** [comment]
Some devices (like windows, sensors and most probably fireplaces too) don't have an user interface in the Google Home app. They can be controlled via voice, interestingly they also have a graphical user interface on Smart Displays, but not in the app. Unfortunately there seems to be nothing we can do. This is something Google has to implement in their app.

**Comment by limpens** [comment]
Thank you for the explanation.
I will be using the 'Fan' device to control the stove, no problem at all, too bad it can't be controlled using the home app.

Regards.
