### ISSUE TITLE
Error not catched: node-red crashes

### ISSUE THREAD

**Issue by 0rsa** [mikejac/node-red-contrib-google-smarthome#126]
Versions:
Node-red 1.2.9
Nodejs 14.16.0
Debian Buster
node-red-contrib-google-smarthome 0.0.63

Log:
> Device:getStates(): deviceIds = undefined
> Device:getStates(): using empty device list
> HttpActions:reportState(): deviceId = undefined
> HttpActions:reportState(): states = {"fa8e20c5.7d06d":{"online":true,"openPercent":0},"86c81724.79c918":{"online":true,"openPercent":0},"f732b116.f23f3":{"online":true,"openPercent":30},"62624427.cf535c":{"online":true,"openPercent":0},"24677563.4b2e4a":{"online":true,"openPercent":0},"f58a3f67.28d01":{"online":true,"openPercent":0},"75c97148.d2dd9":{"online":true,"openPercent":0},"beee5a7d.9bba78":{"online":true,"openPercent":0},"92a6284e.77c578":{"online":true,"openPercent":0},"d392f64b.da9a88":{"online":true,"on":false},"3dc2bed2.a70e42":{"online":true,"on":false},"4c2cd8c1.4316c8":{"online":true}}
> HttpActions:reportState(): notifications = undefined
> HttpActions:reportState(): postData = {"requestId":"3R0cpuS9cvEb5436Tp6neX","agentUserId":"0","payload":{"devices":{"states":{"fa8e20c5.7d06d":{"online":true,"openPercent":0},"86c81724.79c918":{"online":true,"openPercent":0},"f732b116.f23f3":{"online":true,"openPercent":30},"62624427.cf535c":{"online":true,"openPercent":0},"24677563.4b2e4a":{"online":true,"openPercent":0},"f58a3f67.28d01":{"online":true,"openPercent":0},"75c97148.d2dd9":{"online":true,"openPercent":0},"beee5a7d.9bba78":{"online":true,"openPercent":0},"92a6284e.77c578":{"online":true,"openPercent":0},"d392f64b.da9a88":{"online":true,"on":false},"3dc2bed2.a70e42":{"online":true,"on":false},"4c2cd8c1.4316c8":{"online":true}}}}}
> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> SyntaxError: Unexpected token < in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at /root/.node-red/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:574:30
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

Node-red crashed during the night as a result of this error (after hours running)

**Comment by Caprico85** [comment]
This should not happen anymore with 0.0.64. The last version added better error handling on state reporting so Node-Red shouldn't crash anymore.
