### ISSUE TITLE
Have the webserver under the same url than node-red

### ISSUE THREAD

**Issue by Armaell** [mikejac/node-red-contrib-google-smarthome#13]
Hi ! I'm still setting up your contribution, looks promising !

I've just stumbled on a problem that stomped me for an hour. Simply your webserver doesn't take in consideration the _httpRoot_ setting in the _settings.js_ file.  
So I had my reverse proxy sending my request to `/node-red/oauth`, but your webserver was expecting `/oauth`, of course.

Would it be possible to use that settings ? Or maybe make it configurable in the already long server configuration.  
For now it's easily bypassable by just using a subdomain instead of a path.

Thank you !

**Comment by ckhmer1** [comment]
Hi,
this issue should be already fixed, isn't it?
Thanks

**Comment by Caprico85** [comment]
@ckhmer1 Yes, with your contributions this should now be fixed.
