### ISSUE TITLE
http server is not running

### ISSUE THREAD

**Issue by Grewamor** [mikejac/node-red-contrib-google-smarthome#133]
All is working fine, but i get every minute this error:

`HttpActions:reportState(): http server is not running`

Report Interval is: -1

What could be the problem?

**Comment by Caprico85** [comment]
You say everything works, including controlling your devices or asking for their state? That shouldn't be possible if the http server is not running.

One possible explanation would be if there is an additional http server somewhere. One "good" server doing the work and one additional "bad" server causing errors. Do you have a second management node somewhere?

I guess you are seeing this error in Node-Red's log. Do you have any other errors there, especially directly after restarting Node-Red or redeploying your flows?

**Comment by Grewamor** [comment]
After a restart the error is away 🤷‍♂️
