### ISSUE TITLE
Fail to add service to Google Home app

### ISSUE THREAD

**Issue by Mushin** [mikejac/node-red-contrib-google-smarthome#135]
**Issue:**
When trying to 'set up a device' in the Google Home app, I click on the '[Test] servicename', and I get the login screen. After entering the details and logging in, it then says 'linking your account...' and then it goes back to the 'set up a device' screen. The service is not added.

**Setup:** 
- Home Assistant OS v2021.4.4 (running in a VM on my Unraid server)
- Node-RED v8.2.1
- node-red-contrib-google-smarthome v0.0.65
- SSL keys provided by LetsEncrypt
- Port forwarded to the HA IP address in my router
- Dynamic DNS set up for the smarthome URL
- Using username/password auth (but have also tried Google login)

**Troubleshooting:**
- Did everything [here](https://flows.nodered.org/node/node-red-contrib-google-smarthome#troubleshooting)
- Did everything [here](https://github.com/mikejac/node-red-contrib-google-smarthome/wiki/Possible-errors)

In particular:
- Removed special characters from client ID and secret
- Generated a new jwt key
- Logging out and back in to the Google Home app
- Starting over with a completely new action
- Restarting node-RED, HA and the HA OS VM
- I can connect to the server with a GET request test
- SSL keys are valid

**Logs:**
- No errors from debugging the Management node (while running, or after restarting flows)
- Node-RED log:

```
16 Apr 10:55:06 - [info] [server:Home Assistant] Connecting to http://supervisor/core
16 Apr 10:55:06 - [info] [server:Home Assistant] Connected to http://supervisor/core
HttpAuth:httpAuthRegister(/token): query = {}
HttpAuth:httpAuthRegister(/token): body = {"grant_type":"refresh_token","refresh_token":"[REMOVED]","client_id":"[REMOVED]","client_secret":"[REMOVED]"}
Auth:isValidRefreshToken(): valid refreshToken "[REMOVED]" for user [REMOVED]
HttpAuth:handleRefreshToken(): respond success; token = {"token_type":"bearer","access_token":"[REMOVED]","expires_in":3600}
POST /token 200 2.975 ms - 103
HttpActions:httpActionsRegister(/smarthome): request.headers = {"content-type":"application/json;charset=UTF-8","google-assistant-api-version":"v1","authorization":"Bearer [REMOVED]","host":"[REMOVED]","content-length":"80","connection":"keep-alive","user-agent":"Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)","accept-encoding":"gzip,deflate,br"}
HttpActions:httpActionsRegister(/smarthome): request.headers.authorization = Bearer [REMOVED]
HttpActions:httpActionsRegister(/smarthome): reqdata = {"inputs":[{"intent":"action.devices.SYNC"}],"requestId":"[REMOVED]"}
HttpActions:httpActionsRegister(/smarthome): user: [REMOVED]
HttpActions:httpActionsRegister(/smarthome): SYNC
HttpActions:_sync()
POST /smarthome 200 2.337 ms - 79
```

- Google cloud log ("item = syncLog"):

```
{
  "insertId": "[REMOVED]",
  "jsonPayload": {
    "syncLog": {
      "syncs": [
        {
          "requestId": "[REMOVED]",
          "status": "OK",
          "httpLatencyMsec": "230"
        }
      ]
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "[REMOVED]"
    }
  },
  "timestamp": "2021-04-16T09:55:19.792259180Z",
  "severity": "DEBUG",
  "logName": "projects/[REMOVED]/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-04-16T09:55:19.792259180Z"
}
```

**Comment by Caprico85** [comment]
The log shows no errors. So its hard to say what went wrong.

You could try increasing the log level by setting "level" (below logging > console) to "debug" in your settings.js. Restart Node-Red, then try again to login.

Somewhere I read this can also result from having broken devices or having no devices at all. I never had problems with this, but you could try removing your devices or adding only one simple device node (outlet for example).

**Comment by Mushin** [comment]
Thanks. This resolved itself eventually - I'm not sure exactly how, but a few days later I checked in the Google Home app and the service was added. I don't think anything I did fixed it.

**Comment by Caprico85** [comment]
Glad to hear that. Probably only some hiccup by Google.
