### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by Armaell** [mikejac/node-red-contrib-google-smarthome#14]
Hi again,

I got the same exact issue than https://github.com/mikejac/node-red-contrib-google-smarthome/issues/2

I've set the login at 'aa' and the password at 'aa' too,  
then I go to link the device in the Google Home app, I see the login and password field where I enter in both field 'aa', click on the [LOGIN] button, then nothing. I just see a greyish blank page.  
On node-red, I get this message : `{"topic":"management","payload":{"_type":"login","msg":"invalid user"}}`

Well, I doubt to have misspelled something here 😄

**Comment by merlinschumacher** [comment]
Did you change the password from before? It seems as if the json file containing the settings won't get updated, when you change the settings in the configuration node.

**Comment by Armaell** [comment]
I did change multiple times, thinking first I typed it wrongly, then maybe I should not use symbols, and at last trying to simplest of all with 'aa'.

So it well possible too, since I'm using Docker Desktop for Windows, and binded volumes with this version keep having annoying side effects. But on another hand, when I restart node-red, the configuration do stay...
Anyway, I'm not finding where this could be stored ? To check it

**Comment by Caprico85** [comment]
The folder is always called "storage", but the location can vary. On different tries I have seen it in /usr/src/node-red/.node-persist/storage, /usr/src/node-red/node_modules/node-persist/storage and /data/node_modules/node-persist/storage. Seems to depend on how you install Node-RED and this module.

**Comment by Armaell** [comment]
Ok, thank you both, it works !

I found the file at /usr/src/node-red/.node-persist/storage and it was effectively not up to date. Deleted it and everything then was smooth.

But I still have no idea what is the problem, node-red did had the rights for the folder.

**Comment by Caprico85** [comment]
No idea why this happens. I created separate issues for both problems and will take a look on it if I can find some time.
