### ISSUE TITLE
Dispense error

### ISSUE THREAD

**Issue by vernandoRGN** [mikejac/node-red-contrib-google-smarthome#140]
I got `"TypeError: me.supported_dispense_items.forEach is not a function"` for Pet Feeder device type
my supportedDispenseItems.json 
```json
{
  "supportedDispenseItems": [
    {
      "item_name": "food",
      "item_name_synonyms": [
        {
          "lang": "en",
          "synonyms": [
            "food",
            "cat food"
          ]
        }
      ],
      "supported_units": [
        "PORTION"
      ],
      "default_portion": {
        "amount": 1,
        "unit": "PORTION"
      }
    }
  ]
}
```
any clue?

**Comment by ckhmer1** [comment]
Hi,
I'll check it as soon as possible.
Thanks for reporting.
Claudio

**Comment by ckhmer1** [comment]
Hi,
Your supportedDispenseItems.json is not correct, it should be an array of objects instead of yours is an object.
Find below an example:

[
	{
		"item_name": "water",
		"item_name_synonyms": [
			{
				"lang": "en",
				"synonyms": [
					"water"
				]
			}
		],
		"supported_units": [
			"TEASPOONS",
			"TABLESPOONS",
			"FLUID_OUNCES",
			"CUPS",
			"PINTS",
			"QUARTS",
			"GALLONS",
			"MILLILITERS",
			"LITERS",
			"DECILITERS"
		],
		"default_portion": {
			"amount": 2,
			"unit": "CUPS"
		}
	}
]

**Comment by vernandoRGN** [comment]
my bad, it's okay now
