### ISSUE TITLE
FanSpeed not working for the generic "GoogleDevice" node.

### ISSUE THREAD

**Issue by homefefeld** [mikejac/node-red-contrib-google-smarthome#141]
Hello there, 

I'm trying to use FanSpeed with the generic "Google Device".
The fan speed selector appears on my Google Hub, but if I change it nothing is returned by the node.
also, if I set the fan speed on the node, it doesn't get transfert to google home.

Thanks for your help. (Again this node is GREAT !!!)

G.

**Comment by ckhmer1** [comment]
Hi,
I'll check it as soon as possible.
Thanks for reporting.
Claudio

**Comment by homefefeld** [comment]
it is white a vaccum node :
here is the FanSpeed.json:
FanSpeeds4Roborock.json 
{
    "speeds": [
        {
            "speed_name": "Quiet",
            "speed_values": [
                {
                    "speed_synonym": [
                        "quiet",
                        "low",
                        "slow"
                    ],
                    "lang": "en"
                }
            ]
        },
        {
            "speed_name": "Balanced",
            "speed_values": [
                {
                    "speed_synonym": [
                        "balanced",
                        "mid"
                    ],
                    "lang": "en"
                }
            ]
        },
        {
            "speed_name": "Turbo",
            "speed_values": [
                {
                    "speed_synonym": [
                        "turbo"
                    ],
                    "lang": "en"
                }
            ]
        },
        {
            "speed_name": "Max",
            "speed_values": [
                {
                    "speed_synonym": [
                        "Max",
                        "Full"
                    ],
                    "lang": "en"
                }
            ]
        }
    ],
    "ordered": true
}

**Comment by ckhmer1** [comment]
Hi,
I'm not able, in Italian, to ask Google to set the fan speed. Google always returns me a web search :(
Could You please send me the log of your request?
Thanks

**Comment by homefefeld** [comment]
? this ?
{"currentFanSpeedSetting": "Balanced"};
or where do I get the log of my request ?

**Comment by homefefeld** [comment]
do you use Google Hub ? or google home only ?

**Comment by thedroid** [comment]
I am having the same issue here.  Device config ![fan config](https://user-images.githubusercontent.com/903065/115798780-aac20600-a39c-11eb-90cb-72d565ad7e9c.jpg)

availableFanSpeeds.json file
`{
    "speeds": [
      {
        "speed_name": "speed_low",
        "speed_values": [
          {
            "speed_synonym": [
              "low",
              "slow"
            ],
            "lang": "en"
          }
        ]
      },
{
        "speed_name": "speed_medium",
        "speed_values": [
          {
            "speed_synonym": [
              "medium"
            ],
            "lang": "en"
          }
        ]
      },	  
      {
        "speed_name": "speed_high",
        "speed_values": [
          {
            "speed_synonym": [
              "high",
              "fast"
            ],
            "lang": "en"
          }
        ]
      }
    ],
    "ordered": true
  }
`

It shows up in my devices as a fan 
![fan](https://user-images.githubusercontent.com/903065/115799381-0345d300-a39e-11eb-8cc3-4fc1f0f2840a.jpg)

But when I select it it shows up as just an On/Off button
![fan2](https://user-images.githubusercontent.com/903065/115799518-42742400-a39e-11eb-88d9-8cf579f515d2.jpg)

If I try to send a speed to it, it says that the "Node-Home" is unavailable and displays like a switch.
![fan3](https://user-images.githubusercontent.com/903065/115799632-8c5d0a00-a39e-11eb-82ec-89ef60acce75.jpg)


Hope this info helps

**Comment by homefefeld** [comment]
the issue

**Comment by thedroid** [comment]
> the issue

Huh?

**Comment by ckhmer1** [comment]
Hi,
I use google home only no hub.
Are You able to stop node-red and execute it by hand, with a command-line command?
In this way node-red prints the logs on the screen.
Otherwise, You have to configure node-red to write logs in a file,  see [Logging](https://nodered.org/docs/user-guide/runtime/logging)

Thanks

**Comment by Paul-Reed** [comment]
@homefefeld why have you closed this issue.
Have you resolved the problem? If so, what was causing it?

**Comment by thedroid** [comment]
Please see the **TypeError: this.available_fan_speeds.forEach is not a function** error below which occurs when I try to set the fan speed.

`Device:execCommand(): device = {"id":"645afb11.127fa4","states":{},"command":"action.devices.commands.SetFanSpeed"}
google-smarthome:DeviceNode.execCommand: command {"command":"action.devices.commands.SetFanSpeed","params":{"fanSpeed":"speed_low"}}
google-smarthome:DeviceNode.execCommand: states {"online":true,"currentFanSpeedSetting":"","currentFanSpeedPercent":0,"on":false}
POST /smarthome  3.176 ms - 1248
TypeError: this.available_fan_speeds.forEach is not a function
at DeviceNode.execCommand (/data/node_modules/node-red-contrib-google-smarthome/devices/device.js:2097:47)
at GoogleSmartHome.execCommand (/data/node_modules/node-red-contrib-google-smarthome/lib/Devices.js:133:49)
at GoogleSmartHome._execDevice (/data/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:387:27)
at GoogleSmartHome._exec (/data/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:335:50)
at /data/node_modules/node-red-contrib-google-smarthome/lib/HttpActions.js:209:28
at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
at next (/data/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/data/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
at /data/node_modules/express/lib/router/index.js:281:22`

**Comment by homefefeld** [comment]
Sorry guys, I closed this issue by mistake....
no the issue remains..

**Comment by homefefeld** [comment]
Yes !! I have the same error as @thedroid .

**Comment by ckhmer1** [comment]
Hi,

the fan speeds must be an array, yours is an object.
Please find below an example:

`
[
    {
        "speed_name": "speed_low",
        "speed_values": [
            {
                "speed_synonym": [
                    "low",
                    "slow"
                ],
                "lang": "en"
            }
        ]
    },
    {
        "speed_name": "speed_high",
        "speed_values": [
            {
                "speed_synonym": [
                    "high",
                    "fast"
                ],
                "lang": "en"
            }
        ]
    }
]
`

**Comment by thedroid** [comment]
Made changes with the exact array above, now trying to set a fan speed just pulls up a google search with fans on the web.  The command does not make it to the logs or node red.

Below is the log where the fan device is being setup.

`google-smarthome:DeviceNode.loadJson: Fan speeds
google-smarthome:DeviceNode.loadJson: filename /data/availableFanSpeeds.json
google-smarthome:DeviceNode.loadJson: data loaded
google-smarthome:DeviceNode.loadJson: json = [{"speed_name":"speed_low","speed_values":[{"speed_synonym":["low","slow"],"lang":"en"}]},{"speed_name":"speed_high","speed_values":[{"speed_synonym":["high","fast"],"lang":"en"}]}]
google-smarthome:DeviceNode.constructor: Fill disabled
google-smarthome:DeviceNode.constructor InputSelector disabled
google-smarthome:DeviceNode.constructor: Modes disabled
google-smarthome:DeviceNode.constructor: Toggles disabled
google-smarthome:DeviceNode.registerDevice: device_type FAN
google-smarthome:DeviceNode.registerDevice: device = {"id":"645afb11.127fa4","states":{"online":true,"currentFanSpeedSetting":"","currentFanSpeedPercent":0,"on":false},"notificationSupportedByAgent":false,"properties":{"type":"action.devices.types.FAN","traits":["action.devices.traits.FanSpeed","action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Fan"],"name":"fan"},"roomHint":"Office","willReportState":true,"attributes":{"reversible":false,"commandOnlyFanSpeed":false,"availableFanSpeeds":[{"speed_name":"speed_low","speed_values":[{"speed_synonym":["low","slow"],"lang":"en"}]},{"speed_name":"speed_high","speed_values":[{"speed_synonym":["high","fast"],"lang":"en"}]}],"commandOnlyOnOff":false,"queryOnlyOnOff":false},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-device-fan-v1","swVersion":"1.0","hwVersion":"1.0"},"customData":{"nodeid":"645afb11.127fa4","type":"nr-device-fan"}}}
Device:registerDevice(): new device; device = {"id":"645afb11.127fa4","states":{"online":true,"currentFanSpeedSetting":"","currentFanSpeedPercent":0,"on":false},"notificationSupportedByAgent":false,"properties":{"type":"action.devices.types.FAN","traits":["action.devices.traits.FanSpeed","action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Fan"],"name":"fan"},"roomHint":"Office","willReportState":true,"attributes":{"reversible":false,"commandOnlyFanSpeed":false,"availableFanSpeeds":[{"speed_name":"speed_low","speed_values":[{"speed_synonym":["low","slow"],"lang":"en"}]},{"speed_name":"speed_high","speed_values":[{"speed_synonym":["high","fast"],"lang":"en"}]}],"commandOnlyOnOff":false,"queryOnlyOnOff":false},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-device-fan-v1","swVersion":"1.0","hwVersion":"1.0"},"customData":{"nodeid":"645afb11.127fa4","type":"nr-device-fan"}}}
Device:execDevice(): BEGIN
Device:execDevice(): device = {"id":"645afb11.127fa4","states":{"online":true,"currentFanSpeedSetting":"","currentFanSpeedPercent":0,"on":false},"notificationSupportedByAgent":false,"properties":{"type":"action.devices.types.FAN","traits":["action.devices.traits.FanSpeed","action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Fan"],"name":"fan"},"roomHint":"Office","willReportState":true,"attributes":{"reversible":false,"commandOnlyFanSpeed":false,"availableFanSpeeds":[{"speed_name":"speed_low","speed_values":[{"speed_synonym":["low","slow"],"lang":"en"}]},{"speed_name":"speed_high","speed_values":[{"speed_synonym":["high","fast"],"lang":"en"}]}],"commandOnlyOnOff":false,"queryOnlyOnOff":false},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-device-fan-v1","swVersion":"1.0","hwVersion":"1.0"},"customData":{"nodeid":"645afb11.127fa4","type":"nr-device-fan"}}}
Device:execDevice(): properties; key = "type"
Device:execDevice(): properties; key = "traits"
Device:execDevice(): properties; key = "name"
Device:execDevice(): properties; key = "roomHint"
Device:execDevice(): properties; key = "willReportState"
Device:execDevice(): properties; key = "attributes"
Device:execDevice(): properties; key = "deviceInfo"
Device:execDevice(): properties; key = "customData"
Device:execDevice(): states; key = "online"
Device:execDevice(): states; key = "currentFanSpeedSetting"
Device:execDevice(): states; key = "currentFanSpeedPercent"
Device:execDevice(): states; key = "on"
Device:execDevice(): this._devices[device.id] = {"states":{"online":true,"currentFanSpeedSetting":"","currentFanSpeedPercent":0,"on":false},"properties":{"type":"action.devices.types.FAN","traits":["action.devices.traits.FanSpeed","action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Fan"],"name":"fan"},"roomHint":"Office","willReportState":true,"attributes":{"reversible":false,"commandOnlyFanSpeed":false,"availableFanSpeeds":[{"speed_name":"speed_low","speed_values":[{"speed_synonym":["low","slow"],"lang":"en"}]},{"speed_name":"speed_high","speed_values":[{"speed_synonym":["high","fast"],"lang":"en"}]}],"commandOnlyOnOff":false,"queryOnlyOnOff":false},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-device-fan-v1","swVersion":"1.0","hwVersion":"1.0"},"customData":{"nodeid":"645afb11.127fa4","type":"nr-device-fan"}},"executionStates":[]}
Device:execDevice(): END`

**Comment by ckhmer1** [comment]
Hi,
I'm sorry, I thin k I've to release a fix for that.
I'll do it as soon as possible.
Claudio

**Comment by ckhmer1** [comment]
Hi,
Merge request sent.

Waiting for feedback.

**Comment by thedroid** [comment]
The pull request does not seem to make any difference on my end.  Merged locally but I am still having the same issue with a search showing up and the request not reaching node-red.

**Comment by ckhmer1** [comment]
Hi,
did You disable the "Supports fan speed percent" option from the config?

**Comment by thedroid** [comment]
Hi,

I missed that option.  It appears to work now thanks!.  Still only shows up as an on/off toggle in the UI, but I really only use that for testing.

**Comment by ckhmer1** [comment]
Hi,
unfortunately, a lot of devices are shown in UI as an on/off toggle.

**Comment by Caprico85** [comment]
I released v0.0.67 including @ckhmer1's fix for fan speed.

**Comment by homefefeld** [comment]
this is now working like a charm.
Thank you.

**Comment by Chrischi-** [comment]
@ckhmer1 
can you also take a look at the Mode function?

"TypeError: me.available_modes.forEach is not a function".

looks like a similar problem to me.

**Comment by homefefeld** [comment]
@Chrischi- 
the mode.json should be an array..
the json should not start with : {
  "availableModes": ....

But only with the array, the json file should be something like : 
==================================

[
    {
      "name": "load_mode",
      "name_values": [
        {
          "name_synonym": [
            "load",
            "size",
            "load size"
          ],
          "lang": "en"
        }
      ],
      "settings": [
        {
          "setting_name": "small_load",
          "setting_values": [
            {
              "setting_synonym": [
                "small",
                "half"
              ],
              "lang": "en"
            }
          ]
        },
        {
          "setting_name": "large_load",
          "setting_values": [
            {
              "setting_synonym": [
                "large",
                "full"
              ],
              "lang": "en"
            }
          ]
        }
      ],
      "ordered": true
    }
  ]
==================================

**Comment by homefefeld** [comment]
@ckhmer1 ,

just one note , doing the JSON like in the google example would be more intuitive, i.e leaving **"{"availableModes":..** or **{"availableFanSpeeds": {**.       People will may have trouble when they use your node for the first time.

G.
