### ISSUE TITLE
Request for more guidance on Google Device node

### ISSUE THREAD

**Issue by ChutneyMary** [mikejac/node-red-contrib-google-smarthome#143]
I'm trying to set up a Google Device node as Device Type "Charger". I'm struggling with the existing instructions trying to determine what is required in the node feeding the Google Device node.

I have a Change Node preceeding the Google Device node that sets msg.topic to capacityRemaining. I'm injecting a number which is the State of Charge of a solar battery as a percentage. The node always displays ON FULL.

I would welcome more generic instructions be provided for the Google Device node. Perhaps further examples that link the Google Trait Schema with how to construct the Node Red Change Node. I'm just missing some vital link in understanding how to build the required structure in Node Red.

**Comment by rborkows** [comment]
I'm struggling with a similar issue, trying to get a SENSOR working. I can't seem to format the input correctly, or figure out how to ask the assistant for sensor readings, but I did manage to get battery levels working, so here's what I have.

Your inject should push JSON, and here's an example:

{
    "descriptiveCapacityRemaining": "CRITICALLY_LOW",
    "capacityRemaining": [
        {
            "rawValue": 5,
            "unit": "PERCENTAGE"
        }
    ],
    "isCharging": false,
    "isPluggedIn": false
}

this is documented at: https://developers.google.com/assistant/smarthome/traits/energystorage

**Comment by ChutneyMary** [comment]
When you said you've got battery levels working, what did you mean?

I've got a Sensor node with an inject of the suggested JSON. I only see a symbol with a cog on the top-right in the Google Home app. I also can't query it's value. Injecting the values above doesn't change anything.

[https://drive.google.com/file/d/1Y3ST-ET5QswIGUUyZOdNo_Y57J4dFheZ/view](url)

**Comment by Bastelritius** [comment]
Hi,

I have the same problem that I want to setup a senor for Temperature and Humidity. I also see only the symbol with the cog in google home app. I tried to inject the values as shown in the example.
The test flow is the following and here the Humidity value is also shown below the Google node:
![flow](https://user-images.githubusercontent.com/57993456/144813769-b0a12e9e-f176-4e9c-acfe-ec211e84112c.JPG)
Injection looks like this:
![node injection](https://user-images.githubusercontent.com/57993456/144813961-1d922e29-edbd-4860-ba33-9a488de90a82.JPG)
And my Google node Sensor device looks like this:
![node_temp](https://user-images.githubusercontent.com/57993456/144814029-9a3dc089-b1bb-4991-9aca-e52a652c6856.JPG)
Could someone provide a example how to setup a sensor device or can say what I´m doing wrong?

**Comment by Caprico85** [comment]
@Bastelritius Can you control your sensor with voice commands?

My sensor is set up like yours and it works. It can be controlled using voice, but not in the app. This is a known problem. Some devices and traits are not (yet?) supported in the app. See https://developers.google.com/assistant/smarthome/develop/touch-controls#supported_device_types for details.

**Comment by FireWizard52** [comment]
Hi all,

Is a guidance of the "Device" node still needed.
This thread is almost 3 years old!. In the meantime @Caprico85 has added a "Basic Guide" to the "Setup Instructions".
Also the "examples" folder contains several Examples. Do we need more. If so,indicate which one.

If someone needs help with a specific node, let it know here as well.
If not this thread can be closed.

Regards

**Comment by Caprico85** [comment]
I'm closing this now. Reopen if needed.
