### ISSUE TITLE
Errors and exceptions in Google device node

### ISSUE THREAD

**Issue by Vernando05** [mikejac/node-red-contrib-google-smarthome#144]
This is a question rather than an issue. Does anyone know how to pass error and exceptions data into the google device node?
for example this global error
```
{
  "requestId": "12345",
  "payload": {
    "errorCode": "inSoftwareUpdate",
    "status" : "ERROR"
  }
}
```
It requires the requestId value, any idea how to obtain it?

**Comment by Caprico85** [comment]
It's currently not possible. Even if you had the requestId, you couldn't use it. The device nodes currently only accept "normal" inputs, but no error states. Would be a nice addition though.

**Comment by ckhmer1** [comment]
Hi,
it is possible to send a StatusReport with the device status, see https://developers.google.com/assistant/smarthome/traits/statusreport

You could send to google info like the following:

      "blocking": true,
      "deviceTarget": "alarm_2",
      "priority": 0,
      "statusCode": "needsSoftwareUpdate"

I've just sent a patch request implementing this behavior. Is it enough for You?
Claudio

**Comment by ckhmer1** [comment]
It is also possible to set the device in error using an input message with the following data:

topic: errorCode
payload: the error code (i.e.: inSoftwareUpdate)

all the next requests coming from Google will be answered with the error code specified.

To remove the error from the device, use an input message with the following data:

topic: errorCode
payload: empty

This should meet Your requirement.

**Comment by ckhmer1** [comment]
This issue has been fixed several months ago, any feedback on it?
