### ISSUE TITLE
temperatureUnitForUX in sensor.js should be configurable for C or F

### ISSUE THREAD

**Issue by sprior** [mikejac/node-red-contrib-google-smarthome#151]
The temperatureUnitForUX property in sensor.js is currently hardcoded to C which means that Google Assistant will always display/say the temperature in Celsius - the temperature is always uploaded to Google in Celsius and the value of temperatureUnitForUX  determines whether it is left in Celsius or converted to Fahrenheit before being delivered to the user.

**Comment by ckhmer1** [comment]
Hi,
as a workaround/quick fix, using the device node, You are able to select the if temperatureUnitForUX.

Claudio

**Comment by Caprico85** [comment]
As we are migrating to @ckhmer1's Google Device (which supports C/F), the old sensor node won't be changed anymore. Therefore I'll close this issue.
