### ISSUE TITLE
Volume issue with "Device" node

### ISSUE THREAD

**Issue by homefefeld** [mikejac/node-red-contrib-google-smarthome#152]
this is probably for @ckhmer1 ,

while the device using Volume is properly set up in google,  it seems to me that if you deploy a device node your code ignore the max_level_value set in the configuration and takes your default values 
    volume_max_level  =  100
    volume_default_percentage  =  40
    level_step_size  =  1
This is causing me some problems as for onbe of my node the max volume should be 12 and the level_step_size  should be 3.
when I increase the volume, it goes beyond 12 up to 100...

Let me know how I could help here.

F.

**Comment by ckhmer1** [comment]
Hi,
the following node traits support the notifications:

* ObjectDetection
* RunCycle
* SensorState
* LockUnlock
* NetworkControl
* OpenClose

To send a message, just send a message to the node with a topic ending with one of the previous trait names and the payload the right content (see the trait documentation).

The plugin for those nodes sets the attribute notificationSupportedByAgent to true.

Unfortunately, this seems not to be enough to have a notification, and I don't understand what's missing.

Could You review the notification hoping You find some error?

Thanks
Claudio

**Comment by ckhmer1** [comment]
I'll have a look at this problem as soon as possible.
Thanks

**Comment by Paul-Reed** [comment]
@homefefeld - as you have not responded, can this issue now be closed?

**Comment by homefefeld** [comment]
let's close it then.I will test again I will reopen if not working .
Thanks guys.

G
