### ISSUE TITLE
Two way control

### ISSUE THREAD

**Issue by INDRANI125** [mikejac/node-red-contrib-google-smarthome#163]
Can we get a response from Google assist as well after configuring some nodes? or is it only one way?

**Comment by Caprico85** [comment]
What do you mean exactly? With node-red-contrib-google-smarthome you can ask Assistant for the device ("Hey Google, is the light on?"). And you can control your device via Assistant ("Hey Google, turn the light on"). Devices can also be controlled or queried in the Google Home App (at least if Google has implemented an UI for that kind of device).
