### ISSUE TITLE
failed with code: OPEN_AUTH_FAILURE"

### ISSUE THREAD

**Issue by neodino** [mikejac/node-red-contrib-google-smarthome#166]
Cannot use voice command/Google Assistant. Getting "Sorry i could not reach xxxxxxx" back.
I can successfully control the devices trough the Google Home App. 

Anyone else has this issue?

Seems some permission issue. Any idea how to fix?
<img width="793" alt="Screen Shot 2021-08-01 at 5 21 57 pm" src="https://user-images.githubusercontent.com/28005257/127762813-97bf06ed-d43f-467f-8c38-24c993ea8ed8.png">
<img width="1230" alt="Screen Shot 2021-08-01 at 5 23 44 pm" src="https://user-images.githubusercontent.com/28005257/127762872-e7d4fcd0-f695-4d03-8551-11f10619735d.png">

**Comment by Caprico85** [comment]
Had those OPEN_AUTH_FAILURE errors a few times myself. It happened mostly when Google was not able to renew the access tokens. Either when my server was down, Node-RED crashed or when I had wrong permissions set on the auth storage file (google-smarthome-auth-<id> in Node-RED's data directory). It seems Google tries a few times to renew the token, If this fails, Google marks the server as faulty and only tries again after unlinking and relinking the account.

Strange thing is that in your case the app works, voice does not. I would have thought that voice and app use the same authentication mechanisms. So if one fails, the other will fail too.

Did you try unlinking and relinking your account? Do you have any error messages in Node-RED's debug panel?

**Comment by neodino** [comment]
Thanks for reply. All OK now. I tried few things(not in any particular order) and eventually it start working.

- restarted node-red
- re-linked app/account
- recreated project under google actions
- Called "Hey Google Sync my devices" 

FYI: there was no error messages on the NODE-RED side at the time only 200 OK 

 Please close issue. Thanks again.

**Comment by Caprico85** [comment]
Glad to hear that.
