### ISSUE TITLE
Can't add authorized email addresses

### ISSUE THREAD

**Issue by brianmay** [mikejac/node-red-contrib-google-smarthome#172]
Whenever I add authorised email addresses, click save, and then go back to the edit form again, the email addresses I just entered have disappeared.

**Comment by Caprico85** [comment]
Thank you. There really seems to be a problem. I'll have a look this evening. In the mean time you could try to disable Google login and use the "normal" username/password login. That should still work.


Or maybe if @ckhmer1 is faster than me. These are the messages I get in Chrome's dev tools when I try to save and reopen the configuration with an email address. Happens with Node-RED 2.0.5.

![image](https://user-images.githubusercontent.com/2081806/129659953-7aa2daf4-d61f-480b-b3e6-188bde015cac.png)

**Comment by ckhmer1** [comment]
Hi,
I'm sorry but I'm not able to reproduce the problem.

**Comment by brianmay** [comment]
I tried to use the "normal" username/password, but Google continues to ask for a Google account for authentication :-(

**Comment by ckhmer1** [comment]
Try restarting node-red.

**Comment by brianmay** [comment]
I did restart node-red, but this didn't help.

I am guessing this problem only happens on new installs, that don't already have the emails values set. Or maybe if you create a new "SmartHome".

**Comment by ckhmer1** [comment]
I've created a new config, but no problem at all, sorry.

**Comment by ckhmer1** [comment]
Hi,
I'm sorry but I'm not able to reproduce the problem, could I try a patch on the fly?

You should open the file google-smarthome.html and go to line number 345:

`let emails = this.emails || this.credentials.emails;`

and change it to the following row:

`let emails = this.credentials.emails;`

Please, let me know if this fixes the problem.

Thanks
Claudio

**Comment by Caprico85** [comment]
Which version of Node-RED do you have?

It's probably related to the Node-RED version. I can't remember having any problems with Node-RED 1.x. A few days ago I upgraded to Node-RED 2.0. On 2.0.5 I can reproduce the problem. Unfortunately I don't have an old install anymore to test if this also happens on 1.x.

**Comment by ckhmer1** [comment]
Hi,
I have Node-RED 2.0.5 and no problem at all.

**Comment by brianmay** [comment]
I have node-red 1.2.5. Didn't realise this was old, might try to upgrade sometime. But sounds like this isn't the problem here.

**Comment by brianmay** [comment]
Will try the suggested change when I get the chance.

But for reference, I didn't see any JavaScript errors in the console (Firefox), so not entirely convinced that is the problem.

**Comment by ckhmer1** [comment]
the change I've suggested is a server-side change, no matter the JavaScript errors.

**Comment by brianmay** [comment]
@ckhmer1 Made the change. Restarted the server (was this required?). Doesn't seem to have made any difference.

**Comment by brianmay** [comment]
I upgraded to version node-red 1.3.5, and it seems to have fixed the problem. Note I still did have the change suggested by @ckhmer1 active at the time of the upgrade (and first test), but not convinced this made any difference.

**Comment by brianmay** [comment]
Hmmm. Still not linking though. On android device a webbrowser on "Link your devices to Google". Click "Sign in". Says "one moment please" and then redirects back to first page. Can't see any errors logged anywhere. No idea, this might be a different problem, but seems like it might be related.

**Comment by ckhmer1** [comment]
I've send a patch for using the new Google library, it is just one file, you can try to apply it and let me know

**Comment by Caprico85** [comment]
I released v0.1.5 with @ckhmer1's Google library fix (didn't test it though).

I also had a look at the initial problem yesterday evening. I was not able to reproduce it anymore. Editing addresses now works a expected  for me. So I'm currently out of ideas what the reason was. I'm thinking it may have been some browser cache issue only. The "styled" email address field was introduced not long ago. It was a simple text field before. Maybe the browser still had some old stuff in the cache.

> Hmmm. Still not linking though. On android device a webbrowser on "Link your devices to Google". Click "Sign in". Says "one moment please" and then redirects back to first page. Can't see any errors logged anywhere. No idea, this might be a different problem, but seems like it might be related.

This can have different reasons. Wrong configuration, devices not responding correctly and others. This also seems to happen if you try to link without any devices. To rule that out, add at least one single device (doesn't need any special configuration or connections, just use a light or something simple). If that doesn't help, you may need to have a look at Node-RED's debug panel or log file.

**Comment by brianmay** [comment]
OK, I upgraded to v0.1.5, first auth attempt failed, then it worked. Huh? I wasn't expecting that.

But regardless I think we can close this now. Maybe reconsider if somebody else reports the same problem.

**Comment by ckhmer1** [comment]
Thanks for Your feedback.

**Comment by dr-boss** [comment]
Same problem, Authorized emails list is cleared. after every deploy. With user/pass login Synchronization work only from google device to node-red. But any change of device from node red is not send to google
version 0.1.6
