### ISSUE TITLE
messages don't get sent from node

### ISSUE THREAD

**Issue by brianmay** [mikejac/node-red-contrib-google-smarthome#174]
I have this truly bizarre issue that after about the 2nd deploy, the messages from the "Color (HSV) Light" are not getting dispatched on updates.

As in, I change the state of the light in Google. I see the state of the node has correctly changed. But nodes that are connected to the output do not see the message.

I do not see any errors or anything to explain this behaviour.

If I restart node-red, it comes good for a while. Until about the 2nd deploy, when it fails again in exactly the same way.

Only the  "Color (HSV) Light" node is affected - but haven't tried other nodes from this package yet. Will try now.

**Comment by brianmay** [comment]
Seems to happen with other node types.

**Comment by ckhmer1** [comment]
This should happens if You move the position of the nodes after the deploy. Restarting Node-RED should fix it. Have You specified the room in every node?

**Comment by brianmay** [comment]
No. All nodes are unspecified room, and I have not changed this either in node-red or in google.

Like I said, restarting it does fix the problem. But seems like I have to restart node-red to fix this for every single deploy.

**Comment by ckhmer1** [comment]
Not really every single deploy, sometimes if You change the Google nodes.

**Comment by Caprico85** [comment]
Can you open https://example.com:3001/check in a browser after message forwarding fails? Preferably from an external testing tool like https://reqbin.com/. It should respond with a "SUCCESS" message. This shows if there are connectivity issues (e.g. Node-RED killing and not restarting the webserver for the smarthome service).

Did you have a look at Node-RED's log output? `docker logs nodered`, `systemctl status node-red` or somewhere else, depending on how Node-RED is configured and started. Maybe there are already some error messages.

If this doesn't help, you can try increasing Node-RED's log level. Open Node-RED's settings.js, search for "level" (somewhere inside "logging" section), set it to "debug" and restart Node-RED. Then look at Node-RED's log output again. You should now see *lots of* debug messages.

For every command via voice or app there should be messages like

```
2021-08-16T18:26:41.796640535Z HttpActions:httpActionsRegister(/smarthome): request.headers = {"host":"example.com:3001","user-agent":"Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.google.com/bot.html)","content-length":"305","accept-e
ncoding":"gzip, deflate, br","authorization":"Bearer XXXXXXXXXXXXXXXXXX","content-type":"application/json;charset=UTF-8","google-assistant-api-version":"v1","x-forwarded-for":"66.249.81.228","x-forwarded-host":"example.com:3001"
,"x-forwarded-port":"3001","x-forwarded-proto":"https","x-forwarded-server":"traefik","x-real-ip":"66.249.81.228"}
2021-08-16T18:26:41.796806940Z HttpActions:httpActionsRegister(/smarthome): request.headers.authorization = Bearer XXXXXXXXXXXXXXXXXX
2021-08-16T18:26:41.796842043Z HttpActions:httpActionsRegister(/smarthome): reqdata = {"inputs":[{"context":{"locale_country":"DE","locale_language":"de"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"id":"cb782baf.ebdc98"},{"id":"aec7a9bb.661578"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":true}}]}]}}],"requestId":"20031780998829719"}
2021-08-16T18:26:41.797757297Z HttpActions:httpActionsRegister(/smarthome): user: xxx
2021-08-16T18:26:41.797883859Z HttpActions:httpActionsRegister(/smarthome): EXECUTE
2021-08-16T18:26:41.799153328Z HttpActions:_exec()
2021-08-16T18:26:41.800662744Z HttpActions:_execDevice(): command = {"command":"action.devices.commands.OnOff","params":{"on":true}}
2021-08-16T18:26:41.803015487Z Device:execCommand(): device = {"id":"cb782baf.ebdc98","states":{},"command":"action.devices.commands.OnOff"}
2021-08-16T18:26:41.803163767Z Device:execCommand(): device has no execCommand
```

These are the requests Google sends to our service. Do these messages still appear after Node-RED fails to forward messages?

Are there any error messages?

**Comment by brianmay** [comment]
Like I said earlier, the state of the device changes (text under icon in red-node), so I think these means it is talking to Google just fine.

check URL returns SUCCESS, including when accessed remotely.

It fails every time I click deploy. And I haven't made any changes to the Google nodes or any config in Google.

red-node logs look fine to me.

```
[...]
HttpActions:httpActionsRegister(/smarthome): EXECUTE
HttpActions:_exec()
HttpActions:_execDevice(): command = {"command":"action.devices.commands.OnOff","params":{"on":false}}
Device:execCommand(): device = {"id":"8d628b30.95206","states":{},"command":"action.devices.commands.OnOff"}
Device:execCommand(): device has no execCommand
Device:execDevice(): this._devices[device.id] = {"states":{"online":true,"on":false},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"},"id":"8d628b30.95206"},"executionStates":[],"command":"action.devices.commands.OnOff"}
Device:getStatus(): deviceIds = ["8d628b30.95206"]
Device:getStatus(): devices = {"8d628b30.95206":{"states":{"online":true,"on":false},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"},"id":"8d628b30.95206"},"executionStates":[],"command":"action.devices.commands.OnOff"}}
HttpActions:_execDevice(): execDevice = {"8d628b30.95206":{"states":{"online":true,"on":false},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"},"id":"8d628b30.95206"},"executionStates":[],"command":"action.devices.commands.OnOff"}}
HttpActions:_exec(): executionResponse = {"status":"SUCCESS","states":{"online":true,"on":false},"executionStates":[]}
HttpActions:_exec(): resBody = {"requestId":"2710474850022549678","payload":{"commands":[{"ids":["8d628b30.95206"],"status":"SUCCESS","states":{}}]}}
Device:getStates(): deviceIds = ["8d628b30.95206"]
Device:getStates(with-deviceIds): deviceId = "8d628b30.95206"
Device:getStates(with-deviceIds): states[deviceId] = {"online":true,"on":false}
HttpActions:reportState(): deviceId = 8d628b30.95206
HttpActions:reportState(): states = {"online":true,"on":false}
HttpActions:reportState(): notifications = undefined
HttpActions:reportState(): postData = {"requestId":"1gGDfZMMwqKtXxNOTEmWm0","agentUserId":"0","payload":{"devices":{"states":{"8d628b30.95206":{"online":true,"on":false}}}}}
HttpActions:reportState(): success
```

Not sure about the "notifications = undefined" if that is normal or not.

**Comment by ckhmer1** [comment]
"notifications = undefined" is normal because You are not sending a notification but a State Report.

**Comment by brianmay** [comment]
Pity. I was hoping I had found the smoking gun, so to speak.

Might try to upgrade node-red. This is starting to appear like it might be some sort of node-red issue.

**Comment by brianmay** [comment]
Nope. Same problem with 2.0.5.

After restarting node-red, I see this scary looking message, but as far as I can tell it is all working at this stage despite this message:

```
{"msg":"Error in HttpActions:requestSync()","org_msg":{"code":500,"message":"Internal error encountered.","errors":[{"message":"Internal error encountered.","domain":"global","reason":"backendError"}],"status":"INTERNAL"},"data":{"postData":{"agentUserId":"0"}}}
```

**Comment by brianmay** [comment]
In google's logs I see the following error, repeated every now and again. Might be normal, not sure:

```
{
  "insertId": "1xdiidogakxr45c",
  "jsonPayload": {
    "syncLog": {
      "syncs": [
        {
          "status": "BACKEND_FAILURE",
          "requestId": "7748122312763370944",
          "httpLatencyMsec": "802"
        }
      ]
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "robotica-9ea70"
    }
  },
  "timestamp": "2021-08-20T01:22:55.456749449Z",
  "severity": "ERROR",
  "logName": "projects/robotica-9ea70/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-08-20T01:22:55.456749449Z"
}
```

**Comment by ckhmer1** [comment]
Could You please post the complete "postData" field, if it doesn't contain any sensitive data?

**Comment by brianmay** [comment]
@ckhmer1 Not 100% sure what you are referring to here.

I didn't truncate or delete any of the above data, except for the "request.headers" stuff, which looks like it is full of private authentication stuff.

So where I quoted the logs saying:

```
"data":{"postData":{"agentUserId":"0"}}}
```

That is exactly what the logs say.

Does this help?

**Comment by ckhmer1** [comment]
Hi,
I'm sorry, I didn't realize that it was complete.
The message seems an empty message, I've already seen it in my log, I don't know yet why sometimes it is sent. Anyway all the nodes should work correctly.
Thanks for reporting.

**Comment by brianmay** [comment]
I did a diff of the logs between a "bad" run and a "good" run. Basically the same, but the "bad" run has an extra "id" field on two lines. Weird.

```diff
--- bad_on	2021-08-23 08:31:46.897187677 +1000
+++ good_on	2021-08-23 08:14:45.213118287 +1000
@@ -1,23 +1,23 @@
-HttpActions:httpActionsRegister(/smarthome): request.headers = [...]
+HttpActions:httpActionsRegister(/smarthome): request.headers = [...]
 HttpActions:httpActionsRegister(/smarthome): request.headers.authorization = [...]
-HttpActions:httpActionsRegister(/smarthome): reqdata = {"inputs":[{"context":{"locale_country":"US","locale_language":"en"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"id":"8d628b30.95206"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":true}}]}]}}],"requestId":"7370835826328966099"}
+HttpActions:httpActionsRegister(/smarthome): reqdata = {"inputs":[{"context":{"locale_country":"US","locale_language":"en"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"id":"8d628b30.95206"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":true}}]}]}}],"requestId":"14512925059780297909"}
 HttpActions:httpActionsRegister(/smarthome): user: brian@linuxpenguins.xyz
 HttpActions:httpActionsRegister(/smarthome): EXECUTE
 HttpActions:_exec()
 HttpActions:_execDevice(): command = {"command":"action.devices.commands.OnOff","params":{"on":true}}
 Device:execCommand(): device = {"id":"8d628b30.95206","states":{},"command":"action.devices.commands.OnOff"}
 Device:execCommand(): device has no execCommand
-Device:execDevice(): this._devices[device.id] = {"states":{"online":true,"on":true},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"},"id":"8d628b30.95206"},"executionStates":[],"command":"action.devices.commands.OnOff"}
+Device:execDevice(): this._devices[device.id] = {"states":{"online":true,"on":true},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"}},"executionStates":[],"command":"action.devices.commands.OnOff"}
 Device:getStatus(): deviceIds = ["8d628b30.95206"]
-Device:getStatus(): devices = {"8d628b30.95206":{"states":{"online":true,"on":true},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"},"id":"8d628b30.95206"},"executionStates":[],"command":"action.devices.commands.OnOff"}}
-HttpActions:_execDevice(): execDevice = {"8d628b30.95206":{"states":{"online":true,"on":true},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"},"id":"8d628b30.95206"},"executionStates":[],"command":"action.devices.commands.OnOff"}}
+Device:getStatus(): devices = {"8d628b30.95206":{"states":{"online":true,"on":true},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"}},"executionStates":[],"command":"action.devices.commands.OnOff"}}
+HttpActions:_execDevice(): execDevice = {"8d628b30.95206":{"states":{"online":true,"on":true},"properties":{"type":"action.devices.types.SWITCH","traits":["action.devices.traits.OnOff"],"name":{"defaultNames":["Node-RED Switch"],"name":"switch"},"roomHint":"","willReportState":true,"attributes":{},"deviceInfo":{"manufacturer":"Node-RED","model":"nr-switch-v1","swVersion":"1.0","hwVersion":"1.0"}},"executionStates":[],"command":"action.devices.commands.OnOff"}}
 HttpActions:_exec(): executionResponse = {"status":"SUCCESS","states":{"online":true,"on":true},"executionStates":[]}
-HttpActions:_exec(): resBody = {"requestId":"7370835826328966099","payload":{"commands":[{"ids":["8d628b30.95206"],"status":"SUCCESS","states":{}}]}}
+HttpActions:_exec(): resBody = {"requestId":"14512925059780297909","payload":{"commands":[{"ids":["8d628b30.95206"],"status":"SUCCESS","states":{}}]}}
 Device:getStates(): deviceIds = ["8d628b30.95206"]
 Device:getStates(with-deviceIds): deviceId = "8d628b30.95206"
 Device:getStates(with-deviceIds): states[deviceId] = {"online":true,"on":true}
 HttpActions:reportState(): deviceId = 8d628b30.95206
 HttpActions:reportState(): states = {"online":true,"on":true}
 HttpActions:reportState(): notifications = undefined
-HttpActions:reportState(): postData = {"requestId":"5Wn9oFRbcgH2MlKZtTRjJo","agentUserId":"0","payload":{"devices":{"states":{"8d628b30.95206":{"online":true,"on":true}}}}}
+HttpActions:reportState(): postData = {"requestId":"6iAJmSxo7CLp5uibWKldkJ","agentUserId":"0","payload":{"devices":{"states":{"8d628b30.95206":{"online":true,"on":true}}}}}
 HttpActions:reportState(): success
```

Looking at the code, looks like there are some debug messages which aren't getting displayed. Will try to change the node-red log level from "info" to debug".

**Comment by brianmay** [comment]
With "debug" on I just see another line with:

```
23 Aug 08:42:20 - [debug] SwitchNode(updated): states = {"online":true,"on":xxx}
```

Which is consistent for both bad and good runs. xxx is the expected value - true for turning on, off for turning off. Everything else is the same.

This does confirm though that we are running this function:

https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/devices/switch.js#L106

But what is weird is that the last line doesn't seem to be working.

```
this.send(msg);
```

**Comment by brianmay** [comment]
I put this line above the troublesome send line:

```
RED.log.debug("SwitchNode(updated): msg = " + JSON.stringify(msg));
this.send(msg);
```

Now I see the message that is suppose to get sent:

```
23 Aug 08:56:46 - [debug] SwitchNode(updated): states = {"online":true,"on":false}
23 Aug 08:56:46 - [debug] SwitchNode(updated): msg = {"topic":"switch","device_name":"switch","command":"action.devices.commands.OnOff","payload":{"online":true,"on":false}}
```

But this doesn't happen after the redeploy :-(

**Comment by brianmay** [comment]
Sorry, realised I was potentially ambiguous in that last statement.

What I mean is while the message appears in the logs, the message is never sent. So a debug node on the output doesn't print anything.

This only happens after a deploy. After a restart, but before a deploy it works perfectly.

**Comment by brianmay** [comment]
No help, but looks like somebody else had similar issues. https://discourse.nodered.org/t/message-not-being-sent-after-deploy/26128

**Comment by brianmay** [comment]
Hmmm. I added code to print the `this.states` value at the end of the `updated` function. I also added code to print the `this.states` value at the stop of the `onInput` function.

Then I do the following:
1. Toggle light on. The `updated` function reports state is `{"online":true,"on":true}`. The icon changes to on.
2. Toggle light off. The `updated` function reports state is `{"online":true,"on":false}`. The icon changes to off.
3. Send the node a message with `topic = "ON"` and `payload.on = true`. The `onInput` function reports that the state is `{"online":true,"on":true}`, and does nothing. Which makes no sense, I just observed the state changing.

My current theory is something weird is happening on deploy, and we end up with duplicate javascript objects. The `updated` method gets called with the old object, and the `onInput` object gets called with the new object. Causing lots of confusion.

**Comment by brianmay** [comment]
I have a theory... If I am wrong, please say so :-)

On every deploy, we-register the http server hooks, for me this happens here:

https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/lib/SmartHome.js#L161-L165

The old hooks still exist. And we don't overwrite the old hooks. So the old hooks remain in use. But the old hooks refer to the old GoogleSmartHome object that refers to the old device objects that have been replaced with new device objects, so this isn't going to work.

Trying to confirm this behaviour. But I can't see any way to list the http server hooks. I cannot even find any documentation on how the http server hooks work.

I have seen that the device object is different in the "check" http hook from the "updated" function, on repeated calls. Which probably should not happen.

Of course, it is possible that the objects are being duplicated somewhere. I don't see it, but that doesn't mean it isn't happening.

If this was correct, I don't see how this would be working for anybody :-(.

**Comment by ckhmer1** [comment]
Hi,
I'm sorry for the late response and for the big analysis.
Have You tried to set the HTTP Port in order to use a different webserver?
I with the HTTP port all is working, perhaps You are right.

**Comment by jpoeppelman1** [comment]
I have the same issue.  The state of the node changes, but no messages leaves the output.  Show stopper...  Clearly this is a bug, can  we get this fixed?  I'm also running the server on the same port as node red, similar situation where I already have things working with SSL.  Does it have to be on a separate port? Why provide the option to host on the same port as NR if it doesn't work?

**Comment by brianmay** [comment]
@jpoeppelman1 My guess is that this is a bug when using the same http server. Not tested yet but would be good to confirm. If this affected everybody, I think more people would be jumping up and down and screaming, etc. This is the most likely reason why most people are not affected.

My guess is that this would be easy to fix. If you knew enough about the node-red libraries. Which unfortunately I do not. Nor can I find much in the way of good documentation.

I believe the problem is that the webserver is being called to act on the old objects, not the new objects which were replaced on server deploy, and as a result this is also preventing messages from being dispatched.

This might be because when we de a deploy, we don't reload the server, and the server retains the old hooks, and attempting to add hooks that already exist fails.

**Comment by ckhmer1** [comment]
I use the google node-red plugin daily and I haven't all these problems.
Usually, I use the deploy option "Modified nodes", as the following

![image](https://user-images.githubusercontent.com/2863760/133921984-2e682b54-6d67-4b9e-86ac-e58ce6b0841e.png)

Could You please specify exactly the steps to reproduce the problem?

Thanks

**Comment by jpoeppelman1** [comment]
> @jpoeppelman1 My guess is that this is a bug when using the same http server. Not tested yet but would be good to confirm. If this affected everybody, I think more people would be jumping up and down and screaming, etc. This is the most likely reason why most people are not affected.
> 
> My guess is that this would be easy to fix. If you knew enough about the node-red libraries. Which unfortunately I do not. Nor can I find much in the way of good documentation.
> 
> I believe the problem is that the webserver is being called to act on the old objects, not the new objects which were replaced on server deploy, and as a result this is also preventing messages from being dispatched.
> 
> This might be because when we de a deploy, we don't reload the server, and the server retains the old hooks, and attempting to add hooks that already exist fails.

UPDATE - I updated my config to use a different server port, it's working fine now.  Thanks!

**Comment by ckhmer1** [comment]
I've sent a fix for it, I hope it is ok.

**Comment by brianmay** [comment]
> I've also found a way to unregister the Node-RED HTTP endpoints, I hope this fixed issue #174 .

Looking at the PR, I have no idea how you did it, but this sounds like you managed to implement the solution I was looking for.

Thanks!

**Comment by ckhmer1** [comment]
Is this working?

**Comment by brianmay** [comment]
Not tested yet. Not even sure how to install code from a git master into a node-red install.

Hopefully will get time this weekend to try and test this properly.

Thanks for your work!

**Comment by Paul-Reed** [comment]
It has now been published as v1.0.8...
So just update the node in node-RED, but be aware of https://github.com/mikejac/node-red-contrib-google-smarthome/pull/182#issuecomment-925378105

**Comment by brianmay** [comment]
@ckhmer1 Nope, doesn't seem to help.

I see the warning that was [reported](https://github.com/mikejac/node-red-contrib-google-smarthome/pull/182#issuecomment-925378105) so this I think confirms I am on the latest code, but after deploy it stops working still :disappointed:

**Comment by brianmay** [comment]
A bit more confusing now. I played around with sending "restart_server" to the management mode, and it seemed to help restore functionality. Sometimes I need to send the restart single twice.

Now it works after I do a redeploy. I don't have to do the "restart_server" thing.

If I restart node-red, and then do a redeploy, I get the same problem back again however.

**Comment by brianmay** [comment]
It looks like after restarting node-red, I have to:

1. Redeploy.
2. Send "restart_server"
3. Send "restart_server"
4. Redeploy,
5. 2. Send "restart_server"
3. Send "restart_server"

And at that point for future deploys, it will work. Weird. At least I do have a work around now, not sure how much I trust this though.

**Comment by ckhmer1** [comment]
I've changed the code in my last PR., resolving the problem (I hope)

**Comment by ckhmer1** [comment]
I've detected that not always the Stop function gets called.
I've sent a new PR to overcome this behavior.
I hope now it is ok.

**Comment by brianmay** [comment]
Testing PR #185 now. So far looks pretty good. The redeploy problem is fixed.

Fingers crossed https://github.com/mikejac/node-red-contrib-google-smarthome/pull/182#issuecomment-925508535 is also fixed, too early to tell for sure yet.

**Comment by ckhmer1** [comment]
Hi, 
How is it going on?

**Comment by brianmay** [comment]
@ckhmer1 The issues presented here in this bug report look all good after the PR is applied, Thanks.

**Comment by brianmay** [comment]
Still good, closing.

**Comment by naresh97** [comment]
This could be indicative of external connectivity issues as well. For me, this was a firewall resetting after a reboot, blocking the port.
