### ISSUE TITLE
Problem with two way sync

### ISSUE THREAD

**Issue by dr-boss** [mikejac/node-red-contrib-google-smarthome#179]
If I change status of device (ex. light switch) from my phone, all work fine. Node-red receive commands and change state of node.
8.08.2021, 15:08:45
node: c4c1b480.3e6c48
googleBMS : msg : Object
object
topic: "googleBMS"
device_name: "BMS TEST"
command: "action.devices.commands.OnOff"
payload: object
online: true
on: false
_msgid: "d55a016e.b1ea2"

But if I change state (ex back to off) from nodered the device in google assist is not synchronized and I receive this message on nodered:

28.08.2021, 15:18:07
node: GoogleBMS
msg : string[42]
"HttpActions:reportState(): no user logged!"

28.08.2021, 15:18:07
node: c4c1b480.3e6c48
on : msg : Object
object
_msgid: "beb2f30b.18e91"
payload: false
topic: "on"

Aug 28 15:18:07 pi4 Node-RED[8472]: 
HttpActions:reportState(): postData = {"requestId":"5eIKpclNX8AgUs6NLk7Twn","agentUserId":"0","payload":{"devices":{"states":{"301a7a2.96b4d06":{"online":true,"on":false}}}}}

I checked all data (user/pass/secret etc in node config, all is ok.
Can you help me

**Comment by dr-boss** [comment]
another error when sync process start:
"HttpActions:reportState(): http server is not running"
 

For info, the https://dns:3001/check return SUCCESS

**Comment by ckhmer1** [comment]
Is this problem still present? If so, could you please include the Node-RED log?

**Comment by Caprico85** [comment]
Closing this now. Feel free to reopen if necessary.
