### ISSUE TITLE
Boiler Device - Temperature Control not working

### ISSUE THREAD

**Issue by jpoeppelman1** [mikejac/node-red-contrib-google-smarthome#184]
When I add a boiler device with temperature control it fails.  Google home responds with "Actually the Boiler does not support this functionality."  I confirmed the device settings with temp control trait enabled.  Is it a bug?

**Comment by ckhmer1** [comment]
Hi,
I'm sorry for that, I've sent a fix for it.
Claudio

**Comment by jpoeppelman1** [comment]
Thanks for helping fix this.    I checked the change log and don't see this available yet.  When can we get the new build via NR module?

**Comment by ckhmer1** [comment]
I've sent a PR to the project owner
As soon as the project owner will accept it and deliver the update to npm, it will be available to all.

**Comment by jpoeppelman1** [comment]
Is there a way to track this? Thanks again.

**Comment by ckhmer1** [comment]
I don't know, usually, @Caprico85 accepts them.

**Comment by Caprico85** [comment]
v0.1,8 was releaed including Claudio's fixes.

**Comment by jpoeppelman1** [comment]
Thanks guys, but when I open up NR module pallete to upgrade the module it still shows 0.1.7 with no available upgrade button.  Was this pushed to NR repository?
