### ISSUE TITLE
Color (HSV) light white color not white

### ISSUE THREAD

**Issue by brianmay** [mikejac/node-red-contrib-google-smarthome#186]
If I tell Google to set a "Color (HSV) light" to "white", I get a non-white colour.

The exact values are:

```
{"online":true,"on":true,"hue":35.85365676879883,"saturation":32.156863808631904,"value":100,"name":"white","brightness":100}
```

"value" is set to 100%, I believe it should be set to 0% for white.

Possibly this bug is inside Google, and can't be fixed in this project, not sure really where the responsibilities lie.

Side note: What was confusing me also, is that this HSV color model is different from the similar hue-saturation-brightness model LIFX lights expect (white is when saturation is set to 0% and there is no 'value' component).

**Comment by brianmay** [comment]
Thinking about this, is possible that the colour is being altered to support some sort of colour temperature. But am a bit doubtful, I don't think colour temperature is supported with this node (at least that is what google assistant tells me when I try to set the temperature). And the values seem a bit extreme.

**Comment by ckhmer1** [comment]
Hi,
I can control the color and temperature of the light, I have the following payload in output when asking google to change the color:

**White light:**

```{"topic":"luce/garage","device_name":"Luce Garage","command":"ColorAbsolute","params":{"color":{"name":"bianco","temperature":5000}},"payload":{"online":true,"color":{"temperatureK":5000},"on":true},"_msgid":"50e357e8c9083c8d"}```

**Red light**

```{"topic":"luce/garage","device_name":"Luce Garage","command":"ColorAbsolute","params":{"color":{"name":"rosso","spectrumHSV":{"hue":0,"saturation":1,"value":1}}},"payload":{"online":true,"color":{"spectrumHsv":{"hue":0,"saturation":1,"value":1}},"on":true},"_msgid":"80368022d8111fa9"}```


**Warm white**

```{"topic":"luce/garage","device_name":"Luce Garage","command":"ColorAbsolute","params":{"color":{"name":"bianco caldo","temperature":3000}},"payload":{"online":true,"color":{"temperatureK":3000},"on":true},"_msgid":"c60390f5d6c73686"}```


**Blu light**

```
{"topic":"luce/garage","device_name":"Luce Garage","command":"ColorAbsolute","params":{"color":{"name":"blu","spectrumHSV":{"hue":240,"saturation":1,"value":1}}},"payload":{"online":true,"color":{"spectrumHsv":{"hue":240,"saturation":1,"value":1}},"on":true},"_msgid":"8d0b4e331e76425a"}
```

Could You please include the logs?

Thanks

**Comment by brianmay** [comment]
One point of possible confusion, this was with the "Color (HSV) light" node. I think you might be using the "Light node" with the "Color (HSV) light" type. Which has not worked properly with me (#187) yet (will test that again ASAP).

Just to confirm, are you saying when I select a white colour, I should not be seeing any of the hue, saturation, value values? In my tests, I don't see these values unless I pick a colour, e.g. red, and then they always appear even if I select white.

**Comment by ckhmer1** [comment]
I used the Google device node with type light

**Comment by Caprico85** [comment]
I didn't have the chance to try this out myself (my RasPi is dead currently). Just some ideas from me:
- We don't change the values sent by Google. So if the color is wrong, it is already sent by Google like that. I don't think we should recalculate colors on our side to make white more white (and probably mess up other colors during this recalculation).
- Maybe in Google words, "white" simply means the color you get. I read [here](https://www.reddit.com/r/googlehome/comments/5h3id7/can_google_home_turn_your_lights_white/daxlumy/) there are also colors like "Bright White". Maybe there are other color names that get even closer to white.
- It may be related to color temperatures. We report a min and max color temperature to Google. Maybe Google recalculates colors to be "as white as it can get with this color temperature". For lights implemented with the "Google Device" node and "Color setting" trait, the color temp range can be set in the UI. For all other lights, color temp ranges can only be changed in source code (file devices/light.js, search for "temperatureMaxK"). Does setting another max color temp changes the color?

**Comment by Caprico85** [comment]
Resurrected my RPi and tried it.

"White" gets me the same yellowish color as you have. "Bright white"gets me real white. RGB lights have the same problem. "White" is #FFDEAD, "Bright white" is #FFFFFF.

I guess it's something we have to live with. Thats how the colors are called in Google's color table. We have no way to change that table.

Only "fix" is using a function node which converts the wrong white, but keeps other colors unchanged.

**Comment by brianmay** [comment]
OK, thanks for your investigation. Will put it down to Google weirdness.
