### ISSUE TITLE
access by multiple google accounts

### ISSUE THREAD

**Issue by brianmay** [mikejac/node-red-contrib-google-smarthome#193]
Hello,

Just wondering if it is possible for multiple people using different google accounts to access these devices?

Current attempt looks like:

* Oauth app is registered as test app.
* Other user is listed as authorised user for test app. In both the Google Oauth screen and the node-red management node screen.
* Devices do not appear for other user.
* Trying to add devices: Test app doesn't appear for other user.
* Possibly publishing app might help (?) but ideally I want to restrict who can see an app that controls devices in my home.

Maybe this is a limitation of the Google IOT model. But curious if there is something I missed.

Regards

**Comment by brianmay** [comment]
Found this:

https://developers.google.com/assistant/smarthome/develop/testing#share-action

Instructions are not exactly correct, but seem to indicate I need to add the user to the IAM settings in the project as role "viewer". Will test.

**Comment by brianmay** [comment]
Nope, not that simple. Still can't see the project in Google Home.

**Comment by brianmay** [comment]
Turns out user had multiple Google accounts, and using wrong one. Not sure now which of these steps was required, but is working for them now.

**Comment by ckhmer1** [comment]
Hi,
Thanks for reporting.
So, at the end were working, right?
Could you please try to describe the steps, I'd like to add in the docs.

**Comment by Caprico85** [comment]
I also had it running with two accounts a while ago. From what I remember, the process was basically as follows:

1. In the config of your management node switch to "Use Google Login".
1. If you haven't used "Use Google Login" before, follow the steps in [Integrating Google Sign-In](https://github.com/mikejac/node-red-contrib-google-smarthome/#integrating-google-sign-in). It's recommended to get you own account working again before adding a second account.
1. In "Authorized emails" add the email address of the second account. Save and deploy.
1. Open your project in Google Actions Console.
1. From the menu (three dots on the upper right) choose "Manage user access".
1. Select "Add" (**is it called like this in English?**)
1. Enter the E-Mail-Adress for the Account you want to add. As role select at least "Viewer" (*is it called like this in English?*)
1. The added account should now be able to see the project in his own Google Actions Console. You don't need to change anything here.
1. The added account should can now also link your account in the Google Home App by following the steps in [Setup Account linking](https://github.com/mikejac/node-red-contrib-google-smarthome/#setup-account-linking).

But I also needed several tries. So there could be some minor but important steps missing here.

**Comment by brianmay** [comment]
If using oauth test mode on Google, will need to add the email addresses to the allowed users there, I think.

Also I did this [enable testing](https://developers.google.com/assistant/smarthome/develop/testing#enable-shared-testing) although I would like to think this step wasn't required. But not sure.

**Comment by ckhmer1** [comment]
Thanks

**Comment by ckhmer1** [comment]
Thanks

**Comment by Caprico85** [comment]
Thanks. You're right. Resetting/enabling testing may help. Added that to my list.

> If using oauth test mode on Google, will need to add the email addresses to the allowed users there, I think.

There's an oauth test mode? Interesting. I never used that.

**Comment by brianmay** [comment]
Not sure, but I noticed it is possible to share the Google Home with other people. My guess is that this might allow skipping the above procedure.

**Comment by Caprico85** [comment]
Thank you. You are right. You can "invite" other people in the app. Never really thought of that.

I'll add this to the Readme. I'll keep the other instructions too, as inviting does not work in all cases (for example for Google Workspace accounts like I have).

**Comment by Caprico85** [comment]
Added a note on "inviting" to the Readme.

**Comment by jvanderzande** [comment]
> Thank you. You are right. You can "invite" other people in the app. Never really thought of that.
> 
> I'll add this to the Readme. I'll keep the other instructions too, as inviting does not work in all cases (for example for Google Workspace accounts like I have).

I have a number of devices and Scenes setup in Node-red and they all work for me in the Home app, but in my partner's Home app only the devices are shown and the scenes are not there to activate or add to a routine. 

Thanks :)

**Comment by jvanderzande** [comment]
After a lot Searching & Trials I figured out one have to set the "Room hint" to one of the valid rooms for the house or else the Scene is only available to the owner of the Home, but not the invited person(s). 
Jos

**Comment by brianmay** [comment]
I believe that if a device is not assigned to a room, then it isn't assigned as part of that house, and sharing a house will not share unassigned devices.
