### ISSUE TITLE
Cannot GET /smarthome - All others working.

### ISSUE THREAD

**Issue by BloodBlight** [mikejac/node-red-contrib-google-smarthome#197]
/check returns:
`SUCCESS`

/oauth returns:
`response_type undefined must equal "code"`

/token returns:
`invalid client id or secret`

When I try to add the link in google home, get this error:
https://imgur.com/a/kaWvQQ0

I see the auth attempt in the logs:
`GET /oauth?response_type=code&client_id=red-google&redirect_uri=https://oauth-redirect.googleusercontent.com/......... 200 42.766 ms - 7532`

I see it bounce off of my server, and have confirmed my URL, cert all work correctly using my cell phone...

I have a single flow with a single management tile.  I have tried restarting docker (had to for the cert anyway).

Not really sure were to go from here.

**Comment by BloodBlight** [comment]
My node configuration:
https://imgur.com/a/ZicyDYq

**Comment by BloodBlight** [comment]
Weird, ya link still works here... Lots of weird hiccups from sites today though...

**Comment by Caprico85** [comment]
Not being able to GET /smarthome is expected. /smarthome only responds to POST requests. If you send a POST request to https://example.com:3001/smarthome using reqbin.com, curl or some other service it should respond. It will respond with error 401 (unauthorized) as you are not sending auth headers, but at least it should respond.

Now to redirect_uri_mismatch:

When exactly does this happen? Do you see the first login page with the Sign In button?

![image](https://user-images.githubusercontent.com/2081806/136654974-3c84ac95-33b7-4696-8133-dd77d0ceabdb.png)

If you click the button, do you get the page where you select the Google account to use?

What log messages do you get? Only the `GET /oauth?...` line? Or is there a `POST /oauth` line after that GET line too?

**Comment by BloodBlight** [comment]
Sorry, yes I do get that screen (from my server), the auth error comes up after clicking signin.

![tmp](https://user-images.githubusercontent.com/3953102/136663278-fd288958-0138-4a80-885e-f0008759f773.jpg)
![](https://i.imgur.com/f4lQsK3.jpg)

The long only shows two events (tried several times and repeated the pattern):
```
HttpAuth:httpAuthRegister(GET /oauth)
GET /oauth?response_type=code&client_id=red-google&redirect_uri=https://oauth-redirect.googleusercontent.com/r/....&....... 200 5.131 ms - 7532
```

I don't see google attempting to connect.  Tripled checked the behavior using LTE.

I also triple checked the URLs in the account linking section.

**Comment by ckhmer1** [comment]
It seems that You have problems with the following step (from the [Integrating Google Sign-In](https://github.com/mikejac/node-red-contrib-google-smarthome#integrating-google-sign-in))

Register the origins from which your app is allowed to access the Google APIs, as follows.

**Comment by BloodBlight** [comment]
Hmm, if I do a curl, I get a cert error:
```
$curl -X POST https://###############:####/smarthome
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

But in the screenshot above it works fine..  Tried in Chrome, Brave & Firefox, all happy...


Ignoring the cert errors I get:
```
$ curl --insecure -I -X POST https://###############:####/smarthome
HTTP/1.1 401 Unauthorized
Content-Security-Policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
X-DNS-Prefetch-Control: off
Expect-CT: max-age=0
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
X-XSS-Protection: 0
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Authorization
Content-Type: application/json; charset=utf-8
Content-Length: 26
ETag: #################
Date: Sat, 09 Oct 2021 15:07:07 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

Further checking out the cert error...

**Comment by BloodBlight** [comment]
> It seems that You have problems with the following step (from the [Integrating Google Sign-In](https://github.com/mikejac/node-red-contrib-google-smarthome#integrating-google-sign-in))

I will go over this again.  It looks like the instructions might be out of date.
There is no consent screen under credentials.  There is an "OAuth consent screen" options next to the credentials section.

![image](https://user-images.githubusercontent.com/3953102/136664140-79d39551-8689-4bda-9cd8-bd1441caf26c.png)
![image](https://user-images.githubusercontent.com/3953102/136664195-393af91d-22b0-49df-93cd-3645b8142df2.png)

**Comment by BloodBlight** [comment]
Alright, I fixed that, but appear to have broken something else.
![image](https://user-images.githubusercontent.com/3953102/136666565-ca95cc9b-6875-442b-b64f-ce5b9a541a3d.png)

Nothing else in the logs, the service account and everything else I can find appears to be enabled...
