### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by jaseuk73** [mikejac/node-red-contrib-google-smarthome#2]
Hi @mikejac .

I have been looking for something like this for a while and your work so far is really good, thank you.

I have possibly one question and one issue. Your instructions are very methodical and nicely laid out.
The question I have is on the 'Add Request Sync' section you mention pasting the API key into 'smart-home-provider/cloud/config-provider.js'. I cannot seem to find any reference to this in your code or node red. I would be very grateful if you could point me in the right direction.
The Issue I may have is when going into the Google Home [test] app I get the 'NODE-RED SmartHome Welcome' screen with a Link your devices to Google page and the Login button shows up. but nowhere to put in credentials. If I press the Login button it redirects to a blank grey page, and on Node red debug panel I get _type: login  msg: invalid user.
If you need any specific info please let me know.

Kind regards  @jaseuk73

**Comment by scotie** [comment]
Same issue here. Didn't find where to put the API KEY

**Comment by mikejac** [comment]
Sorry, the API key is not needed by this node. Also, an option to disable SSL has been added in version 0.0.14.

/michael
