### ISSUE TITLE
Sure but first you will have to unlock your device

### ISSUE THREAD

**Issue by brianmay** [mikejac/node-red-contrib-google-smarthome#200]
I have noticed that Google Nest devices are happy to turn on/off lights etc via this plugin.

But if you allow Google Assistant to respond on a locked phone, sometimes it will answer instead. Or in addition to the Google nest device. It will always answer with "Sure but first you will have to unlock your device" which is a bit of a pain.

Sometimes the Google Nest has already made the change when the phone complains. Other times it hasn't.

Wondering if there is anyway of allowing phones to make changes to devices even if the phone is locked? Or do I need to stop google answering when the phone is locked?

**Comment by Caprico85** [comment]
Never had these problems myself. So I am not speaking from experience here. When I say something, both my devices are waking up but only one device responds and one device goes back to sleep. Usually the Nest responds and the phone sleeps. From what i've heard, to do this the devices communicate with each other on which device unterstood you best. So, maybe connectivity issues that prevent communication? Or maybe positioning issues so your phone thinks it's far away from your smart speaker.

I also searched around and found several pages referring to Google Voice Match (e.g. [this](https://www.reddit.com/r/googlehome/comments/d6wzjm/google_is_answering_me_on_multiple_devices/) or [this](https://www.reddit.com/r/GooglePixel/comments/8nhjkq/both_google_home_and_pixel_xl_respond_to_ok_google/)). Google Voice Match creates a voice model of your voice to recognize you later. If your devices aren't connected to the same Google account or use different voice models, they may not recognize your voice and think there are different people talking, so they respond independently.

Voice Match could also explain why your phone is asking for unlocking. Voice Match can unlock the phone by itself if it recognizes your voice. But if your phone doesn't recognize your voice anymore, it may think you are somebody else. To protect your home it may then ask you to unlock your phone as an additional security measure.

So first I would try is setting up Google Voice Match again. This is done in the Google Assistant settings on your phone. Re-train your voice model and check that it is activated on all devices in question.

**Comment by Paul-Reed** [comment]
I would agree with Caprico85.
The usual thing that causes this problem is that one device is using a different Google account.
I currently have a Nest device sat next to my phone, and use voice commands to control lighting, and as Caprico85 describes, both devices wake up when the hear 'Hey Google' but when I issue the command one device deals with it, whilst the other goes back to sleep.

**Comment by brianmay** [comment]
All my devices are on the one Google account.

Will retry training...

**Comment by brianmay** [comment]
Definitely was something wrong with my voice match. Way to test "Ok Google, Who am I?" resulted in the nest saying it didn't recognise me. But curiously it was willing to do actions for me.  Weird. I think I programmed that years ago, not surprising it needed to be redone, and am a bit surprised Google didn't require me to do so. Will see what it is like now.

**Comment by brianmay** [comment]
I still have seen situations where multiple devices will answer, for example on set timer request. And I end up with multiple timers. Even though all devices are on my account, and I retrained my voice.

But I haven't seen this problem requiring unlocking again. So I will close for now until it happens again.

**Comment by brianmay** [comment]
This is happening again on my phone. Any commands to my phone require unlocking it. Including asking "who am I", then it returns my name.

**Comment by Caprico85** [comment]
I'm sorry to hear that. Some more questions to investigate further:

- Do you have devices linked using their own "skills", without using Node-RED or node-red-contrib-google-smarthome? Does it happen for these devices too?
- If you enable debug output, are there any log messages when Google asks you to unlock your phone? I want to find out if Google calls our service and is unhappy with the response or if Google doesn't even try to call our service.
- Any logs in [Google Cloud logs](https://console.cloud.google.com/logs/query)?

**Comment by brianmay** [comment]
I think it is happening for all devices, not just  node-red-contrib-google-smarthome devices.

**Comment by Paul-Reed** [comment]
I don't believe that this is a smarthome issue, it's something that has been raised many times elsewhere, for example see this thread - https://support.google.com/assistant/thread/20839541/ok-google-to-do-that-you-need-to-unlock-your-phone?hl=en

I too have had similar issues when asking my Shellies to switch on/off, which is nothing to do with smarthome.

**Comment by brianmay** [comment]
Thanks for the reference. For some reason I really thought Google supported this.

Best bet might be to disable Google assistant from responding from the looked screen, so my nest will always respond.
