### ISSUE TITLE
remove requirement for "Out Topic" on nodes

### ISSUE THREAD

**Issue by y8s** [mikejac/node-red-contrib-google-smarthome#204]
Is this really required? I am having a little trouble trying to figure out why it's required. Other services don't use a topic and leave it undefined/empty. It seems like an unnecessary extra configuration step. Maybe to save time, it could be configured globally in the setup node.

Also it's a little unclear to me if the "Out Topic" on the node is the same as the topic described in each node in the docs where it says "`topic` can be `on`, `online`, `brightness` or something else." If they are the same, can you update the readme to clarify that?

Other than that, the service and instructions for setup are great! Thanks!

**Comment by ckhmer1** [comment]
In my opinion should not be mandatory, in fact in the Google Device node it is not.
The Out Topic is used when the node receives a command from the Google Smart Home API and is not related to the input topic.
The Out Topic should be used to distinguish different nodes, perhaps the out message, after some elaboration will be sent to the MQTT bus.

**Comment by Paul-Reed** [comment]
It's not unusual for nodes to have a user defined output topics, and can be useful, see [this post](https://discourse.nodered.org/t/multistate-switch-no-output-topic/52145) in the node-RED forum, as an example.
As @ckhmer1 has said, users (including me) use the topic for MQTT purposes, see the screenshot below, which controls a shelly switch. Without the topic, I would need to add another process in the flow to introduce a topic.

You always, of course have the option not to use topics, but for me it's useful.

![shelly](https://user-images.githubusercontent.com/973580/144489238-2a3f44d5-c7e2-4992-b15d-67e9a6ba09f7.JPG)

**Comment by Caprico85** [comment]
Output topics can be useful. But you are right. It should not be required. In v0.1.14 I made the fields optional.

**Comment by y8s** [comment]
Thanks @Caprico85 !

**Comment by y8s** [comment]
Updated and tested. I removed all my out topics and now things are running smoothly. Thanks again.
