### ISSUE TITLE
Devices don't update in google home immediately without restarting flows

### ISSUE THREAD

**Issue by y8s** [mikejac/node-red-contrib-google-smarthome#205]
Redeploying a modified node does not update the data in google home.

For example: If I create a light node in google smarthome and name it "Light1" and deploy, it shows up in google home as "Light1".

If edit that node and rename it to "Desk Lamp", click "done" and redeploy, the changes do not take effect either in google home OR in the actual node output (e.g. with debug node). I'm not sure how long it takes as I've not waited. 

If I choose the option to restart flows in nodered, it does update immediately. 

Note that I've also tried sending topic "restart_server" to the setup node but that has no effect.

**Comment by ckhmer1** [comment]
Did You try sending "request_sync" to the setup node?
Did You try also with the Google device node?

**Comment by y8s** [comment]
Sending topic `request_sync` to the management node doesn't solve the problem. (it would have been easy to inject that at deploy) 
I also notice the management node doesn't output when I send request_sync to confirm the command like it does for restart_server. Should it?

I'm using a google device node to test but it behaves like the other device specific nodes.

As a quick test, I also gave it 10 minutes to update on its own (with various combinations of restart and resync of the server) but it never updated.

**Comment by y8s** [comment]
I set the delay  to "2" and tried again. 

Results are:

1. entering the management node and editing the google-smarthome client node settings and clicking "Update" at the top and Done on the management node and redploying does pick up the changes to other nodes.
2. restarting the server OR requesting sync does not change the nodes
3. editing a node and redeploying does not update the node output 

FYI I'm testing by changing the topic. 
Steps to reproduce:
1. Create a node for google device 
2. enter basic data, no topic (choose smarthome installation, name, type: switch, room hint, leave topic blank)
3. add debug node: show complete message
4. deploy
5. node works as expected
6. edit node, change topic to "testtopic"
7. deploy
8. **unexpected behavior:** node shows topic as ""
9. double click management node
10. click edit icon on smarthome field
11. click "Update" button
12. click "Done" on management node
13. deploy
14. topic for above google device node says "testtopic"
