### ISSUE TITLE
Release .23: Config Node not visible: Reports Waiting for googlesmarthome-client

### ISSUE THREAD

**Issue by davidstewartnz** [mikejac/node-red-contrib-google-smarthome#21]
Hi,
I have tried deploying release .23 on both a Raspberry Pi and also a windows deployment.
All the client "action" nodes appear as expected
I do not see the Config node on either system, and the instance  on the Raspberry PI reports:
Waiting for missing types to be registered: - googlesmarthome-client

I have used "npm ls" to check that the dependencies are in place

I apologize if this is simple user error, but if you could guide me on where/how to launch the config node

Thanks
David Stewart

**Comment by Caprico85** [comment]
Was able to reproduce this. On Node.js 10 it works. On Node.js 12 I get exactly the same error as you - the management node is missing and an error message shows in the logs:

`[node-red-contrib-google-smarthome/google-smarthome] TypeError: prop.match is not a function`

So far your only option is to downgrade to node.js version 10. I will also have a look into it and see if I can get it to work on version 12.

**Comment by davidstewartnz** [comment]
Thank you - the downgrade to version 10, in my case 10.19.0 worked - off to work through the rest of the configuration - your help much appreciated

**Comment by Caprico85** [comment]
node-red-contrib-google-smarthome should now work with Node 12 too (#27)
