### ISSUE TITLE
Server listens on TCP6 only

### ISSUE THREAD

**Issue by umiki7** [mikejac/node-red-contrib-google-smarthome#211]
Hi,
The server seems to listen on TCP6 only, which I suspect is the reason, why I cannot reach it (Oracle Cloud, IPv6 disabled by default).
I have no problems accessing other services listening on TCP4, including Node-red itself. I have no error messages in the logs, the server seems to be running OK.

**Comment by umiki7** [comment]
Starting the server on 0.0.0.0 does not solve the issue. The problem is probably elsewhere...

**Comment by ckhmer1** [comment]
If You leave the port field empty, the node uses the same port that Node-RED uses.

**Comment by umiki7** [comment]
I have tried that and also just added "0.0.0.0"  as host to the function call opening the listener effectively forcing it to IPv4. Neither of them helped, so the problem is not related to IPv6.

(Still I have no clue, why the https server is unreachable, even if running at the same port as Node-red. I can not get a response with reqbin, even from local net. No error messages in Debug.)

**Comment by ckhmer1** [comment]
Share Your Google SmartHome config, if You leave the port empty, and Node-RED is reachable, Google Smarthome must be reachablw.

**Comment by umiki7** [comment]
You were of course right, with an empty port, it was reachable. 
curl -k https://0.0.0.0:30003/check also worked (30003 is the port that I would like to use).
It was of course a firewall configuration mistake on my part (for the ones on OCI: it is not enough to add the rule to the security list, the machines local firewall might also need to be configured)
