### ISSUE TITLE
Cant get it to work. Google home app cannot reach (iobroker nodered)

### ISSUE THREAD

**Issue by TimoS911** [mikejac/node-red-contrib-google-smarthome#212]
Okay i think i have done everything but it wont work.

I just did everything in the manual and i also get a status 200 (OK) with reqbin.com.
NodeRed is installed as an adapter in iobroker. I forward port 80,443,3001,8084 to my iobroker raspberry.

My settings:
![accountlinking](https://user-images.githubusercontent.com/80464022/147075079-970804f0-f9cd-4801-820a-d80031d6731c.PNG)
![googleactions](https://user-images.githubusercontent.com/80464022/147075107-00f31242-bb0b-42fa-8d1b-6b066e4cc350.PNG)
![noderednode](https://user-images.githubusercontent.com/80464022/147075124-f467e174-a6ff-4c47-bb97-ff48f9d7aaa7.PNG)
![req](https://user-images.githubusercontent.com/80464022/147075360-251db748-66e6-436d-9936-9a7346ad8605.PNG)
![IMG_9008](https://user-images.githubusercontent.com/80464022/147075793-12c69d70-fe86-46cd-9ba3-ca655de8ea7f.PNG)

Is there any way i can check more stuff that can lead me to the point where i have something wrong?
To get to this point just took me way too long (fk ssl certificates + iobroker... just use certbot if you try to get ssl certificates...)

Would be nice if someone got an idea.
I am out of ideas.

**Comment by ckhmer1** [comment]
Open the browser to the /check page instead of sending it a rest request.
The page You see in the response is a test page, fill in the form info, and press test.

**Comment by TimoS911** [comment]
If i open the website "https://tim............net:3001/check i get an error that this page is not reachable.

![website-check](https://user-images.githubusercontent.com/80464022/147099990-fc9b2618-e70d-4b26-a2ed-01b8bd6da484.PNG)

So i need this page to be browsable? It should display something?

**Comment by Caprico85** [comment]
You accidentally included your URL on the screenshot. I tried to access it ... and it works.

![image](https://user-images.githubusercontent.com/2081806/147101495-98c77a5c-a066-47f3-a522-7af2343856fa.png)

So maybe something on your phone or your network is blocking the connection. Have you tried disabling WiFi to use your mobile internet connection?

**Comment by TimoS911** [comment]
Wow really... Thank god i accidentally included the URL :D
I can login with the google home app with wifi off.

Can this lead to any problems in the future?
I will try to add some dummy smart devices today in nodered and check if i can controll it with my phone app.

But thank you so much!

**Comment by Caprico85** [comment]
> Can this lead to any problems in the future?

During normal operation it shouldn't. The only one talking to your port 3001 are Google servers. As Google is coming from outside your network, it shouldn't hit whatever is blocking port 3001.

You might have to relogin after some months. As long as you remember to turn off your WiFi then, it shouldn't be a problem.

**Comment by TimoS911** [comment]
Okay i tested some different nodes and everything works fine.
Finally i can start on voice controll my HSV RGB lights.
I just have to figure out how to use NodeRed :) but thats not for this issue here.

Maybe you should add the little info that you can open the /check page in youre browser and should see that picture you send in the setup guideline. I thought that i can only get and post requests on that port/site.

Info for someone that finds this case because of google iobroker and this nodered.
Try not to hard to get the SSL stuff going directly from iobroker. It didnt work at all for me with letsencrypt on web.0/admin.0.
Just set up a certbot directly in ssh and use the path to the certificates in the main iobroker setup certificates tab.
Make sure that iobroker can read these as certbot maybe create these as root user and iobroker cannot access it. (try to cd there or nano the certificate via ssh and you will see if pi user can access.)
Once this is set up you can go ahead and use the well written instructions on how to set up this nodered node.
I just put the JWT Key json file in the iobroker upload directory and gave it the direct path to that file at the management node config. (/opt/iobroker/iobroker-data/files/0_userdata.0/iobroker-xxxxx-xxxxx-xx.json)

This case can get closed and thank you Caprico.
