### ISSUE TITLE
Google Device node Thermostat setting

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#214]
Hello all,

As already mentioned by @Caprico85, we are in a process that the "old" nodes will be deprecated and replaced by one "Google Device".
This is a good decision, as it will reduce the "palette". Therefore I already started the process of replacing all configured "old" nodes to the Google Device node. It worked very well with the Lights (on/off) devices.

So I started to look at the Thermostat node.
I created a simple test flow as below:

![Screenshot_Google_Device_Thermostat1](https://user-images.githubusercontent.com/46283323/147115499-8b87bad0-5698-4eab-b613-3687bfd332f8.png)

With an Inject node I injected the following object:

![Screenshot_Google_Device_Thermostat2](https://user-images.githubusercontent.com/46283323/147115602-55437bb6-56b0-4ed9-bfb5-9a3cf43690c3.png)

I would expect to see under the node something like H T:21.9 °C|S: 22 °C

However it looks like the node does not show the Setpoint value, as the "old" node does, but the Min threshold (°C) value.

Checking with the get_state command shows that the value is correctly received by Google.
See below:

![Screenshot_Google_Device_Thermostat3](https://user-images.githubusercontent.com/46283323/147116329-dc5c034d-3554-40e7-9e14-0ef8d7362b3b.png)

My configuration of the Google Device node is shown below:

![Screenshot_Google_Device_Thermostat4](https://user-images.githubusercontent.com/46283323/147116393-e1232811-2072-49a8-998a-0be40a821b6a.png)

Did I configure something wrong or is this a bug?

Regards

**Comment by ckhmer1** [comment]
I've sent a PR for fixing it.

**Comment by FireWizard52** [comment]
I have tested it and it functions as expected.
A very minor thing and this is only cosmetics is that in the status under the node a space is inserted between the temperature value and °C, e.g. T: 22.1 °C, while after the setpoint S: 21°C (without space before °C)
But this is not really important
As this issue is solved for now, we can close it.
