### ISSUE TITLE
Error in HttpActions:reportState() when selecting a channel on a media device

### ISSUE THREAD

**Issue by rockstar2020** [mikejac/node-red-contrib-google-smarthome#220]
Hi there,
I've been using Google device (TV) for quite sometime and it's been working flawlessly.
I basically have loaded several channels to the device and change them using voice command on my Google Home and then executing the script based on currentChannel state in the payload.
Recently I noticed that the command for changing channel still works perfectly but right after executing it, node red throws following error.
Any idea what could have caused the error?

Many thanks in advance.

![image](https://user-images.githubusercontent.com/35903046/147696466-c85f2c73-5fda-4eca-bea1-d73e9153811f.png)

**Comment by ckhmer1** [comment]
Don't use the media device node, it is deprecated, use the Google Device instead.

**Comment by rockstar2020** [comment]
I'm using Google Device node.

**Comment by ckhmer1** [comment]
Should be fixed, just wait for the new release.

**Comment by Caprico85** [comment]
Released v0.2.3 containing @ckhmer1's fix.

**Comment by rockstar2020** [comment]
Awesome! Thank you both.
