### ISSUE TITLE
Few issues with pin code

### ISSUE THREAD

**Issue by bartbutenaers** [mikejac/node-red-contrib-google-smarthome#222]
Hi guys,

Sorry to disturb you again.
Was experimenting with the pin code, but I have some issues with it:

1. Last night it worked fine.  But today when I say *"one two three four"* then I get the numbers as words (instead of digits *"1234"*).  And for the numbers as words, Google complains that the keycode has the ***wrong format***:

   ![image](https://user-images.githubusercontent.com/14224149/147728073-37b2843a-2587-4dfc-8ff7-5c12de50a228.png)

   This is a bit weird since Google should know that a keycode are numbers?  Saw that lots of other users have the same problem (non Node-RED related!).  When I say *"twelve fourty five"* then Google recognizes it again correctly as numbers *"1234"*.  

   I don't think you can solve this, so perhaps mention it in the readme (and info panel)?

2. When I speak my commands, then it works fine (i.e. Google asks my keycode).  However when I turn this switch on/off via the button, then it doesn't work correctly:

   ![image](https://user-images.githubusercontent.com/14224149/147728386-0b079899-4059-4380-8786-84d48461226b.png)

   When I switch the device on/off via the button, that works fine for switches without key code.  However with key code enabled, the buttons don't ask for a keycode, and no output messages are being send in Node-RED.  Only the local status (in the big letters) changes, with is rather confusing because you get the impression that the command has been executed succesfull.

   Note that I see exact the same behaviour via the button in the Home app:

   ![image](https://user-images.githubusercontent.com/14224149/147728695-6f156aa4-e9c3-4586-93eb-65bc0acd4675.png)
 
Thanks again !!!
Bart

**Comment by ckhmer1** [comment]
This is a Google problem, when the node red plugin receives the message to switch on our off respond with the pin needed error message.
Google should revert back the status immediately.
I think nothing we can do for it.

**Comment by bartbutenaers** [comment]
Ok no problem.
Thanks!!
