### ISSUE TITLE
Not able to control volume on media devices

### ISSUE THREAD

**Issue by rockstar2020** [mikejac/node-red-contrib-google-smarthome#229]
Hi there, 
Happy New Year!
I've been dealing with a weird issue and I'm hoping some folks could help me out here by recreating the issue on their side.  
Lately I noticed I'm not able to turn the volume up or down on any media device node. 
I can turn the device on or off but whenever I trigger a voice command to change the volume, google home says "Sorry, I didn't understand" or sometimes adjusts the volume of Google home device instead. 
This was not the case since almost a year I'm using this fantastic piece of work. 

Can you follow the below steps to recreate the flow and let me know if you're also facing the same issue?
Accordingly I'll know if the issue is from my setup or not. 

1. Add a Google Device Node (I'm using the latest release).
2. Change the device to a media device such as Soundbar, TV, Speaker or anything else that you can control the volume with. Just make sure volume trait is selected. 
3. Connect the output of the media node you just added to a debug node. 
4. Deploy. 
5. Say a voice command like "turn up the volume on xxxxxxx".
6. Check if your command runs successfully and the debug node throws a payload that indicates volume adjustment. 

Many thanks in advance

**Comment by ckhmer1** [comment]
I get the following message:

![image](https://user-images.githubusercontent.com/2863760/148509575-93ef32f7-509b-4e7d-90e6-a6ffa245c0a7.png)

What is wrong?

**Comment by rockstar2020** [comment]
Thanks a lot!
In this case something is wrong with Google I guess because it doesn't pass my voice command. 
Appreciate testing it for me. 
Cheers
