### ISSUE TITLE
Getting error reported from Management node

### ISSUE THREAD

**Issue by Paul-Reed** [mikejac/node-red-contrib-google-smarthome#230]
I'm running the latest version, and have also patched https://github.com/mikejac/node-red-contrib-google-smarthome/pull/228 but am noticing that I'm getting an error reported from the Management node.

Steps to recreate

![lamp](https://user-images.githubusercontent.com/973580/148525149-22c53684-cc4e-4923-871a-1ac108bab93a.JPG)

Add a device node to workspace and select 'light' device and include 'brightness' trait.
With nothing else connected to the node, this then appears to work fine when using the phone 'Home' app, but checking the debug, the Management node produces an error message;

```
{
  "msg": "Error in HttpActions:reportState()",
  "org_msg": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  },
  "data": {
    "postData": {
      "requestId": "7azbiFvOX9fBfpn6TRQdJ8",
      "agentUserId": "0",
      "payload": {
        "devices": {
          "states": {
            "e05d5857524a8131": {
              "online": true,
              "on": true,
              "brightness": 18,
              "name": "table lamp"
            }
          }
        }
      }
    }
  }
}
```

**Comment by ckhmer1** [comment]
Could You please comment the line number 291 in the Devices.js file and let me know.

**Comment by Paul-Reed** [comment]
I've commented out line 291
`// states[deviceId].name = name;`

Restarted node-RED, and the error message no longer appears.
However now, even ticking 'persistent state' does not result in a status update from the Management node (you maybe expect this).
Otherwise the node works fine,

**Comment by ckhmer1** [comment]
I've checked locally and it is working.
Did You configure it correctly?

**Comment by Paul-Reed** [comment]
I've now added in https://github.com/mikejac/node-red-contrib-google-smarthome/pull/228/commits/e0288e067bd9b3daa18ca6e9f6fe3b47463e4808 which has been added since my last attempt.

It's strange really, because I've had a device node configured as a light with on/off/brightness traits for several months, which works perfectly now with no errors, but when I add another device node configured the same (different name), and switch it on (using phone app) it does not trigger a status report from he management node. If I switch my 'old' device node on, it does trigger a status report which also includes the new device node status as expected;
```
{
  "f937fb3622739174": {
    "online": true,
    "on": false,
    "brightness": 1
  },
  "fb6085c3cf5c1fd8": {
    "online": true,
    "on": false
  }
}
```

It appears that any **new** added node does not trigger a 'get_state', yet my old nodes do !!!

**Comment by Paul-Reed** [comment]
A system reboot, and everything is now working as it should.
Your PR resolves all issues for me, thanks for the quick response.
Closing....
