### ISSUE TITLE
[Question] What to expect from the Google Device node, configured as "Scene"

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#232]
If you configure the Google Device node as a "Scene", what should be injected in the input? You cannot tell Google what scene to activate. Google tells you. However I have never seen anything at the output. What to expect.

The only thing I see at this node, if I use the get_state command, is that "online" is true. 

How should this node work?

**Comment by ckhmer1** [comment]
Scenes has no properties, I'm not sure that the online one is working, be one never tried to disable it.
I've only tested the voice command to enable and disable it.

**Comment by FireWizard52** [comment]
Hello @ckhmer1,

> Scenes has no properties

I know and that is correct.

> I'm not sure that the online one is working, I've never tried to disable it

If I tell to my (in this case) Google Nest Hub: "Activate <Scene name>, I receive at the output of the node an Object with
"online" : true.
However I had hoped to see, according to https://developers.google.com/assistant/smarthome/guides/scene#response,
something like "status": "SUCCESS", in addition.

Or a text like activated or in case the Scene reversible checkbox is ticked also something like deactivated.

Or is my idea completely wrong?

> I've only tested the voice command to enable and disable it.

I did not test that and I'm wondering what the result will be?

Regards

**Comment by ckhmer1** [comment]
The payload contains only the nice state.
Print out the complete message and you will see more info regarding the command received

**Comment by FireWizard52** [comment]
Hello @ckhmer1 

Unfortunately, this does not give more useful info.

![Screenshot_scene_bedtijd1](https://user-images.githubusercontent.com/46283323/148611108-505c65cb-2a4f-43d1-8f4c-edd9b9f83bb4.png)

Regards

**Comment by ckhmer1** [comment]
It should give all the info you need 
Command tells you that you asked for a scene activation.
Deactivate equals to false tells you that it is an activation.
For the scene, i use this last info to activate or deactivate something

**Comment by FireWizard52** [comment]
@ckhmer1 

So you don't use "status": "SUCCESS"? Sorry, if that was a wrong expectation.

Regards

**Comment by ckhmer1** [comment]
The status info never goes outside the node, forget it

**Comment by FireWizard52** [comment]
I implemented a flow with the data, presented above and it works.
Thanks for the support.

Great piece of software

Topic can be closed.

Regards

**Comment by FireWizard52** [comment]
While checking for an other issue. (See: #342), I discovered that the only error occurring regularly is related to Scene.
So obviously there is something wrong:

See message below:

`SYNC: Request ID 16843626070593528282 update devices failed: INVALID_ARGUMENT. Detail: No SupportedTraits for device [type: "action.devices.types.SCENE"
agent_device_id {
  agent_id: "jonas-node-red-c3709"
  device_id: "91e3033013249be7"
}
will_report_state: true
device_info {
  manufacturer: "Node-RED"
  model: "nr-device-scene-v1"
  hw_version: "1.0"
  sw_version: "1.0"
}
attributes {
}
custom_data: "{\"accessToken\":\"27HotRBjvoZqd5mFxsetpMpNSmqSRWkUX327BUdpDrAC\",\"clientId\":\"d7ec4b2f72adc483\",\"httpPathPrefix\":\"/\",\"httpPort\":18080.0}"
agent_device_names {
  name: "Bedtijd"
  default_names: "Node-RED Scene"
}
inferred_room {
  structure_id_from_hint: "0e48da69-8b10-42aa-a2d8-f1f91b9475f2"
  room_id_from_hint: "0e48da69-8b10-42aa-a2d8-f1f91b9475f2.f56e84a2-65ec-4e0c-84ee-831ff6d67c28"
}
other_device_ids {
  agent_id: "jonas-node-red-c3709"
  device_id: "91e3033013249be7"
}
].
{
insertId: "17ae6uafeagqd8"
logName: "projects/jonas-node-red-c3709/logs/actions.googleapis.com%2Factions"
receiveTimestamp: "2022-11-30T17:14:07.218304220Z"
resource: {2}
severity: "ERROR"
textPayload: "SYNC: Request ID 16843626070593528282 update devices failed: INVALID_ARGUMENT. Detail: No SupportedTraits for device [type: "action.devices.types.SCENE"
agent_device_id {
  agent_id: "jonas-node-red-c3709"
  device_id: "91e3033013249be7"
}
will_report_state: true
device_info {
  manufacturer: "Node-RED"
  model: "nr-device-scene-v1"
  hw_version: "1.0"
  sw_version: "1.0"
}
attributes {
}
custom_data: "{\"accessToken\":\"27HotRBjvoZqd5mFxsetpMpNSmqSRWkUX327BUdpDrAC\",\"clientId\":\"d7ec4b2f72adc483\",\"httpPathPrefix\":\"/\",\"httpPort\":18080.0}"
agent_device_names {
  name: "Bedtijd"
  default_names: "Node-RED Scene"
}
inferred_room {
  structure_id_from_hint: "0e48da69-8b10-42aa-a2d8-f1f91b9475f2"
  room_id_from_hint: "0e48da69-8b10-42aa-a2d8-f1f91b9475f2.f56e84a2-65ec-4e0c-84ee-831ff6d67c28"
}
other_device_ids {
  agent_id: "jonas-node-red-c3709"
  device_id: "91e3033013249be7"
}
]."
timestamp: "2022-11-30T17:14:07.207824227Z"
}`

**Comment by ckhmer1** [comment]
I think I've fixed it in my last pr not yet delivered.
I had the same issue with scene, but with my last pr disappears.
I asked today at @Caprico85 to deliver the last pr, I'm waiting for a response.

**Comment by FireWizard52** [comment]
I don't think that #256 has been merged, as I still see "unknown"  under the node instead of "Ok"

**Comment by FireWizard52** [comment]
Correction to above post.

If it has something to do with the update to version 0.4.0, I have no idea, but it shows OK under the widget.
Perhaps @ckhmer1 's  PR has been included. 

![Screenshot_Scene_widget](https://user-images.githubusercontent.com/46283323/205311101-9b7fdaeb-064b-42f3-bc3a-5201809edfe0.png)

I also did not notice any error messages in the Google log.

So the topic can be closed i.m.o.
