### ISSUE TITLE
Google Log in failed

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#241]
Hi,

Last evening I noticed, when I wanted to switch of my lights with a voice command that Google responded with something as <Name> is not available. It has happened before but then after a few seconds it was okay again. I think that was a network issue.
However this morning still not available.

I do not believe that this issue is directly related to node-red-contrib-google-smarthome , as it has been working for approx. 2 month without giving any issues.

I did already the following:

1. Restart the Google device (Nest Hub)
2. Tried to  Reconnect account in Google Home app
3. Tried to unlink account in Google home app and log in again
4. Restart google-smarthome server.
5. Restart Node Red
6. Restart Raspberry Pi
7. Power down Google Nest Hub.
8. Test if <domainname.nl>;3001/check is reachable (Success)
9. Tried to login from outside my Local network in order to avoid NAT Loopback issue.

I still had no success to log-in with my Google account.
Finally I switched back to Local Authentication with Username/Password and log-in was successful.
So all my devices functions again.

Has anybody noticed this before? Has something with Google Log-in expired?

If I try to login with Google I see in my screen that it is redirected to "accounts.google.com" and nothing happens
if I use that URL in the browser, it connects to my account page. 

Any hint what to check or where to look is welcome.

Regards

**Comment by Caprico85** [comment]
> Last evening I noticed, when I wanted to switch of my lights with a voice command that Google responded with something as is not available. It has happened before but then after a few seconds it was okay again. I think that was a network issue.

I currently have similar problems. First command fails, from the second command on it works. Some hours later first command fails again. I suspect it is related to token renewal. After some hours the token expires and needs to be renewed. Maybe the token renewal takes too long or we are doing something wrong. I didn't had the time to investigate further.

<br>

> Has anybody noticed this before? Has something with Google Log-in expired?

It's probably related to [oAuth consent screen](https://console.cloud.google.com/apis/credentials/consent) or [credentials](https://console.cloud.google.com/apis/credentials). Unfortunately our instructions on Google Sign-In are a bit outdated. Google seems to have changed their pages once again. I am currently rebuilding our [setup instructions](https://console.cloud.google.com/apis/credentials). The instructions on Google Sign-In are not updated yet. If you can wait a few days, I might have it ready by then.

**Comment by Caprico85** [comment]
I updated the setup guide. Can you please go through [the instructions on Google Sign-In](https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/docs/setup_instructions.md#integrating-google-sign-in-optional) and compare your settings to the screenshots?

**Comment by FireWizard52** [comment]
Hello @Caprico85,

Thank you for updating the documentation. Especially the screenshots are very useful.

I read the complete manual.
I checked my configuration of the Google Sign-in carefully with this document (3 times)

Unfortunately I have not been able to sign-in with the Google account.
Strange as it has worked before.
In Google I have the following configured:

![Screenshot_Google_login1](https://user-images.githubusercontent.com/46283323/151999984-110873e5-0c7d-4aa5-a49e-c7f200663212.png)

![Screenshot_Google_login2](https://user-images.githubusercontent.com/46283323/152000039-31afd10b-33f9-4401-87ba-69ef1dbafd69.png)

![Screenshot_Google_login3](https://user-images.githubusercontent.com/46283323/152000086-b4c8e666-fb05-4e42-8fcc-975e5524e598.png)

As you can see, my screen 2 is different than the picture in your documentation.
I have as 3 "Test Users", while you have "Optional Info".
Does that mean I have to fill in myself as a test user? Don't believe it?

Trying to sign-in in the Google Home app on my phone gives me first https://example.com:3001/smarthome.
If I press "Sign-in with Google" it wants to go to "accounts.google.com", but it stops there.
"accounts.google.com" is reachable from my phone.

I do not thing it is related to this app, but there might be something else.
Did not find it, yet. Any suggestion, where to look?

Regards

**Comment by Caprico85** [comment]
> As you can see, my screen 2 is different than the picture in your documentation. I have as 3 "Test Users", while you have "Optional Info". Does that mean I have to fill in myself as a test user? Don't believe it?

Thats interesting. If I edit the Demo project, I now also see "Test users". If I edit my own project, I see "Optional Info". I currently have no idea why this happens.

Nonetheless, both screens should be empty. I think, Test users is only needed when you invite other users into your project. Optional Info is only needed for verification by Google when you release your project to the public (which you never do)

I just noticed something else. I forgot the step with Authorized emails in the guide.


> 
> Trying to sign-in in the Google Home app on my phone gives me first https://example.com:3001/smarthome. If I press "Sign-in with Google" it wants to go to "accounts.google.com", but it stops there. "accounts.google.com" is reachable from my phone.
> 
> I do not think it is related to this app, but there might be something else. Did not find it, yet. Any suggestion, where to look?
> 
> Regards

**Comment by Caprico85** [comment]
Oh damn. I just tried to unlink and relink my project. Exactly as you, now I am getting redirected to an empty page on accounts.google.com and then nothing happens.

I'll investigate further. For the time being, you should stay on password based authentication.

**Comment by FireWizard52** [comment]
Hi. @Caprico85 

Just to verify, it happens after you pushed "Sign-in with Google" and that points you to "account.google.com"?
The strange thing is that, it worked before and then suddenly I couldn't reach my devices.
I did the same as you (relink) and I could not sign-in anymore.

While trying to get local execution working I noticed a very strange thing and I'm not sure that it should be in this topic.
But I will mentioned it  anyhow.

Previously I had Node Red OpenAQ (Air Quality) installed. See: https://flows.nodered.org/node/node-red-contrib-openaq
This application should have no relation with Google Smarthome.

I used it for a while but I had no flow, using these nodes, running, but they were still in the palette.
The node-red-contrib-openaq module created also a openaq.log file in my home directory and I found that this grew pretty fast in size. It turned out that a lot of Google Smarthome logdata has been written into this file.
You could delete it, but after a reboot I has been created again.
So Google Smarthome logdata in OpenAQ log. Very strange.

Together with upgrading to version 0.2.8, I removed OpenAQ from the palette.
And now all that log data comes into node-red-log and makes the log unreadable.

See an example below:

![Screenshot_Node-Red-Log](https://user-images.githubusercontent.com/46283323/152054484-f8965829-1bc5-4c7e-9cc6-16d8aa63f67d.png)


Any idea?

**Comment by Caprico85** [comment]
Judging by the code, node-red-contrib-openaq seems to override all calls to console.log(), console.error() and the like with its own logging functions. This way it redirects log output from all other nodes into its own log file openaq.log.

![image](https://user-images.githubusercontent.com/2081806/152056082-b011bb34-143d-495f-a81b-4f480f6339a5.png)

Bad practice by the openaq package, but this shouldn't cause problems with Google Login.

**Comment by FireWizard52** [comment]
Indeed bad coding practice. I removed the openaq package
But as you said, it should not reflect Google Log-in.
But, is it possible to limit the log data?

**Comment by Caprico85** [comment]
Unfortunately not. node-red-contrib-google-smarthome can be very talkative. I haven't found a good way to limit it to only the relevant messages.

**Comment by Caprico85** [comment]
Seems to be related to a security feature on our side. If I comment out

```
this.app.use(helmet());
this.app.use(cors());
```

in SmartHome.js and

```.set("Content-Security-Policy", "default-src 'self' 'unsafe-inline' *.google.com")```

in HttpAuth.js, I can successfully login.

Of course disabling all security features isn't the right way. I'll need to find out what exactly is causing this.

**Comment by Caprico85** [comment]
Should be fixed in v0.2.9.

This was caused by an incorrect HTTP header Cross-Origin-Opener-Policy. This prevented the Google popup to get a backreference to our login page. And instead of showing some kind of helpful error message, Google preferred to simply do nothing ☹️

**Comment by FireWizard52** [comment]
Hello @Caprico85,

I installed version 0.2.9 and can confirm that it is possible again to log-in with the Google account.
So, it seems that this issue is solved.

One remark for other users.

Be aware, that you might have to sign-in with your mobile phone from outside your local network (example 3G/4G)
Suppose your domain is example.com, your phone will not connect to example.com:3001, if it is connected to your LAN, unless your router supports NAT Loopback (hairpinning). See: https://en.wikipedia.org/wiki/Hairpinning.

I think we can close this issue for now.

Thanks for solving this issue so quick.

Regards

**Comment by Caprico85** [comment]
Nice! Didn't know about hairpinning. Thank you. I might add that to the readme.
