### ISSUE TITLE
Account Link / Device Sync issue

### ISSUE THREAD

**Issue by bkdfkup** [mikejac/node-red-contrib-google-smarthome#244]
Hi mikejac.

Ill start by saying thanks for your efforts developing this node and associated guides, its great to have new ways to connect smarthome ecosystems.

I have an interesting issue where as far as i can tell everything is configured correctly, and i can successfully link my node-red-contrib-google-smarthome with Google Home, and control devices as expected. 

The issue lies in the fact that no new devices are syncing if i add any, and any attempt to "Reconnect account", or Unlink and re-link via Google Home fails. The screenshots below show any link attempt from this point.

![Screenshot_20220125-155917](https://user-images.githubusercontent.com/74683396/151066395-aea5baa8-c003-46af-92ae-a062c325b59f.png)
![Screenshot_20220125-155840](https://user-images.githubusercontent.com/74683396/151066417-0803b5b8-c9e7-40ec-bdd8-2e7f2497e66e.png)
![Screenshot_20220125-155902](https://user-images.githubusercontent.com/74683396/151066432-949937a7-a485-4a27-8c3b-c32da660fa19.png)

I can successfully reach the webservers check page as seen here, both internally and externally:

<img width="284" alt="Screenshot 2022-01-26 084447" src="https://user-images.githubusercontent.com/74683396/151066699-7d59fc13-b745-43d5-9ca9-e7c095da4fcc.png">

Server config for information:

<img width="344" alt="Screenshot 2022-01-26 084359" src="https://user-images.githubusercontent.com/74683396/151068901-072683ae-6370-4cf2-b654-a8fcb0b70ace.png">

Troubleshooting steps i have attempted are (in no particular order):

- Re-start server via management node
- Reboot Node Red
- Checked google-side configurations against documentation
- Tried different ports
- Re-created google service accounts and keys
- Changed local user credentials, removing any special characters.
- Uninstalled and reinstalled node-red-contrib-google-smarthome entirely (above scenario still occurs)
- Deleted auth configuration files and confirmed they are populating
- Tried with node-configured SSL and SSL offloading (via NGINX0, with same results with either.

Now here's the kicker, I have found that if I DELETE the nodes server config and create a new one with the EXACT same settings, i can add the new configuration to my nodes and successfully link my account. ONCE. And then the above issue repeats itself.

For information, i am routing via Cloudflare DNS proxy and have a local NGINX instance to handle routing and SSL duties server-side. The fact that i can successfully link accounts with this configuration, and a the server config deletion and recreation lets me work around the issue, i dont think the Cloudflare/NGINX presence is a factor. I could be wrong.... 

Grateful for any assistance. Let me know what other info you require.

**Comment by ckhmer1** [comment]
Did You fill out the check forms and pressed the test button?

**Comment by bkdfkup** [comment]
![Untitled](https://user-images.githubusercontent.com/74683396/151253939-bd35bdde-e7f0-4093-9112-75eba32e29a3.png)

Just replicated the scenario. Tested OK prior to initial account linking, and still tests ok after receiving the error message during re-linking account and / or failing to sync new devices.

**Comment by ckhmer1** [comment]
Could You please post the logs related to the issue? I think before adding a new node.
If You configured the delay "Request sync delay (s)", please wait the specified seconds for the "request sync" message and then post all the logs. 
Thanks

**Comment by bkdfkup** [comment]
Please close this issue. I was unable to pull logs so rebuilt from scratch. All now working as expected. Thanks for your help.
