### ISSUE TITLE
SensorState displays "Unknown"

### ISSUE THREAD

**Issue by domenicoblanco** [mikejac/node-red-contrib-google-smarthome#245]
Hi, first of all thanks for this awesome project!

Today I tried to configure a Water Leak sensor with the following payload using the Google Device node. 
```
{
    "currentSensorStateData": [
        {
            "name": "WaterLeak",
            "currentSensorState": "leak"
        }
    ]
}
```
The node doesn't return any error except for the debug message under the node that always displays "Unknown" as in the picture
<img width="515" alt="Screenshot 2022-01-29 at 15 27 51" src="https://user-images.githubusercontent.com/9018104/151664723-9bd0b6da-da47-4541-bac7-b8ad8fcadf3b.png">

This is the current node setup, I cannot understand what I'm doing wrong. I tried also with CarbonMonoxideLevel and AirQuality with the examples provided in the [Sensor State page](https://developers.google.com/assistant/smarthome/traits/sensorstate#device-states) but the result is the same
<img width="503" alt="Screenshot 2022-01-29 at 15 29 01" src="https://user-images.githubusercontent.com/9018104/151664754-371f4a47-9368-4b35-9dd2-3798ea8d4860.png">

**Comment by Caprico85** [comment]
Released v0.2.7 including @ckhmer1's fix.
