### ISSUE TITLE
Version 0.2.7: Temperature Sensor not working.

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#253]
Hi,

I updated this afternoon to version 0.2.7 and noticed that the sensor (temperature) will not be updated anymore.
It has been working, without issues, with 0.2.6 and previous versions.

I send the following data to the device:

![Screenshot_Google_outdoorTemp](https://user-images.githubusercontent.com/46283323/151998070-180804d0-6223-4d4b-81af-f8e75e3e3d9b.png)

Google responds with: Cannot reach Google device name

The configuration of the device node is as follows:

![Screenshot_Google_Device_Sensor_Temp_Config](https://user-images.githubusercontent.com/46283323/151998257-40f36131-0147-44b1-b708-db9fbdcb5db8.png)

![Screenshot_Google_Device_Sensor_Temp_Config2](https://user-images.githubusercontent.com/46283323/151998287-90c164ac-3121-4a19-9ca8-9e7bd9c01cbd.png)

Anything changed, regarding the sensor node?

Regards

**Comment by ckhmer1** [comment]
This should be fixed with the PR #249

**Comment by FireWizard52** [comment]
Thank you,  @ckhmer1,

This PR fixed also my issue. Thanks for the quick response.

Regards
