### ISSUE TITLE
Request: Reduce amount of information in Node-RED help tab

### ISSUE THREAD

**Issue by y8s** [mikejac/node-red-contrib-google-smarthome#268]
Every time I refer to the help tab for a node-red-contrib-google-smarthome node over where the debug window is, I am mildly frustrated that I have to scroll very far down through the "Device Types" and "Device Traits" lists before I get to the i details and node configuration I need. I realize the sections are collapsible, but it might make sense to reorder this list so the long list of stuff not applicable to my specific node is down at the bottom and the per-node configuration details are up at the top.

Or maybe just link to the nodered.org page or github read me for the nodes and keep all of that stuff out of the help section. It seems atypical to have that much information, even for a complicated node package. Where other nodes have 1 - 3 pages  of text there, this one has **26**!

Generally once configured, I need only to refer to how to communicate with the node.

Here's what I'd suggest to keep it simpler:

- Keep the Inputs and Outputs sections at the top
- Remove the Device Types and Device Traits sections
- Keep the "Node Properties" section 
- Keep the "Input Message" section up to just before "The following topic values are special treatments:" 
- Keep the "Output Message" section
- Keep the two notes if you like.
- Add the stuff removed to a link in the References section, e.g. "Device Types", "Device Traits", "Topics with Special Treatments"

That should pair it down to a more user-friendly length. 

Thanks!

**Comment by Caprico85** [comment]
Removed the links to device traits and types from the docs, only kept the links.
