### ISSUE TITLE
Request for support for device nicknames

### ISSUE THREAD

**Issue by csmale** [mikejac/node-red-contrib-google-smarthome#280]
Could I put in a request for the support of device nicknames? I have been using them in (ahem) a "competing solution" and find them very useful in a mixed-language household like ours where even in English people use different names for the same thing.

It would be awesome if this could be added!

**Comment by Paul-Reed** [comment]
Unless I'm misunderstanding your request, I'm not sure that this is something that can be added to smarthome, as it's usually achieved by using 'routines' in the google home app, where you can assign a number of different phrases to the same device action -

![screen](https://user-images.githubusercontent.com/973580/164535724-fb2937c6-f08a-4238-81ce-38b160b68bed.png)

**Comment by Caprico85** [comment]
I think it is possible.

According to https://developers.google.com/assistant/smarthome/reference/intent/sync a device can report defaultNames and nicknames besides its "real" name. None of this is currently implemented though.

![image](https://user-images.githubusercontent.com/2081806/164537541-1c84cb21-28f5-4c14-9ad9-4740b3ff3288.png)

**Comment by csmale** [comment]
No, this is something different. It is information that is included in the SYNC response, next to the "name" information. It is not intended as a command, or a whole sentence; just as an alternative name for the device, so "Awning" and "Canopy" and "Zonnescherm" can all be used to refer to the same thing. This name can then be used in voice commands like "OK Google, open the {x}". Yes, it even works in different languages...

It's nothing fancy, just an array of strings. They are not even tagged with a language.

It's documented on https://developers.google.com/assistant/smarthome/reference/intent/sync?hl=en:
![image](https://user-images.githubusercontent.com/1978633/164538364-bbb49333-4928-4807-959c-e3cb65259062.png)

**Comment by csmale** [comment]
I notice the subtle difference between "defaultNames" and "nicknames" - one is intended to be provided by the manufacturer (and that's us, effectively) and the other is "provided by the user". I have never noticed any kind of UI however for the user to manage the nicknames.

**Comment by Paul-Reed** [comment]
Ah OK, I hadn't seen that feature before, but can see it's usefulness.

**Comment by Caprico85** [comment]
Released v0.3.4 including (somewhat experimental) support for nicknames. You can now set a comma-separated list of nicknames on devices.

![image](https://user-images.githubusercontent.com/2081806/164550318-88238d6a-0390-4986-93a0-890f7da0adb6.png)

Requires more documentation, but should work.

**Comment by csmale** [comment]
Wow, that was quick @Caprico85 ! Thank you so much! I will try it out later today.

**Comment by csmale** [comment]
It's working! One thing for the documentation though. If I look on my phone at the Google Home app, the name used as the label for the device, and the name used in any confirmation message, is now the **first nickname** (if any are present) and not the name set in the name field. So users should be reminded to copy the "name" to the first "nickname" **if they are going to use nicknames** on a particular device.
This is standard Google functionality and is no reflection on this code which as we can see is just passing the message to Google.
Thanks again!

**Comment by Caprico85** [comment]
> [...] is now the **first nickname** (if any are present) and not the name set in the name field. So users should be reminded to copy the "name" to the first "nickname" **if they are going to use nicknames** on a particular device.

I changed the code to automatically report the device name as the first nickname if nicknames are set. So, devices always keep their "real" name without the user doing anything.
