### ISSUE TITLE
How can I use this on the Home Assistant Node Red?

### ISSUE THREAD

**Issue by ArcaEge** [mikejac/node-red-contrib-google-smarthome#287]
Home Assistant has an addon for Node Red and I would like to run this on it. However I followed the setup instructions but the /check page doesn't load and says refused to connect. How an I fix this? I believe this is because Home Assistant blocks outbound connections for some addons.

**Comment by Caprico85** [comment]
I never really used Home Assistant, so I am probably not of much help here.

As far as I know Home Assistant is based on Docker. This means, its maybe not Home Assistant blocking outbound connections, but Docker not forwarding inbound connections.

You can try running `docker ps -a` on the shell. There you see a list of the running containers, each with their port forwardings.

![image](https://user-images.githubusercontent.com/2081806/171041831-20753daa-23af-4430-93dc-fcecf5f9a026.png)
In my case port 3001 is forwarded to Caddy (which reverse proxies to Node-RED internally).

Do you see any containers? Is Node-RED running in its own container or is it included in Home Assistants container. Is there a container with port 1880 assigned?
