### ISSUE TITLE
how to install using Node-Red Add-on in Home Assistant installed in Virtual Machine

### ISSUE THREAD

**Issue by sacredprey005** [mikejac/node-red-contrib-google-smarthome#298]
Hi,

I have node-red installed as an add-on in Home Assistant which is installed in a virtual machine. Can somebody share instructions on how to use this or install this using that config? like what will be the service url? the oauth/token url? etc.. any help would be appreciated.. thank you.

**Comment by tpickle-py** [comment]
i have node-red as a addon in HA, and would like to use this aswell


I cant for the life of me figure out how to setup the OAUTH/TOKEN under the configuration in nodered, what values should be present.

**Comment by Caprico85** [comment]
The basic install process is documented in https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/docs/setup_instructions.md. 

My settings in Node-RED are currently are as follows. You won't be able to copy them exatly, as they are use an external reverse proxy and I don't use HA. But they may serve as a starting point.
![image](https://user-images.githubusercontent.com/2081806/189472459-a241a885-ab26-4a61-bbbf-6f97f10a7bdc.png)
![image](https://user-images.githubusercontent.com/2081806/189472511-37b60d26-d54f-4c87-b334-12547558e1d0.png)

And I have to say, it's been a while since I played around with Home Assistant. So my knowledge may be "a bit rusty". But I'm trying my best to help.

I guess, the biggest challenge is to get the SSL setup and the port forwarding set up. Therefore, some questions first:

Do you already have a domain registered (e.g. from a DynDNS provider)?
Do you already have SSL certificates?
You run Home Assistant on a Raspberry Pi (or simlar), by flashing it's image on the SD card (so HA has full control over your host)? Or did you setup HA by running its Docker container on your existing host?

**Comment by tpickle-py** [comment]
> - [x] Domain registered and using DDNS
> - [x] Have SSL certificates (certbot/Lets Encrypt)
> HA Environment:
>   - [ ] You run Home Assistant on a Host (RaspiberryPi)
>   - [x] HA has full control over vm host (ESX/Hyper-V/)
>   -
>   - [ ] Docker Container on  Docker Host
> Network Stack  
>   - [ ] Docker Setup (Nginx Reverse Proxy)
>   - [ ] Firewall forward port Nginx Reverse Proxy 
>   - [ ] Inbound Firewall Rule and Destination NAT Configured for node-red-contrib-google-smarthome
>   - [x ] Inbound Firewall Rule and Destination NAT configured for Home Assistant
>   - [ ] Node Red Configuration:  _Partially Filled out_
> _Local Authenication_
> `Use Google Login` 🔲
> `Username:` _NULL_
> `Password:` _NULL_
> _Actions on Google Project Settings_
> `Client ID` ✅ Configured
> `Client Secret` ✅ Configured
> _Web Server Settings_
> `Port:` _NULL_
> `Path:` _NULL_
> `Local Fulfillment Port:` _NULL_
> _Google HomeGraph Settings_
> `JWT Key` ✅ Configured
> 

Not sure if I need to put anything into Local Authentication, this is where I am having trouble, as well as what additional configuration is needed

**Comment by tpickle-py** [comment]
> > * [x]  Domain registered and using DDNS
> > * [x]  Have SSL certificates (certbot/Lets Encrypt)
> >   HA Environment:
> >   
> >   * [ ]  You run Home Assistant on a Host (RaspiberryPi)
> >   * [x]  HA has full control over vm host (ESX/Hyper-V/)
> >   
> >   * [ ]  Docker Container on  Docker Host
> >     Network Stack
> >   * [ ]  Docker Setup (Nginx Reverse Proxy)
> >   * [ ]  Firewall forward port Nginx Reverse Proxy
> >   * [ ]  Inbound Firewall Rule and Destination NAT Configured for node-red-contrib-google-smarthome
> >   * [x]  Inbound Firewall Rule and Destination NAT configured for Home Assistant
> >   * [ ]  Node Red Configuration:  _Partially Filled out_
> >     _Local Authenication_
> >     `Use Google Login` 🔲
> >     `Username:` _NULL_
> >     `Password:` _NULL_
> >     _Actions on Google Project Settings_
> >     `Client ID` ✅ Configured
> >     `Client Secret` ✅ Configured
> >     _Web Server Settings_
> >     `Port:` _NULL_
> >     `Path:` _NULL_
> >     `Local Fulfillment Port:` _NULL_
> >     _Google HomeGraph Settings_
> >     `JWT Key` ✅ Configured
> 
> Not sure if I need to put anything into Local Authentication, this is where I am having trouble, as well as what additional configuration is needed

I dont think the home assistant  add-on will allow you to open a new port for smart home, this is why I didn't configure the NAT and Firewall rules

**Comment by Caprico85** [comment]
> Not sure if I need to put anything into Local Authentication,

Leave Google Login disabled. It would need additional configuration. Username/password authentication is enough for the start. Enter an username and password of your choice. These are the credentials you use when you link your account in the Google Home app later.

> I dont think the home assistant add-on will allow you to open a new port for smart home, this is why I didn't configure the NAT and Firewall rules

Unfortunately I don't know enough of HA to suggest you how to open up ports. But there might be other options.

Option 1:
node-red-contrib-google-smarthome doesn't neccessarily need its own port. It can reuse the same port as Node-RED. So, if HA exposes Node-RED's port (1880 by default) to the network, it would expose google-smarthome as well. Unfortunately this brings other problems. If you forward Node-RED's port to the internet, you need to secure it. Node-RED would need user authentication. And as Google requires HTTPS encryption, Node-RED would need to be HTTPS encrypted as well.

Option 2:
You could use a reverse proxy. Even if HA doesn't expose the port for node-red-contrib-google-smarthome directly, it might expose the port of the reverse proxy. The proxy could forward connections to node-red-contrib-google-smarthome then. There's an [HA addon for Caddy](https://github.com/einschmidt/addon-caddy-2). And we have a [tutorial on how to use Caddy](https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/docs/caddy.md) as a reverse proxy in front of node-red-contrib-google-smarthome. The tutorial is not written for HA. But it might be a starting point.
