### ISSUE TITLE
GoogleSmartHomeNode(constructor): error {"errno":-21,"syscall":"read","code":"EISDIR"}

### ISSUE THREAD

**Issue by homefefeld** [mikejac/node-red-contrib-google-smarthome#299]
Hi There, 
IT has been a very long time.
Everything was working fine until I upgraded node.
I now get new errors in the log 
**GoogleSmartHomeNode(constructor): error {"errno":-21,"syscall":"read","code":"EISDIR"}
- [error] Error: EISDIR: illegal operation on a directory, read**
and 
**
- [error] HttpActions:reportState(): http server is not running
**

Any help would be greatly appreciated.

**Comment by Caprico85** [comment]
There seems to be something when Node-RED tries to access your files.

Does Node-RED's user directory (the directory where your settings.js, flows.json etc. are) exist? Are permissions and owner of this directory correct?

Are there files like `google-smarthome-auth-*.json` in this directory? Are their permissions and owner correct?

What JWT key filename have you set in your config? If it is an absolute path: Does the file exist, are its permissions and owner correct? If it is a relative path or only the filename: Does the file exist and is it located in Node-RED's user directory? Are its permissions and owner correct?
    ![image](https://user-images.githubusercontent.com/2081806/178267418-27084fc4-ff89-462c-a8a8-130f9158cfeb.png)

**Comment by Caprico85** [comment]
Closing this now. Feel free to reopen if neccessary.
