### ISSUE TITLE
Cannot find in node-red palettes

### ISSUE THREAD

**Issue by purebenwoo** [mikejac/node-red-contrib-google-smarthome#3]
Hi,

I've been looking for something like this for a month!!! Unfortunately, I can't seem to see it on my palettes to install. Can you advise please?

Thanks in advance.

ben

**Comment by rajendranponnappan** [comment]
Yes you can not find it  in the palettes to install  however you install if you follow the instruction given as below.

To install - change to your Node-RED user directory.

    cd ~/.node-red
    npm install node-red-contrib-google-smarthome

Thanks,
Raj

**Comment by mikejac** [comment]
@rajendranponnappan is correct. Also remember to restart Node-RED after installation.

/michael

**Comment by purebenwoo** [comment]
Thank you all.
On 2/27/2019 5:59:36 AM, Michael Jacobsen <notifications@github.com> wrote:
@rajendranponnappan [https://github.com/rajendranponnappan] is correct. Also remember to restart Node-RED after installation.
/michael
