### ISSUE TITLE
Can not connect Home App to node-red-contrib-google-smarthome

### ISSUE THREAD

**Issue by uklatt** [mikejac/node-red-contrib-google-smarthome#309]
Hello,

I successfully installed node-red (3.0.2) and node-red-contrib-google-smarthome (0.3.9) and set everything up as described in the documentation. I use node-red on the same machine as the webserver.

I can reach https://mydomain.com:1880/check and https://mydomain.com:1880/oauth from Browser over internet but not
https://mydomain.com:1880/smarthome
What could be the reason?

Google Home App can also not find the service.

When I fill the "check" URL with the credentials I get the following:
![Bild2](https://user-images.githubusercontent.com/42005666/183421943-932cffa3-a1ff-47fe-b12b-1b16390e0a09.png)

Uwe

**Comment by Caprico85** [comment]
Hallo Uwe,

> I can reach https://mydomain.com:1880/check and https://mydomain.com:1880/oauth from Browser over internet but not
> https://mydomain.com:1880/smarthome

What do you mean you cannot reach https://mydomain.com:1880/smarthome? If you get the message `Cannot GET /smarthome` that's okay. /smarthome only responds to POST requests. You can use a service like reqbin.com send a POST request. If done correctly, it will answer with status 401 and error message `missing inputs`.
![image](https://user-images.githubusercontent.com/2081806/183466355-f4706466-dd39-4d34-b218-3d21d8d2348f.png)

<br>

The error message from the /check page also indicates there is something wrong with POST requests. The mentioned line tries to read client_id from a POST request sent to /oauth.

You could try reqbin.com to send a POST request to https://mydomain.com:1880/oauth. Select POST and on the content tab add a variable client_id. It should answer with `client_id xxx invalid`. If done with your real client id it will answer with `redirect_uri undefined invalid`.
![image](https://user-images.githubusercontent.com/2081806/183470340-9717c1bd-e825-4b8a-99cd-8ca7efd7149f.png)

Any other message may mean there is something wrong with POST requests. A reverse proxy or security software altering or blocking POST maybe?


Caprico

**Comment by uklatt** [comment]
Hi Caprico,

If I use reqbin.com:

https://mydomain.com:1880/smarthome POST reports Status 401 "missing inputs" (as it should)

https://mydomain.com:1880/oauth with JSON POST {"client_id":"12345"} reports Status 500:

`TypeError: Cannot read property &#39;client_id&#39; of undefined<br> &nbsp; &nbsp;at /root/.node-red/node_modules/node-red-contrib-google-smarthome/lib/HttpAuth.js:98:92<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:144:13)<br> &nbsp; &nbsp;at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:114:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:284:15<br> &nbsp; &nbsp;at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at expressInit (/usr/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
`

I have no proxy or firewall software running. Only a debian buster with Apache 2 and two virtual hosts and lets encrypt certificates. I use the same certificates for node-red settings.js. The node-red port 1880 is directly reachable and I have set the "Local Fulfillment Port" to 11080.

Uwe

**Comment by clysss** [comment]
Hello,
I had exactly the same issue. Thanks to uklatt who point the httpAdminRoot difference, I manage the error :
 as I mandatory had to keep my httpAdminRoot in settings.js (in my case /xxxxxAdmin), I change in smartnode client node the WEB SERVER PATH to /xxxxxAdmin 
 => http://mywebsite/xxxxxAdmin/check is now OK
**so there is effectively a issue with paths when httpAdminRoot is configured**

**Comment by meh301** [comment]
I am trying to get this to work with httpadminroot (set as /admin) and set the path to /admin as @clysss stated which solved the token undefined issue but now I am getting stuck at oauth redirect after successful authentication for which I get the following error: "HttpAuth:httpAuthRegister(POST /oauth): redirect_uri undefined invalid". It seems that it is ignoring the /admin path?

![image](https://user-images.githubusercontent.com/1178712/215439985-74a8b16c-97ce-451b-bfef-97b059fd0af2.png)
