### ISSUE TITLE
Receive voice command in node-red

### ISSUE THREAD

**Issue by uklatt** [mikejac/node-red-contrib-google-smarthome#311]
Hallo,

I am a litten bit lost.
How can I receive a Google Home Mini voice command in node-red?

Can somebody point me to a documentation or howto for this?

Uwe

**Comment by Caprico85** [comment]
I agree, the docs on how to setup a device are a little bit "thin" in the moment.

After you successfully linking your account, probybly the easiest way would be to start with the example. From Node-RED's menu, chosse "Import", then import the "Dimmable light" example.

![image](https://user-images.githubusercontent.com/2081806/183714700-f6126981-f29b-4032-bf37-d41f83d1cec6.png)

Place it anywhere on a flow. Open the configuration of the "Light table lamp" node.

![image](https://user-images.githubusercontent.com/2081806/183715240-7d0c79d4-450d-4ede-b7ed-569f6f006de2.png)

Select your config in the select box. You can also give your device a better name.

![image](https://user-images.githubusercontent.com/2081806/183715652-1b2a91d0-3bef-4b99-a175-35a2b197c1cb.png)

For now, leave all other fields as is. Deploy your flow.

If you open your Google Home App, you should already see your new device. If not, say "Hey Google, sync my devices".

Say "Hey Google, switch the table lamp on" or control your device in the app. In Node-RED's debug panel you should see the messages from your device.

![image](https://user-images.githubusercontent.com/2081806/183717837-80b0e1d4-fde5-4f9d-b8f3-711256d1a61c.png)

Now you only need to handle these messages and control your physical device accordingly.

On the input side of the device node, you can send in the current state of your device. This is not neccessary. But it helps to show the state of your device in the app. For example, if you switch off your device via its physical light switch, Google would not know about it and still show it as on.

![image](https://user-images.githubusercontent.com/2081806/183721273-3698c357-5fc0-40f2-bc31-d4171a7bcedb.png)

Now you can reconfigure your device or add new devices. Every device has a device type and one or multiple traits. Traits are the abilities of your device. For example, there are traits for On/Off, for Open/Close, for setting the temperature and so on.

![image](https://user-images.githubusercontent.com/2081806/183722128-8fa56719-de4c-49eb-b017-b6c0750550c7.png)

**Comment by uklatt** [comment]
Hi Caprico,

this helps to add a new device. Thank you.
But my main question is: Can I use a device to receive all voice commands with an additional text component?

For example: I say "OK Google Kommando irgendeintext"
I want to receive "Kommando irgeneintext" or at least "irgendeintext" in node-red an do something with it.

Because Google changes the ITTT API, its not possible from end of august 2022 to receive commands with text components or numbers.

I want to replace ITTT with node-red and node-red-contrib-google-smarthome.

Uwe

**Comment by Caprico85** [comment]
Unfortunately, no. Google Smarthome only supports controlling devices.

You can partially work around this using scenes. Scenes are activated using "Hey Google, activate >scene name<" (or maybe even "Hey Google, >scene name<"? Never tried it). Scenes have a fixed name though. They can't have variable components like numbers (except if you create hundreds of scenes for every possible number).

For real free-style commands you would have to build a custom action. There were projects like node-red-contrib-googlehome-actions-v2, node-red-contrib-actions-google, node-red-contrib-google-action-dialogflow, node-red-contrib-google-action-dialogflow-http or node-red-contrib-gactions-fulfillment implementing this. I never used them, I don't know if they still work and I don't know if they really do what you want.

As far as I remember, those custom actions also require you to say "Hey Google, tell >my action< to >do something<". You can't simply say "Hey Google, >do something<". I don't know how IFTTT achieved those completely custom commands without any prefix and if that's still possible at all.

**Comment by uklatt** [comment]
Thank You for your help.
So I need to search for a working solution.

Uwe

**Comment by Paul-Reed** [comment]
What is your 'user case' for this?
If we know the reason why you want this feature, we may be able to suggest an alternative solution.

**Comment by uklatt** [comment]
Hi Paul,

I use ioBroker as home automation software and ITTT to send Google voice commands to my own Javascripts. Then my AV system is controlled with this commands. Now I am searching for a ITTT replacement.

Uwe

**Comment by Paul-Reed** [comment]
Can't you use smarthome to interact with your JavaScripts?
Smarthome has lots of AV device types and traits.

**Comment by uklatt** [comment]
Hi Paul,

I want to use voice commands with a Google Home mini. 

Uwe

**Comment by uklatt** [comment]
Hi Paul,

I don't wann to use many node-red devices. 
My need is one device that receives all voice commands.

Uwe

**Comment by Paul-Reed** [comment]
I don't think Google works like that, it uses pre-defined devices and traits.
But good luck!

**Comment by Caprico85** [comment]
You wouldn't need lot's of different devices. You would only need one device, to which you would add different traits.

Now it depends if the traits fulfill what you want. There are traits for [switching on and off](https://developers.google.com/assistant/smarthome/traits/onoff), for [controlling the volume](https://developers.google.com/assistant/smarthome/traits/volume) or for [switching channels](https://developers.google.com/assistant/smarthome/traits/channel). But there are no traits (that I know of) for recording stuff. And there is no way with node-red-contrib-google-smarthome to define a custom command.

**Comment by FireWizard52** [comment]
Hello @uklatt,

I hope, that it is clear to you from the previous posts, that `node-red-contrib-smarthome` and `Google Home` is not able to relay "spoken text" from your Google Home Mini to a node in Node Red. So you will never receive a "written text" in any node in Node Red.

`node-red-contrib-smarthome`, and also others, like SmartNora, are designed to control various devices in your smart home.

You said:

> Then my AV system is controlled with this commands

Node-red with the `node-red-contrib-smarthome` node installed is very well capable of controlling such a AV system directly, even without your Java scripts. Perhaps you need some adaption in a Function node (with JavaScript). That depends on tour AV System.
See: https://developers.google.com/assistant/smarthome/guides/audiovideoreceiver

The only thing you might miss is something like song/artist selection or a playlist. For these things you can buy a Google ChromeCast and take a Spotify Premium account.

**Comment by uklatt** [comment]
I have solved this problem with the device "scene".
Unfortunately I need to create an individual scene for every command, but better than nothing ;-)

Uwe
