### ISSUE TITLE
Internal Error Encountered

### ISSUE THREAD

**Issue by lyntonjjr** [mikejac/node-red-contrib-google-smarthome#313]
I've been using this integration for a few weeks now and it's been working flawlessly.  Last night, all devices went offline in Google Home and the following error is coming up in the nodered logs.

`POST /smarthome 200 2.587 ms - 718
{"msg":"Error in HttpActions:requestSync()","org_msg":{"code":500,"message":"Internal error encountered.","errors":[{"message":"Internal error encountered.","domain":"global","reason":"backendError"}],"status":"INTERNAL"},"data":{"postData":{"agentUserId":"0"}}}`

Not much to go on I know, but has anyone seen this before?

**Comment by Caprico85** [comment]
Sorry for the late reply. In case you haven't got it fixed already:

- I guess "Hey Google, sync my devices" doesn't work?
- Does unlinking and relinking your account help?
- Do the Google Cloud Logs https://console.cloud.google.com/logs/query say anything helpful? Especially after syncing your devices or relinking your account.

I did see internal server errors before. Unfortunately I couldn't track it down to a specific reason. Somehow it always fixed itself after a while or after restarting or relinking.

**Comment by Caprico85** [comment]
Closing due to inactivitiy. Feel free to reopen.
