### ISSUE TITLE
Thermostat temperaturesetting controls not available in Google Home app 

### ISSUE THREAD

**Issue by LocutusOfB0rg** [mikejac/node-red-contrib-google-smarthome#323]
While the voice control allows to change thermostat temperature settings, it's impossible to change anything in the Google Home app

![image](https://user-images.githubusercontent.com/87582907/193012869-91dc2475-3a4e-46ac-8ce3-a17698e0b796.png)

I've checked the requests in node-red logging and stumbled upon a post on stackoverflow which had a similar issue.

This is what's being sent as sync:

HttpActions:reportState(): successfully reported state to Google: {"requestId":"123456789","agentUserId":"0","payload":{"devices":{"states":{"321456987":{"online":true,"thermostatMode":"auto","thermostatTemperatureAmbient":22,"thermostatTemperatureSetpoint":19}}}}}

https://stackoverflow.com/questions/64075280/google-smart-home-actions-for-thermostat-report-state-issue
https://developers.google.com/assistant/smarthome/develop/touch-controls#google_home_app
https://developers.google.com/assistant/smarthome/traits/temperaturesetting

According to those posts, if I'm not mistaken of course, that state report needs an additional set of attributes to be sent in case me.trait.temperaturesetting equals true:

"thermostatTemperatureRange" : {"minThresholdCelsius": 10, "maxThresholdCelsius" :30 }

**Comment by LocutusOfB0rg** [comment]
And probably also "thermostatTemperatureUnit"

**Comment by Caprico85** [comment]
> HttpActions:reportState(): successfully reported state to Google: {"requestId":"123456789","agentUserId":"0","payload":{"devices":{"states":{"321456987":{"online":true,"thermostatMode":"auto","thermostatTemperatureAmbient":22,"thermostatTemperatureSetpoint":19}}}}}

What you posted is a request from reportState(). Reportings requests happen when the temperature on your thermostat is changed and informs Google about the updated temperatures.

minThresholdCelsius, maxThresholdCelsius and thermostatTemperatureUnit on the other hand are part of the sync request. A sync requests is sent when you restart Node-RED, redeploy your flows or say "Hey Google, sync my devices". Sync requests tell Google what devices you have and what their abilities are. 

Sync requests actually contain minThresholdCelsius, maxThresholdCelsius and thermostatTemperatureUnit (if the thermostat is configured correctly):

```json
{
  "requestId": "...",
  "payload": {
    "agentUserId": "0",
    "devices": [
      {
        "type": "action.devices.types.BED",
        "traits": [
          "action.devices.traits.Modes",
          "action.devices.traits.TemperatureSetting"
        ],
        "name": {
          "defaultNames": [
            "Node-RED Bed"
          ],
          "name": "Bett",
          "nicknames": []
        },
        "roomHint": "Wohnzimmer",
        "willReportState": true,
        "notificationSupportedByAgent": false,
        "attributes": {
          "availableModes": [],
          "commandOnlyModes": false,
          "queryOnlyModes": false,
          "availableThermostatModes": [],
          "thermostatTemperatureRange": {
            "minThresholdCelsius": 10,
            "maxThresholdCelsius": 40
          },
          // HERE
          "thermostatTemperatureUnit": "C",
          "bufferRangeCelsius": 2,
          "commandOnlyTemperatureSetting": false,
          "queryOnlyTemperatureSetting": false
        },
        "deviceInfo": {
          "manufacturer": "Node-RED",
          "model": "nr-device-bed-v1",
          "swVersion": "1.0",
          "hwVersion": "1.0"
        },
        "otherDeviceIds": [
          {
            "deviceId": "..."
          }
        ],
        "customData": {
          "httpPort": 9999,
          "httpPathPrefix": "/",
          "clientId": "...",
          "accessToken": "..."
        },
        "id": "..."
      }
    ]
  }
}
```

My thermostat is configured like this:

![image](https://user-images.githubusercontent.com/2081806/193070401-ee299efe-5277-4b3d-a6b2-351e663aaa86.png)

Before I was able to change the temperature in the app, I had to press that button below to set it to heating mode. After that it worked:

![image](https://user-images.githubusercontent.com/2081806/193076376-a0e0b732-8ce3-4269-b884-262a0ca24150.png)

**Comment by FireWizard52** [comment]
Hi @LocutusOfB0rg

You wrote:

> While the voice control allows to change thermostat temperature settings, it's impossible to change anything in the Google Home app

As I look to your screenshot of the Google Home app, I see that your thermostat in the Living has been set to Auto(matic) mode.
In this case the temperature  setting of your thermostat has been preprogrammed in your thermostat andyou arenot able to change the temperature setting from your Google Home app.

If you want to change the settin, you have to changeit to "Manual" mode.
You can do that as follows:

![Screenshot_20220929-185212](https://user-images.githubusercontent.com/46283323/193097900-675cc7e8-7795-4622-9b22-b255f610def9.png)

Press the "square" button under the temperature indication, as in the screenshot, presented by @Caprico85. indicated by a red arrow.

A menu will pop-up and you can select the mode, you want. See beow

![Screenshot_20220929-185301](https://user-images.githubusercontent.com/46283323/193099359-e96e629a-90e8-4f5b-afb7-05ee90254255.png)

You should configure your thermostat node, according to the capabilities of your hardware device (thermostat)

Regards

**Comment by LocutusOfB0rg** [comment]
Many thanks for the help @FireWizard52 @Caprico85 !

Besides auto and off, I also added "heat", and now I can change the temperature as shown in the screenshots by Firewizard
