### ISSUE TITLE
Error in HttpActions: requestSync()

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#326]
Hi,

This is a long time issue and not a recent failure. It is not a real problem and everything functions as normal.

After every restart of Node-RED (required if nodes are upgraded), I receive the following error message from the googlesmarthome-client node.

![Screenshot_Google_Home_error](https://user-images.githubusercontent.com/46283323/195094160-af9d5a82-fa88-4df3-89e4-82cbab136396.png)

If I check code 429 (https://developers.google.com/assistant/smarthome/develop/request-sync) I read:

> 429 - Failure: Maximum number of concurrent sync requests has been exceeded for the given agentUserId. A caller may only issue one concurrent sync request unless the async flag is set to true. 

As said, it is not a real problem, but I don't think that I can set the async flag somewhere.

**Comment by Caprico85** [comment]
I never had this problem. On the other hand, just to be sure, setting the async flag shouldn't hurt.

The async flag would have to be added in lib/HttpActions.js, line 706, in the block `postData`:

```js
        const postData = {
            agentUserId: userId,
            async: true,           // <-- here
        };
```

I'll release a new version with the async flag soon.

**Comment by FireWizard52** [comment]
Hello @Caprico85,

I modified the lib/HttpActions.js file and added the line `async: true,`
After restarting Node-RED the previous error did not appear and also other unexpected behavior did not occur.

The fact, that you never had this problem, could be related to the number of devices, you have in use with Google Home.
I discussed it also with @Paul-Reed and to him this error message was also unknown. He used 8 devices, while I'm using approx. 40 devices. (Lights, Switches, Security device, Sensors) How may do you use?

Regards and thanks for giving me the indication on how to solve.

**Comment by Caprico85** [comment]
Hi @FireWizard52,

the setup in my parents apartment has 10 devices, my own setup has 4.

I'm not sure if it really is related to the number of devices. The problem occurs during requestSync(). This only sends a signal to Google, saying that there might be new devices. Google then calls our API later to do the actual sync. The actual sync process may take longer with more devices, but not the requestSync call.

I'm wondering how you get two concurrent calls at all. During startup, this module only does a single call. I have no idea where your second call comes from. Do you have multiple management nodes? Or do you automatically send a request_sync message into your management node on startup?

**Comment by FireWizard52** [comment]
Hi @Caprico85 

You wrote:

> I'm not sure if it really is related to the number of devices. The problem occurs during requestSync(). This only sends a signal to Google, saying that there might be new devices. Google then calls our API later to do the actual sync. The actual sync process may take longer with more devices, but not the requestSync call.

Thanks for your explanation. This makes it again clearer to understand, what is happening.

> Do you have multiple management nodes?

No, I have only one.

> Or do you automatically send a request_sync message into your management node on startup?

That is it. 

I have connected an "Inject" node, with the topic `request_sync`, to the Management node and of course after a restart of Node-RED this is injected in the Management node and then together with the Sync Request from the Management node, you will have 2 concurrent requests. 

Never realized that.

Do you suggest to remove the recent patch?  I has no negative effect, as far as I can see now.

Regards

**Comment by Caprico85** [comment]
Hi @FireWizard52 

> Do you suggest to remove the recent patch? It has no negative effect, as far as I can see now.

No, I wouldn't remove it. There may be other people having the same problem. As far as I understand, it may even make the startup process a little bit faster if the requestSync request happens asynchronously. So, thank you for pointing me to this performance improvement 😄

Regards
