### ISSUE TITLE
Notification from Smoke detector

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#327]
Hi all,

As Smoke alarms (Smoke detectors) are mandatory in many countries, it is a good idea to use an announcement to your Google Home speakers in case smoke has been detected.

It is rather difficult to find in the Google documentation on how the payload should look like.
In fact. it is an addition to (closed) #153.
Please find below an example on how to send a notification to your Google speaker in case smoke has been detected.

`[{"id":"b89c356b30f2a00e","type":"google-device","z":"1797c1fc2aa93477","client":"d7ec4b2f72adc483","name":"Rookmelder","nicknames":"Smoke Alarm","topic":"","room_hint":"Test","device_type":"SMOKE_DETECTOR","trait_appselector":false,"trait_channel":false,"trait_inputselector":false,"trait_mediastate":false,"trait_onoff":false,"trait_transportcontrol":false,"trait_modes":false,"trait_volume":false,"trait_toggles":false,"trait_brightness":false,"trait_colorsetting":false,"appselector_file":"applications_<id>.json","appselector_type":"str","channel_file":"channels_<id>.json","channel_type":"str","inputselector_file":"inputs_<id>.json","inputselector_type":"str","command_only_input_selector":false,"ordered_inputs":false,"support_activity_state":false,"support_playback_state":false,"command_query_onoff":"","supported_commands":["CAPTION_CONTROL","NEXT","PAUSE","PREVIOUS","RESUME","SEEK_RELATIVE","SEEK_TO_POSITION","SET_REPEAT","SHUFFLE","STOP"],"volume_max_level":100,"volume_can_mute_and_unmute":true,"volume_default_percentage":40,"level_step_size":1,"command_only_volume":false,"command_only_brightness":false,"command_only_colorsetting":false,"color_model":"temp","temperature_min_k":2000,"temperature_max_k":9000,"modes_file":"modes_<id>.json","modes_type":"str","command_query_modes":"","toggles_file":"toggles_<id>.json","toggles_type":"str","command_query_toggles":"","trait_camerastream":false,"hls":"","hls_app_id":"","dash":"","dash_app_id":"","smooth_stream":"","smooth_stream_app_id":"","progressive_mp4":"","progressive_mp4_app_id":"","webrtc":"","webrtc_offer":"","webrtc_ice_servers":"","webrtc_ice_servers_type":"str","auth_token":"","passthru":false,"persistent_state":true,"trait_scene":false,"scene_reversible":true,"trait_timer":false,"trait_temperaturesetting":false,"max_timer_limit_sec":86400,"command_only_timer":false,"available_thermostat_modes":["off","heat","cool","on","heatcool","auto","fan-only","purifier","eco","dry"],"min_threshold_celsius":0,"max_threshold_celsius":40,"thermostat_temperature_unit":"C","buffer_range_celsius":2,"command_query_temperaturesetting":"","trait_temperaturecontrol":false,"tc_min_threshold_celsius":0,"tc_max_threshold_celsius":40,"tc_temperature_step_celsius":1,"tc_temperature_unit_for_ux":"C","tc_command_query_temperaturecontrol":"","trait_humiditysetting":false,"min_percent":0,"max_percent":100,"command_query_humiditysetting":"","trait_dock":false,"trait_locator":false,"trait_lockunlock":false,"trait_reboot":false,"trait_openclose":false,"discrete_only_openclose":false,"open_direction":[],"command_query_openclose":"","trait_startstop":false,"pausable":false,"available_zones":[],"trait_runcycle":false,"trait_softwareupdate":false,"trait_rotation":false,"supports_degrees":true,"supports_percent":true,"rotation_degrees_min":0,"rotation_degrees_max":360,"supports_continuous_rotation":false,"command_only_rotation":false,"trait_lighteffects":false,"default_sleep_duration":1800,"default_wake_duration":1800,"supported_effects":["colorLoop","sleep","wake"],"trait_statusreport":false,"trait_cook":false,"supported_cooking_modes":[],"food_presets_file":"foodPresets_<id>.json","food_presets_type":"str","trait_fanspeed":false,"reversible":false,"supports_fan_speed_percent":false,"fan_speeds_ordered":false,"command_only_fanspeed":false,"available_fan_speeds_file":"availableFanSpeeds_<id>.json","available_fan_speeds_type":"str","trait_sensorstate":true,"sensor_states_supported":["SmokeLevel"],"arm_levels_ordered":false,"trait_fill":false,"available_fill_levels_file":"availableFillLevels_<id>.json","available_fill_levels_type":"str","supports_fill_percent":false,"ordered_fill_levels":true,"trait_armdisarm":false,"available_arm_levels_file":"availableArmLevels_<id>.json","available_arm_levels_type":"str","trait_energystorage":false,"is_rechargeable":false,"query_only_energy_storage":false,"energy_storage_distance_unit_for_ux":"","trait_dispense":false,"supported_dispense_items_file":"supportedDispenseItems_<id>.json","supported_dispense_items_type":"str","supported_dispense_presets_file":"supportedDispensePresets_<id>.json","supported_dispense_presets_type":"str","trait_networkcontrol":false,"supports_enabling_guest_network":false,"supports_disabling_guest_network":false,"supports_getting_guest_network_password":false,"network_profiles":[],"supports_enabling_network_profile":false,"supports_disabling_network_profile":false,"supports_network_download_speedtest":false,"supports_network_upload_speedtest":false,"trait_objectdetection":false,"show_trait":"selected","advanced_settings":true,"ct_appselector":"","ct_armdisarm":"","ct_brightness":"","ct_camerastream":"","ct_channel":"","ct_colorsetting":"","ct_cook":"","ct_dispense":"","ct_dock":"","ct_energystorage":"","ct_fanspeed":"","ct_fill":"","ct_humiditysetting":"","ct_inputselector":"","ct_lighteffects":"","ct_locator":"","ct_lockunlock":"","ct_mediastate":"","ct_modes":"","ct_networkcontrol":"","ct_objectdetection":"","ct_onoff":"","ct_openclose":"","ct_reboot":"","ct_rotation":"","ct_runcycle":"","ct_scene":"","ct_sensorstate":"","ct_softwareupdate":"","ct_startstop":"","ct_statusreport":"","ct_temperaturecontrol":"","ct_temperaturesetting":"","ct_timer":"","ct_toggles":"","ct_transportcontrol":"","ct_volume":"","pin_appselector":"","pin_armdisarm":"","pin_brightness":"","pin_camerastream":"","pin_channel":"","pin_colorsetting":"","pin_cook":"","pin_dispense":"","pin_dock":"","pin_energystorage":"","pin_fanspeed":"","pin_fill":"","pin_humiditysetting":"","pin_inputselector":"","pin_lighteffects":"","pin_locator":"","pin_lockunlock":"","pin_mediastate":"","pin_modes":"","pin_networkcontrol":"","pin_objectdetection":"","pin_onoff":"","pin_openclose":"","pin_reboot":"","pin_rotation":"","pin_runcycle":"","pin_scene":"","pin_sensorstate":"","pin_softwareupdate":"","pin_startstop":"","pin_statusreport":"","pin_temperaturecontrol":"","pin_temperaturesetting":"","pin_timer":"","pin_toggles":"","pin_transportcontrol":"","pin_volume":"","x":500,"y":3040,"wires":[[]]},{"id":"148aa41effefe119","type":"inject","z":"1797c1fc2aa93477","name":"Smoke","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"currentSensorStateData\":[{\"name\":\"SmokeLevel\",\"currentSensorState\":\"smoke detected\"}]}","payloadType":"json","x":270,"y":3040,"wires":[["b89c356b30f2a00e"]]},{"id":"6b7581b806fc2662","type":"inject","z":"1797c1fc2aa93477","name":"No Smoke","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"currentSensorStateData\":[{\"name\":\"SmokeLevel\",\"currentSensorState\":\"no smoke detected\"}]}","payloadType":"json","x":260,"y":3080,"wires":[["b89c356b30f2a00e"]]},{"id":"17794bef0894967a","type":"inject","z":"1797c1fc2aa93477","name":"Smoke Notification","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"SensorState","payload":"{\"name\":\"SmokeLevel\",\"priority\":0,\"currentSensorState\":\"smoke detected\"}","payloadType":"json","x":230,"y":3000,"wires":[["b89c356b30f2a00e"]]},{"id":"d7ec4b2f72adc483","type":"googlesmarthome-client","name":"Jonas","enabledebug":false,"default_lang":"en","usegooglelogin":true,"usehttpnoderoot":false,"port":"3001","httppath":"","ssloffload":false,"localport":"18080","accesstokenduration":"60","reportinterval":"60","request_sync_delay":"2","set_state_delay":"2"}]`

**Comment by Paul-Reed** [comment]
Probably worth mentioning that 'Voice Notifications' must be set to 'On' in the google 'Home' app, for announcements to be made by the example above.

![smoke](https://user-images.githubusercontent.com/973580/195934079-ea88cb7e-d832-46a0-a611-333814b67e40.png)

**Comment by FireWizard52** [comment]
@Paul-Reed,

You are right but this information you could find in the documentation.
I just wanted to share the payload for controlling a notification from a smoke detector.

This information is not available.

Initially I wanted to add this information to #153, but in that case nobody would noted that, as this thread has been closed

If I read your issue in #153 I noticed that to get a Notification from a Doorbell, you had a lot  of try and error.
First a bug had to be solved and then you had to find the proper payload.

In the README file at: https://flows.nodered.org/node/node-red-contrib-google-smarthome#sending-spoken-notifications
you will see that for a proactive notification a lot of things has to be done. (Google Homegraph, etc). But this is not the case.

If you go to Object Detection (https://developers.google.com/assistant/smarthome/traits/objectdetection)  you might expect that you have to send something as:

```
{
  "ObjectDetection": {
    "objects": {
      "named": [
        "Alice"
      ]
    },
    "priority": 0,
    "detectionTimestamp": 946684800000
  }
}
```
But it is much simpler, as you have discovered.

Use ObjectDetection as topic and only as payload:

```
 {
      "named": 
        "Alice"
 },
```

For a smoke detector it is some thing similar.

SensorState as topic and as payload:

```
{
    "priority": 0,
    "name": "SmokeLevel",
    "currentSensorState": "smoke detected"
  }

```
"priority": 0 is obviously optional.

But you cannot copy the sample from https://developers.google.com/assistant/smarthome/traits/sensorstate

This brings me to my last remark:

There is still an open issue (#143), where this kind of information should go.
This will improve this piece of software tremendously..
Also the text that has to be used in case of query can go in there. It took me a lot of time and try and error, to query the smoke detector sensor and got returned the correct answer.

**Comment by Paul-Reed** [comment]
@FireWizard52 Yes, it would be good to add this to the examples folder - https://github.com/mikejac/node-red-contrib-google-smarthome/tree/master/examples

I thought I'd mention 'enabling voice notifications ' here because many users may just load up your example, and without reading the docs just conclude -  "huh, it doesn't work!!"

**Comment by FireWizard52** [comment]
Hi @Paul-Reed 

Paul, you are right. I also forgot to enable notifications, when I made a test device in order to test it.

I will add the smoke detector to the  examples.
Perhaps it is also nice to add the doorbell, but then not with a person (Alice), but just a unknown person.

Not all people have a doorbell with camera and face recognition, Do you have one?

Regards

**Comment by Paul-Reed** [comment]
No, but I wish!!

**Comment by FireWizard52** [comment]
I saw that @Caprico85 has added a folder "Spoken Notifications" to the "examples" folder.
I had actually planned to do the same,

So thank you, @Caprico85

**Comment by Caprico85** [comment]
Thank you @FireWizard52. I took your example and added it as an example. I also added an example for RunCycle (washing machines and the like).

> Perhaps it is also nice to add the doorbell, but then not with a person (Alice), but just a unknown person.

The example for doorbells already had two input nodes. One for Alice, one for 2 unknown people.

> I thought I'd mention 'enabling voice notifications ' here because many users may just load up your example, and without reading the docs just conclude - "huh, it doesn't work!!"

I also added a comment node to the example flows, reminding people to enable notifications.
