### ISSUE TITLE
Incoming messages filter

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#329]
Hi,

The latest version, released October 15, 2022, contains a new feature, called "Incoming messages filter".
The explanation is as follows:

> If enabled, incoming messages will managed only if the message topic starts with the node topic.

Users will only see one field with "topic" which is indicated as "Out topic"

![Setting_topic_Google_Home](https://user-images.githubusercontent.com/46283323/196040755-0b732b5c-df8e-4c64-b5d4-2d962b8f7960.png)

In my opinion it is not clear that the "node" topic is the same as the "Out" topic.

By default this feature is enabled. I'm not sure that every user has used this function before and many flows might fail.

Your opinion?

Regards and thanks for the good work.

**Comment by FireWizard52** [comment]
Additional.

I use the topic to be a number. This will fail, as you use the type checking for a string.
I had this discussion before:

https://github.com/andrei-tatar/node-red-contrib-smartnora/issues/64

Think about it.

**Comment by ckhmer1** [comment]
Hi, 
Really the default value is false, unfortunately node-red shows it as selected in the GUI if no previous value is specified ( I think it is a node-red bug).
The node logic instead use the false value if no value is specified, so no filter is applied to the messages.

**Comment by Caprico85** [comment]
I think it was because the checkbox was marked as "checked" in device.html. Fixed that in v0.3.13. Neither new nor existing devices get the checkbox pre-checked now.

![image](https://user-images.githubusercontent.com/2081806/196056956-d493bf4d-a972-4de9-bbd4-a2d3b4bd4935.png)

v0.3.13 also fixes numeric topics.

**Comment by FireWizard52** [comment]
Thanks @Caprico85  and @ckhmer1,

It were only small things and I was aware of these things so it didn' t hurt me.
I also suggest that you change "node" topic to "Out" topic.
It will make it clearer for a lot of users.

Good work.

Regards

**Comment by Paul-Reed** [comment]
I'm not sure what the real benefit is of this change, as the topic is already committed for incoming messages. For example, enabling the filter stops flows where the msg.topic is already in use.
```
{
"payload":25,
"topic":"brightness"
}
```

**Comment by FireWizard52** [comment]
Hello Paul,

You wrote:

> I'm not sure what the real benefit is of this change, as the topic is already committed for incoming messages.

The benefit is dependent on your flow. The best way is to illustrate this with an example

See (a part of) my flow for controlling some Lights (On/Off type in this case).

![Screenshot_Example_Filter_IDX](https://user-images.githubusercontent.com/46283323/196153037-b6ba1c5c-9736-4332-94cc-db2f975779b7.png)

Unless you only control your devices with the voice command of your Google Home speaker or you use the Google Home app, the Google-Smarthome devices gets also status information (On/Off) from an external source. In my case I have also Domoticz installed and Domoticz sends the status information by MQTT. You probably remember I have approx 40 devices installed, among them 13 On/Off devices. In Domoticz the index (idx) number is important and this number informs you about the device that has been switched On or Off. Also a Domoticz MQTT out node contains the idx, in order to switch the correct light.

Before this new version I have to use a "Switch" node (Or, as I use this, a contrib-filter node, called Filter IDX) to split the various indexes to the correct google-smarthome device node. And the more lights you have the bigger this node becomes.

The "Topic Out" selection existed already in the Device node and I use that to control the correct devices in Domoticz.

I use this specific for Domoticz, but in maybe used for other external inputs as well, like Shelly or ZWave devices.
Especially useful i case you have multiple similar devices.

You also wrote:

> For example, enabling the filter stops flows where the msg.topic is already in use.

This is correct and therefore it is important that this functionality is disabled by default, so that users can selectively use it, if needed. In my case I can remove a really large Filter IDX node.. So I like it.

However there is still some room for improvement.

1. Use a different color then a green/red dot, if the data is coming from an external  because this may be mixed up with "Cloud fulfillment"
2. Use this data as well in case that a user switches a device to "On" or "Off", in case the device is already "On" or "Off".
Currently it is possible by voice to issue a command, while the action is already for filled.

I hope this explains a little, as I'm happy with the new functionality. I cleans up my workbench.

Regards

**Comment by Paul-Reed** [comment]
Thanks for the explanation 😊

**Comment by ckhmer1** [comment]
> some

Hi @Caprico85 ,
should we rename the field "Out Topic" to "Topic" or change the help explanation?
I prefer the former solution. What do You think about it?

**Comment by Paul-Reed** [comment]
Yes, I was thinking the same, as it would help make things easier to understand.

**Comment by FireWizard52** [comment]
Agree, the solution you choose, doesn't matter, but the help text should match with the field text.
