### ISSUE TITLE
Information about Google Server country location

### ISSUE THREAD

**Issue by MuadDibVV** [mikejac/node-red-contrib-google-smarthome#332]
Hello,

  Is anyone have information about the Google Server country location from which arrive the flow ? I want to secure my installation with a country location filter but I always block the flow when using the list of Google datacenters country location in Europe and north america...

Thanks

**Comment by FireWizard52** [comment]
Hi,

This  is what Stackoverflow tells you:

https://stackoverflow.com/questions/69359823/how-do-we-find-out-the-google-smart-home-action-data-server-location

Perhaps it will help you.
