### ISSUE TITLE
Local fulfillment failing after X time

### ISSUE THREAD

**Issue by shme14** [mikejac/node-red-contrib-google-smarthome#339]
Currently on a fresh restart of node-red local fulfillment works great. After an undetermined amount of time it starts failing. If I ask my phone or any of my homes to "force local" and then ask it to turn off any lights the command fails. 

While in the failing state I can still issue the `curl -X POST http://192.168.1.50:13002/smarthome` command and receive `{"error":"missing inputs"}` (which means that it should still be working?) If I restart node red while it is in this state local fulfillment starts working fine again. 

It's a real bummer when it starts taking up to 5 seconds to toggle lights on and off. (Almost instant when local fulfillment is working)

What steps can I take to troubleshoot this further?

**Comment by Caprico85** [comment]
For me, local fulfillment works. So it does not seems to be a general problem.

> While in the failing state I can still issue the `curl -X POST http://192.168.1.50:13002/smarthome` command and receive `{"error":"missing inputs"}` (which means that it should still be working?)

It means the local fulfillment port of Node-RED is still reachable, not necessarily local fulfillment still works. Maybe Node-RED is responding wrong or the app.js script is sending wrong data.

When you open chrome://inspect in Chrome, does it discover your smart speaker? Does it shpw any errors when you inspect your speaker?

**Comment by FireWizard52** [comment]
Just a few questions.

What version of Node RED are you using? And what version of "node-red-contrib-google-smarthome" do you use?
Is your app.js file updated in the Google's "Actions Console"? And does this app version match with the corresponding node version.

You said also:

> It's a real bummer when it starts taking up to 5 seconds to toggle lights on and off.

In my opinion 5seconds is quite long. In general I do not see such a long time, if "Cloud fulfillment" is used.
Perhaps it is a little bit slower than "Local fulfillment", but in my case not significant.

Do you have network problems" Slow network?

**Comment by shme14** [comment]
So the problem might have been that I was running version 1.3.4 of Node-Red. I updated it yesterday to 3.0.2 and so far local fulfillment has been staying online.

I will have to wait a few more days to confirm that the problem is actually fixed though as with 1.3.4 it would drop local fulfillment seemingly randomly after a few days of power on time. 


> In my opinion 5 seconds is quite long. In general I do not see such a long time, if "Cloud fulfillment" is used. Perhaps it is a little bit slower than "Local fulfillment", but in my case not significant.
> 
> Do you have network problems" Slow network?

I don't think it is my internet. It is typically rock solid. 1Gbps fiber. 

My theory is that the google home device would try to do local fulfillment first, times out, and then trys cloud fulfillment after. (That might be completely wrong though)

**Comment by Chrischi-** [comment]
I have exactly the same problem. After a few days / hours, no local fulfillment works anymore. In my case, the easiest way to restore is to power off a Google Assistant device. No matter which one I restart, it brings back local fulfillment immediately. Otherwise, I also have ~5-6 seconds for the command to execute. Completely disabling it also helps of course to get better speed.

I'm using the latest node-red-contrib-google-smarthome, app.js and NodeRed 3.0.2

I think the issue started sometime in the last 6-8 weeks. Only after that I switched to the latest versions without success.

**Comment by shme14** [comment]
@Chrischi- I have 3 Google Home Mini's and one regular Google home. All the old school ones from before they transitioned to nest.

**Comment by FireWizard52** [comment]
hello @shme14,

I checked your screenshot carefully and I saw a similar error (in red)  that I received in July this year (See #300)
The error is: Not Node Red Google Smarthome type. expected: 'nodered-google  got: 'hap'

I assume that your setting of MDNS service name is identical as shown in the screenshot in #300 and that there is not something like 'hap'

However this issue has been solved with a new version of 'app,js'

Does 'local fulfillment' still work for you after 2 days?

@Chrischi- 

Can you show a screenshot of your `chrome://inspect` console of one of your devices?

**Comment by shme14** [comment]
@FireWizard52 
My MDNS service name matches what the tutorial says it should be (https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/docs/local_fulfillment.md)

![](https://imgur.com/M0MPN0j)

Local fulfillment seems to still be working since Saturday night. 

I wonder if @Chrischi- 's solution of power cycling one of the homes will work and if my phone leaving the local WiFi network and coming back has the same effect. It's a possibility that this only happens when I don't leave the house for a while so my phone stays connected the whole time and nothing leaves the network or power cycles? If it goes down again I will first try power cycling my phone then power cycling a google home.

**Comment by Caprico85** [comment]
Closing this now as local fulfillment seems to be working again.
