### ISSUE TITLE
CameraStream implementation

### ISSUE THREAD

**Issue by FireWizard52** [mikejac/node-red-contrib-google-smarthome#342]
I investigated the possibility to activate a CameraStream and to display it on a Google Nest Hub in a more efficient way than I currently do. I configured a Device node as a Camera

After Configuration the node indicates unknown.  However you might expect that the device becomes visible in the 'Google SmartHome app' on the Smartphone.

However the node id is visible

![Screenshot_Google Home Camera node](https://user-images.githubusercontent.com/46283323/204348728-d287fc10-1632-4988-8449-54116365a518.png)

And it indicates "online".

![Screenshot_Google Home Camera node debug](https://user-images.githubusercontent.com/46283323/204349067-c5d3a53c-2337-4a86-b1ec-dda73fb95ec1.png)

Also with this node configured I get the following error.

![Screenshot_Google Home Camera node debug2](https://user-images.githubusercontent.com/46283323/204349649-b026cd27-e19f-4226-887c-3314bbf2d2de.png)

[Edit] This error will be sent each hour

I believe that this should be solved first, before I can test a stream

I tested also SmartNora Camera device and that works okay. However it does not display my CameraStream yet

Any suggestion to look at?

**Comment by ckhmer1** [comment]
Hi, 
if I've understood well, the urls should be HTTPS urls, and should be reachable from outside your private network, no private network IP.

Because You get the error message "Request entity was not found" the problem is inside the sync response. You should check in the google logs if there is some message allowing to understand the problem.

**Comment by FireWizard52** [comment]
Hi @ckhmer1, Claudio.

Thanks for your response.

You could be right, but I do not understand a few things.

1. https://developers.home.google.com/cloud-to-cloud/traits/camerastream shows e.g. for HLS as HTTP Live Streaming.
However the examples show everywhere https.

2. Testing with SmartNora creates a camera device in the Google Home app
Testing it, gives some activities in the Google Nest Hub, indicating that something should be shown,
However this is not the case. 

3. Using CATT (see: https://github.com/skorokithakis/catt) shows a nice stream to the Google Nest Hub,
This functionality is in use for a number of years.

In all cases I use http on my Local Lan, which is not accessible from the Internet.

I do understand that the camera should be accessible from the Internet, as it is stated that:
Note: CameraStream is not currently supported by local fulfillment.
I also can imagine that Google requires https and not http.

But why isn't a device created, while SmartNora does.

I do not have planned to make my camera's accessible from the Internet, butI will try to find a public cam and test with that.

**Comment by FireWizard52** [comment]
In addition to previous post.

Claudio asked,
> You should check in the google logs if there is some message allowing to understand the problem.

I checked the Google logs but no error indication from that Camera node.

**Comment by FireWizard52** [comment]
After updating to version 0.4.0. See procedure in #345 I noticed the following:

> However you might expect that the device becomes visible in the 'Google SmartHome app' on the Smartphone.

This device is now visible in the Google Home app. The hourly error message, as shown in my post 3 days ago, did not appear as well (so far)

So I will take a look to the Camera device, but first local fulfillment.
