### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by T1mey** [mikejac/node-red-contrib-google-smarthome#352]
Hi,

since today I have some problems with account sync. If I save my flow I get this error 

"HttpActions:requestSync(): no user logged!"

Already unlinked my account in google home, deleted the google auth json files, and resterted node red.
After linking it again the issue remains.

As well I see 4 devices in my google home app. But new devices are not added.
I can control the existing one's with google home app but if I use voice control of google nest hub it says that device is not reachable.

Any idea ?

**Comment by ckhmer1** [comment]
It could be a wing device configuration.
Try to disable all service and add just a new one, a switch with on/off trait.
All devices should disappear except the new one.

**Comment by T1mey** [comment]
> It could be a wing device configuration. Try to disable all service and add just a new one, a switch with on/off trait. All devices should disappear except the new one.

So I removed all and added just the switch. All devices get deleted in home app (and the new one does not appear)....
If I add the deleted one'S they appear again... but not the switch...

Crazy...

**Comment by T1mey** [comment]
> > It could be a wing device configuration. Try to disable all service and add just a new one, a switch with on/off trait. All devices should disappear except the new one.
> 
> So I removed all and added just the switch. All devices get deleted in home app (and the new one does not appear).... If I add the deleted one'S they appear again... but not the switch...
> 
> Crazy...

Found the issue., was a mistake by me.... devices are now visible. 
But the problem that I can only use the buttons in google home and not voice control is still there.

google nest hub it says for all devices that device is not reachable.

**Comment by ckhmer1** [comment]
Perhaps it's helpful if you share with us what was the problem

**Comment by T1mey** [comment]
The problem was that I accidently added a second management config and as I added a new device it was set as default...
The voice control problem could still not be solved....

**Comment by T1mey** [comment]
Ok... found te issue ... I said to my nest hub "force local" in my working area and thought that this is limited to the device ... seems that it is valid for the account ;-)

Thanks for providing this software !!!

**Comment by Caprico85** [comment]
Glad you got it fixed.

I added a note to the Troubleshooting section about using "force local/default"
