### ISSUE TITLE
Google link not possible

### ISSUE THREAD

**Issue by ckhmer1** [mikejac/node-red-contrib-google-smarthome#36]
Hi,
thanks for your effort in developing this plug-in.

I'm not able to login to the google home, I can enter the login and password, the node-red redirects to the redirect_utl, but the mobile phone goes again to the service selection.

Find below the log:
HttpAuth:httpAuthRegister(GET /oauth)
GET /oauth?client_id=XXXXXXXXXXX&response_type=code&state=STATE_STRING_FILL_IT&scope=REQUESTED_SCOPES_FILL_IT&user_locale=LOCALE_FILL_IT&redirect_uri=https://oauth-redirect.googleusercontent.com/r/PROJECT_ID_FILL_IT 200 5.141 ms - 6938
HttpAuth:httpAuthRegister(POST /oauth): body = {"state":"STATE_STRING_FILL_IT","client_id":"XXXXXXXXXXX","username":"ckhmer1","password":"PPPPPPPPPPPPP","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/PROJECT_ID_FILL_IT"}
HttpAuth:httpAuthRegister(POST /oauth): login successful
HttpAuth:httpAuthRegister(POST /oauth): authCode successful; authCode = 5rWoAnjQQ3skMLUKYg5f4ST6WQ6MFKXb6ZbKP6WjLBtY
POST /oauth 302 6.986 ms - 164
HttpAuth:httpAuthRegister(/token): query = {}
HttpAuth:httpAuthRegister(/token): body = {"client_id":"XXXXXXXXXXX","client_secret":"SSSSSSSSSSSSSSSSSSSSSS","grant_type":"authorization_code","code":"5rWoAnjQQ3skMLUKYg5f4ST6WQ6MFKXb6ZbKP6WjLBtY","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/PROJECT_ID_FILL_IT"}
HttpAuth:handleAuthCode(): TypeError: Cannot read property 'accessToken' of undefined
POST /token 400 4.292 ms - 2

I've used the following script:

**login_get**
```
#!/usr/bin/env bash
. ./data
curl "$BASE_URL/oauth?client_id=$GOOGLE_CLIENT_ID&response_type=code&state=$STATE_STRING&scope=$REQUESTED_SCOPES&user_locale=$LOCALE&redirect_uri=$REDIRECT_URI"
echo
```

**login_post**
```
#!/usr/bin/env bash
. ./data

EPWD=$(printf "%q" $PWD)
echo LOGIN POST
AUTH=$(curl -s --data "response_type=code" --data "state=$STATE_STRING" --data "client_id=$GOOGLE_CLIENT_ID" --data "username=$USERNAME" --data-urlencode "password=$PWD" --data-urlencode "redirect_uri=$REDIRECT_URI" $BASE_URL/oauth)
echo "AUTH RESPONSE: $AUTH"
CODE=${AUTH##*code=}
echo "CODE $CODE"
CODE=${CODE%%&*}
echo "CODE $CODE"
echo "CODE=\"$CODE\"" > code
```
**authorization_code**
```
#!/usr/bin/env bash
. ./data
. ./code

AUTH=$(curl -s --data "client_id=$GOOGLE_CLIENT_ID" \
--data "client_secret=$CLIENT_SECRET" \
--data "grant_type=authorization_code" \
--data "code=$CODE" \
--data-urlencode "redirect_uri=$REDIRECT_URI" \
$BASE_URL/token)
echo "AUTH $AUTH"
# echo "$AUTH" > auth.json
ACCESS_TOKEN=$(echo "$AUTH" | jq ".access_token")
REFRESH_TOKEN=$(echo "$AUTH" | jq ".refresh_token")
echo "ACCESS_TOKEN=$ACCESS_TOKEN" > code
echo "REFRESH_TOKEN=$REFRESH_TOKEN" >>code
echo
```

**refresh_token**
```
#!/usr/bin/env bash
. ./data
. ./code

AUTH=$(curl -s --data "client_id=$GOOGLE_CLIENT_ID" \
--data "client_secret=$CLIENT_SECRET" \
--data "grant_type=refresh_token" \
--data "refresh_token=$REFRESH_TOKEN" \
$BASE_URL/token)
echo "AUTH $AUTH"
if [[ $AUTH == *access_token* ]] ; then
  ACCESS_TOKEN=$(echo "$AUTH" | jq ".access_token")
  if [ -n "$ACCESS_TOKEN" ] ; then
    echo "ACCESS_TOKEN=$ACCESS_TOKEN" > code
    echo "REFRESH_TOKEN=$REFRESH_TOKEN" >>code
  fi
fi
echo
```

**data**
```
#!/usr/bin/env bash
PROJECT_ID=PROJECT_ID_FILL_IT
GOOGLE_CLIENT_ID=123456789012345678901
STATE_STRING=STATE_STRING_FILL_IT
REQUESTED_SCOPES=REQUESTED_SCOPES_FILL_IT
LOCALE=LOCALE_FILL_IT
REDIRECT_URI=https://oauth-redirect.googleusercontent.com/r/$PROJECT_ID
REDIRECT_URI=$(printf "%q" "$REDIRECT_URI")
REDIREDT_URI=TEST
BASE_URL=http://localhost:3001
USERNAME=my_user
PWD=my_password
CLIENT_SECRET="some-secret-shared-with-google"
```

What's wrong?

Thanks
Claudio

**Comment by Caprico85** [comment]
Something seems to be wrong with your auth storage (the file where this module stores its tokens). Can you please post the lines from your log starting with "Auth:loadAuth()"? Should be some of the first lines after a restart.

You can also try deleting auth storage to force it to be regenerated. This is how you do it:
1. Stop Node-RED.
2. Delete the file "google-smarthome-auth-*.json" from Node-RED's data directory. If you can't find it, run `find / -name "google-smarthome-auth-*.json"`.
3. There might also be data saved to the old location that was used some versions ago. Usually it can be found in `~/.node-persist/storage/`. Delete all files in this folder.
4. Start Node-RED. If all went well, the log should say `Auth:loadAuth(): new auth data created`. You should now be able to log in.

**Comment by ckhmer1** [comment]
Hi,
thanks for your help.
Please find below the node red logs, using fake data configuration:

[alarm@imx53-1 ~]$ node-red-pi
4 Aug 07:14:00 - [info]

Welcome to Node-RED
===================

4 Aug 07:14:00 - [info] Node-RED version: v1.1.2
4 Aug 07:14:00 - [info] Node.js  version: v14.7.0
4 Aug 07:14:00 - [info] Linux 5.7.6-1-ARCH arm LE
4 Aug 07:14:07 - [info] Loading palette nodes
4 Aug 07:14:46 - [info] Settings file  : /home/alarm/.node-red/settings.js
4 Aug 07:14:46 - [info] Context store  : 'default' [module=memory]
4 Aug 07:14:46 - [info] User directory : /home/alarm/.node-red
4 Aug 07:14:46 - [warn] Projects disabled : editorTheme.projects.enabled=false
4 Aug 07:14:47 - [info] Flows file     : /home/alarm/.node-red/flows_imx53-1.json
4 Aug 07:14:47 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

4 Aug 07:14:47 - [info] Starting flows
Auth:loadAuth(): err: SyntaxError: Unexpected end of JSON input
SmartHome:Start(listen): using external SSL offload
SmartHome:Start(): registered routes:
SmartHome:Start(): /oauth
SmartHome:Start(): /oauth
SmartHome:Start(): /token
SmartHome:Start(): /smarthome
SmartHome:Start(): /smarthome
4 Aug 07:14:47 - [info] Started flows
SmartHome:Start(listen): listening at :::3001
4 Aug 07:14:47 - [info] Server now running at http://127.0.0.1:1880/



HttpAuth:httpAuthRegister(GET /oauth)
GET /oauth?client_id=123456789012345678901&response_type=code&state=STATE_STRING_FILL_IT&scope=REQUESTED_SCOPES_FILL_IT&user_locale=LOCALE_FILL_IT&redirect_uri=https://oauth-redirect.googleusercontent.com/r/PROJECT_ID_FILL_IT 200 166.660 ms - 6938


HttpAuth:httpAuthRegister(POST /oauth): body = {"state":"STATE_STRING_FILL_IT","client_id":"123456789012345678901","username":"my_user","password":"my_password","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/PROJECT_ID_FILL_IT"}
HttpAuth:httpAuthRegister(POST /oauth): login successful
HttpAuth:httpAuthRegister(POST /oauth): authCode successful; authCode = HBHRQpYN8QW7iJ2tjpM3qCWU9VjQHXnqC5SGkHWXi78c
POST /oauth 302 418.202 ms - 164



HttpAuth:httpAuthRegister(/token): query = {}
HttpAuth:httpAuthRegister(/token): body = {"client_id":"123456789012345678901","client_secret":"some-secret-shared-with-google","grant_type":"authorization_code","code":"HBHRQpYN8QW7iJ2tjpM3qCWU9VjQHXnqC5SGkHWXi78c","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/PROJECT_ID_FILL_IT"}
HttpAuth:handleAuthCode(): TypeError: Cannot read property 'accessToken' of null
POST /token 400 86.564 ms - 2

**Comment by ckhmer1** [comment]
Hi,
I've found the problem, in case that the file "google-smarthome-auth-*.json" doesn't exist, the code raises an exception and doesn't write it.
I've fixed it with my pull requests. I hope you agree to merge them.
Thanks
Claudio

**Comment by ckhmer1** [comment]
Thank for merge all my modification.
Now it is fixed.
