### ISSUE TITLE
Any way to read other devices status like alarm, times etc?

### ISSUE THREAD

**Issue by cwickstr** [mikejac/node-red-contrib-google-smarthome#365]
Hi, Is there any way to read status of other devices?
For example i am looking for a way to read the wake up alarm time that i set on my Lenovo Smart-clock each night, and based on that i want be able to for example turn on some lights 20 minutes before the alarm rings or do something else.

Reading the statuses for every single device could be very useful for other automation tasks as well.
A node that simply returns a complete dump of all devices statuses in the home would be enough.
If all the device status data is stored in the HomeGraph there is already access?
(I did experimented some with the undocumented local access device API but authentication for getting tokens failed.)

Thanks!

**Comment by Paul-Reed** [comment]
Have you tried the smarthome Management node?
Inject the topic `get_state` into the management node, and it should return the HomeGraph status of all devices.

![get state](https://user-images.githubusercontent.com/973580/212768895-ec609621-f3f4-4cce-8be2-b2f598437b4c.JPG)

**Comment by cwickstr** [comment]
Hi @Paul-Reed ,
This way i can can only get the status from the devices configured in Node-RED, if "Persistent state" is checked:
![image](https://user-images.githubusercontent.com/106800555/212828055-2986fff6-e440-44bd-8db7-2ea2cae81260.png)

Anyway, could it probably work for any other device in the HomeGraph if there was a way to query a specific device with its ID?
-And that would need some kind of other query to first get a list of all configured devices in the HomeGraph.

**Comment by Caprico85** [comment]
`get_state` does not query the Home Graph. It only reads the states you set via the device nodes in Node-RED. If your alarm clock is not set via Node-RED, you can not query it this way.

node-red-contrib-google-smarthome does not query the Home Graph. It only sends new state values to the Home Graph, but it does not read back values. Neither for devices in your own smarthome project nor for devices in other projects. 

If you know the project id of the project your alarm clock is running in, you can look into the [Home Graph Viewer](https://smarthome-test-suite.withgoogle.com/devices). There is probably an API to get the same information too. But this is not part of node-red-contrib-google-smarthome.

For Home Assistant there is https://github.com/leikoilja/ha-google-home to query some states of your devices. It says it can also read alarms. I never used it though. I don't know if it works, if it does what you want and if there is something similar available for Node-RED.

**Comment by cwickstr** [comment]
Thank you all for replying.
I will find some another way. And thank you for making this great project!

/Carl
