### ISSUE TITLE
Google home linking fails

### ISSUE THREAD

**Issue by BlackWolves-nl** [mikejac/node-red-contrib-google-smarthome#373]
Hi I'm trying to setup this by following everything in the Setup Instructions.

Environment:
Windows 11 with iis reverse proxy
Node-RED version: v3.0.2
Node.js  version: v17.9.1

When trying to link the service in google home i get the following message after entering the credentials:
Cannot GET /r/domo-87744

Log from node red looks like this:
`HttpAuth:httpAuthRegister(POST /oauth): body = {"username":"***","password":"***","client_id":"ZRsxmx74aTNKRKEPjZfK986FQpNYJwAP","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/domo-87744","state":"ADtLpDvM0-OLPDzbvrGRLFOWxiHEwviNmgeK09Pk-P9uVqUYGdelhyOwJe6lXvFSk4NBp6fLyHViZp8MrbBQiwWw-wTPwaWJ64ml9xYcEIYD01uVVVUy1-JfoPOKwzlUUWZmyfeNL5BGdBdi7QtRh9oecBxTzp6KtV9bcHTb0FhKy1JnbJRtMvW9zuptbC6dMExr4oczF-X6r__sD8BKZQr0L6PTkelrw9zFsxL2CeVIVQ1-_MYSrf-x5FWss561THPTKws1TPSi9nxzjzduz8dhBqvbUwSWgBCeW4Y1AtKzPbkbtMJUEZyY5XXVDKfLCrA4_JvoifUkPZTBDdNs76dE4s9EyfOkq1RcuU7sUda-c9_b7uUEwgrVrwjnYAvoJn1IiZy-h7niO3sh1A7rHgHezDDsxh0Ixe4Zgq4o0SZOW1La7d7Xua3xRiQIe8SdVKpkyzJWlrU4n7cfC_TnrAkChiKQhALig-Q31ZiXAZMAbBsoSZVeQlVRP2Q_x8_0U3kwt_avqeqz0oC9arPuNGFSVr1Dngt1AP8X0IeubMtszLsCvyCBrqUo8CLZK4sa97ePiUXqAlGtPMXJM_cYvJI5Omw0G_aM4Emga44IhIOFPfWR4ajmuMC-0vi-0VUjf7SkH4pNGXzs","response_type":"","id_token":""}
HttpAuth:httpAuthRegister(POST /oauth): Local login
HttpAuth:handleUserAuth(): login successful
HttpAuth:handleUserAuth(): authCode generated successfully (authCode = 4x3Atrjo5yZ2KQ8q9VNDqY1EPFDjMRbovAYyA5PpG8PT)
HttpAuth:handleUserAuth(): redirecting to Google at https://oauth-redirect.googleusercontent.com/r/domo-87744?code=4x3Atrjo5yZ2KQ8q9VNDqY1EPFDjMRbovAYyA5PpG8PT&state=ADtLpDvM0-OLPDzbvrGRLFOWxiHEwviNmgeK09Pk-P9uVqUYGdelhyOwJe6lXvFSk4NBp6fLyHViZp8MrbBQiwWw-wTPwaWJ64ml9xYcEIYD01uVVVUy1-JfoPOKwzlUUWZmyfeNL5BGdBdi7QtRh9oecBxTzp6KtV9bcHTb0FhKy1JnbJRtMvW9zuptbC6dMExr4oczF-X6r__sD8BKZQr0L6PTkelrw9zFsxL2CeVIVQ1-_MYSrf-x5FWss561THPTKws1TPSi9nxzjzduz8dhBqvbUwSWgBCeW4Y1AtKzPbkbtMJUEZyY5XXVDKfLCrA4_JvoifUkPZTBDdNs76dE4s9EyfOkq1RcuU7sUda-c9_b7uUEwgrVrwjnYAvoJn1IiZy-h7niO3sh1A7rHgHezDDsxh0Ixe4Zgq4o0SZOW1La7d7Xua3xRiQIe8SdVKpkyzJWlrU4n7cfC_TnrAkChiKQhALig-Q31ZiXAZMAbBsoSZVeQlVRP2Q_x8_0U3kwt_avqeqz0oC9arPuNGFSVr1Dngt1AP8X0IeubMtszLsCvyCBrqUo8CLZK4sa97ePiUXqAlGtPMXJM_cYvJI5Omw0G_aM4Emga44IhIOFPfWR4ajmuMC-0vi-0VUjf7SkH4pNGXzs

POST /oauth 302 6.821 ms - 1584

GET /r/domo-87744?code=4x3Atrjo5yZ2KQ8q9VNDqY1EPFDjMRbovAYyA5PpG8PT&state=ADtLpDvM0-OLPDzbvrGRLFOWxiHEwviNmgeK09Pk-P9uVqUYGdelhyOwJe6lXvFSk4NBp6fLyHViZp8MrbBQiwWw-wTPwaWJ64ml9xYcEIYD01uVVVUy1-JfoPOKwzlUUWZmyfeNL5BGdBdi7QtRh9oecBxTzp6KtV9bcHTb0FhKy1JnbJRtMvW9zuptbC6dMExr4oczF-X6r__sD8BKZQr0L6PTkelrw9zFsxL2CeVIVQ1-_MYSrf-x5FWss561THPTKws1TPSi9nxzjzduz8dhBqvbUwSWgBCeW4Y1AtKzPbkbtMJUEZyY5XXVDKfLCrA4_JvoifUkPZTBDdNs76dE4s9EyfOkq1RcuU7sUda-c9_b7uUEwgrVrwjnYAvoJn1IiZy-h7niO3sh1A7rHgHezDDsxh0Ixe4Zgq4o0SZOW1La7d7Xua3xRiQIe8SdVKpkyzJWlrU4n7cfC_TnrAkChiKQhALig-Q31ZiXAZMAbBsoSZVeQlVRP2Q_x8_0U3kwt_avqeqz0oC9arPuNGFSVr1Dngt1AP8X0IeubMtszLsCvyCBrqUo8CLZK4sa97ePiUXqAlGtPMXJM_cYvJI5Omw0G_aM4Emga44IhIOFPfWR4ajmuMC-0vi-0VUjf7SkH4pNGXzs 404 1.175 ms - 151`

When trying to use the check page i get:
GET check: OK
GET oauth: OK
POST oauth: ERROR: redirect_uri https://dtgh.blackwolves.nl/oauth?response_type=code&client_id=ZRsxmx74aTNKRKEPjZfK986FQpNYJwAP&state=state&ac= invalid
POST token: Pending
POST smarthome: Pending

with node red log:
`HttpAuth:httpAuthRegister(POST /oauth): body = {"client_id":"ZRsxmx74aTNKRKEPjZfK986FQpNYJwAP","redirect_uri":"https://dtgh.blackwolves.nl/oauth?response_type=code&client_id=ZRsxmx74aTNKRKEPjZfK986FQpNYJwAP&state=state&ac=","username":"***","password":"***"}
20 Feb 10:00:30 - [error] [googlesmarthome-client:Config] Auth:isValidRedirectUri(): invalid redirect uri!
20 Feb 10:00:30 - [error] HttpAuth:httpAuthRegister(POST /oauth): redirect_uri https://dtgh.blackwolves.nl/oauth?response_type=code&client_id=ZRsxmx74aTNKRKEPjZfK986FQpNYJwAP&state=state&ac= invalid
POST /oauth?state=state 500 15.287 ms - 132`

What did i do wrong?

**Comment by BlackWolves-nl** [comment]
Note:
If i do the check page local (localhost:3001/check) all the checks are ok

**Comment by Caprico85** [comment]
Hi

`Cannot GET /r/domo-87744` looks suspicious.

Which URLs did you set as Auth, Token and Fulfillment URL on the Actions on Google Console?

![image](https://user-images.githubusercontent.com/2081806/220178386-8ac7910d-3fd4-4ddd-b833-81c9618dfcf5.png)

![image](https://user-images.githubusercontent.com/2081806/220178503-84cf427e-8957-4a7b-9598-471f9aa6d629.png)

It has be your domain, followed by `/oauth`, `/token` and `/fulfillment` respectively.

If you have set an URL subpath, this comes in front of the path (as in `https://yourdomain.com:3001/subpath/oauth`).

**Comment by BlackWolves-nl** [comment]
they are all prefixed with the domain url:
https://dtgh.blackwolves.nl/smarthome
https://dtgh.blackwolves.nl/oauth
https://dtgh.blackwolves.nl/token

no subpath is set

**Comment by BlackWolves-nl** [comment]
Tried doing it all from scratch but the same error occurs.
Can you see from the logging from where to where this goes wrong?
Could it be my iis reverse proxy? (I have more sites running these proxies and they work fine)

**Comment by BlackWolves-nl** [comment]
I manually copied the certifcates to test without the proxy and yes then it works.
So its something with the reverse proxy in iis.
Does anyone have experience with this?
Im using IIS because i use certifytheweb for automatic certifcate renewal.

**Comment by BlackWolves-nl** [comment]
Going to close the issue as is found out that certifytheweb has deployment tasks.
It now exports the certicates to the files.
I now only have to configure a task to reset the node red server
