### ISSUE TITLE
A request of support to improve the list of commands

### ISSUE THREAD

**Issue by sergemartin66** [mikejac/node-red-contrib-google-smarthome#378]
Hello,
 I use the node-red-contrib-google-smarthome software to drive a small robot like R2D2. It works very well! I configured the Device node as a REMOTE_CONTROL in Node-Red. So, my robot runs if I say 'Hey Google avance'   (I'm French), it stops if I say 'Hey Google arrete',  it goes to the right side if I say 'Hey Google précédant',  it goes to the left side if I say 'Hey Google suivant'. What do I have to do to add many new commands like 'go to the kitchen' or 'take the pencil' ? Is there a device with wich I can find in the message payload what I said in GOOGLE ASSISTANT ? Or Is there a device that uses a JASON input file where the commands are described and that I can easily modify ?
Thanks for your help !
 Best regards.
Serge Martin

**Comment by Caprico85** [comment]
Closing this now. Feel free to reopen.
