### ISSUE TITLE
Google Assistant recognize user voice and make a user verification

### ISSUE THREAD

**Issue by JosepFarreLlados** [mikejac/node-red-contrib-google-smarthome#393]
Hello!
This is a question rather than an issue. 
Does anyone know how to [recognize the user voice](https://support.google.com/assistant/answer/7394306)?
I can verify the user with a [PIN code](https://discourse.nodered.org/t/node-red-contrib-google-smarthome-user-verification-feature/55355), could be possible implement a user verification using the recognize user voice function? So, in case of a voice command get a msg with the user name for instance?

**Comment by Caprico85** [comment]
Hello!

No, unfortunately there is no way to do this. Google does all the voice recognition by itself. Node-RED basically only gets a message saying "Device ... should be switched on". No details on who started the request, no voice information, no voice recordings, not even an information on which device started the request or if the user used voice or app.
