### ISSUE TITLE
Node red creates a new device instead of addressing the original one

### ISSUE THREAD

**Issue by Tom-vdv1988** [mikejac/node-red-contrib-google-smarthome#397]
Hello,

I have a problem that my nodes are not synced with google home but that they are created twice.
The intention is that I operate an outlet from the node red.

In Node Red:
![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/134892539/36c02d76-67a9-4693-bfb6-369850f75470)
![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/134892539/bb4c6299-6c9f-4e99-b27d-1b9c7ce2a837)
**--> I named the outlet the same as in google.**

In google Home:
![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/134892539/204ab8bd-835f-4cf2-b41b-c0dcc8543e64)

--> I can operate the dubble created device from the Node Red.

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/134892539/aa9584ff-9866-41e5-b148-c89a1470cf8a)

1) Original outlet that is present in the house, and is working from gogle home
2) New Outlet created by Node Red.

But the intention is that I can operate the existing outlet. 
And not that a 2nd one is created.
**--> Node Red should address the original outlet (1) and not create a new one.**

I have also tried this with lamps, but this gives the same result. Lamps are also created twice.

**I call the devices the same as in Google home.**
**What am I doing wrong?**

**Thank you already for the help.**

kr,
Tom

**Comment by FireWizard52** [comment]
Hi,

How is your first device, the original outlet, created?
Is it because another manufacturer, and where yout outlet is part of, has been connected to Google.

Regards

**Comment by Caprico85** [comment]
Hi @Tom-vdv1988!

If your device is already connected using another manufacturer, there is no way to control it with node-red-contrib-google-smarthome. We can only create new devices, we cannot take control over existing devices from other manufacturers.

You can unregister the device from its original manufacturer and control it exclusively from Node-RED if there's a module available for it. Then it would only appear once in Google Home. On the downside you loose the ability to control your device if Node-RED is offline.

Regards
