### ISSUE TITLE
 Notification at Google Nest Mini from a detector

### ISSUE THREAD

**Issue by JosepFarreLlados** [mikejac/node-red-contrib-google-smarthome#398]
Hello!!
I have node-red v3.0.2 and I use "node-red-contrib-google-smarthome" version 0.4.4

Following the instruccions on [issue 327](https://github.com/mikejac/node-red-contrib-google-smarthome/issues/327)  I have a doorbell device with [Objectdecteion](https://developers.home.google.com/cloud-to-cloud/traits/objectdetection) to notify when is activated.

To receive the notification I have I have two speakers:

- [Lenovo Smart clock](https://www.lenovo.com/es/es/smart-clock/?orgRef=https%253A%252F%252Fwww.google.com%252F) works fine and I receive a voice notification when is activated the bell.
- [Nest mini](https://store.google.com/es/product/google_nest_mini?hl=es) (Firmware system 356012 with firmware cast 1.56.356012 I don't receive the notification. 

The setup on Node-red must be correct due to on my Lenovo I receibe the notification correctly.
At both speakers  I allowed the notifications despite the Nest mini not works. See attached picture of the Nest mini setup. 
![Imagen de WhatsApp 2023-06-23 a las 16 40 31](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/98636450/b79158df-0da5-4b6e-93ae-38b601d54c78)

Any feedback with notifications using a Nest mini?
Thanks in advance.

**Comment by Caprico85** [comment]
Hi @JosepFarreLlados,

from the API side there is no way to select the speaker that should respond. As far as i know all speakers should respond simultaneously. If one speaker does not respond, it is maybe not assigned to the same household or it is set to Do not disturb mode. Here they discuss the problem in reverse (silencing a speaker insted of getting it to talk): https://www.reddit.com/r/googlehome/comments/mjz5bg/voice_notifications_to_specific_speaker/

Regards

**Comment by JosepFarreLlados** [comment]
Hello!!
Many thanks for your feedback. 
I have the doorbell device setup according with the steps of [FireWizard52](https://github.com/FireWizard52). My [Lenovo Smart clock](https://www.lenovo.com/es/es/smart-clock/?orgRef=https%253A%252F%252Fwww.google.com%252F) works fine and reproduce a message each time as is activated the doorbell device. So for this reason I assume my doorbell device setup is correct and I have the problem on my [Nest mini](https://store.google.com/es/product/google_nest_mini?hl=es) that no reproduce nothing when the alarm is activated.
Now I set my [Nest mini](https://store.google.com/es/product/google_nest_mini?hl=es) speaker on the same "room" of the doorbell device (previously was on another "room"). When is activated the doorbell device the Lenovo Smart clock reproduce a message and the Nest mini no. I also tested to have each device connected individually and the Nest mini never works.
Find attached my [Nest mini](https://store.google.com/es/product/google_nest_mini?hl=es) setup screenshots:
![Nuevo Presentación de Microsoft PowerPoint](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/98636450/812444f8-7c4a-4337-9784-c119fa38b01b)
Thanks in advance.

**Comment by FireWizard52** [comment]
Hello @JosepFarreLlados 

Can you also post the last screen, as I showed you in my post? I'm very curious what that setting shows.

Regards

**Comment by JosepFarreLlados** [comment]
Hello,
Many thanks for your feedback.

Find attached my doorbell device setup on Google Home app and my Node-red setup:
![Nuevo Presentación de Microsoft PowerPoint (2)](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/98636450/8335c4e5-8d38-401d-a944-92dd0781e28d)

Thanks in advance.
Regards,

**Comment by FireWizard52** [comment]
Hello @JosepFarreLlados,

I checked all of your screenshots carefully with mine but I do not notice any significant differences between your settings and mine.
 However my Function node in front of the Google Home doorbell is a little different, but I'm notsure if this is essential.

It contains:

`if ((msg.payload.source === "switch") && (msg.payload.output === true)) {
   msg.topic = "ObjectDetection";
   msg.payload = { "unclassified": 1 }
 } else {
    return null
 }

return msg`

Regards

**Comment by FireWizard52** [comment]
Hi @JosepFarreLlados,

This morning I tested my system again, just to be sure that there is not an issue introduced with the latest firmware.
Luckily this is not the case.

For your information. I own a Google Nest Hub in the  Living Room and a Google Nest Mini in the kitchen. The living room has an open  connection with the kitchen. I have also a second Google Nest Mini upstairs.

If I test the doorbell, I get the notification on all three devices. However the text is not in sync. That might be considered as disturbing in case you have multiple devices that you can hear at the same time..

The only thing I noticed, that in the device (doorbell) configuration, I have "Persistent state" checked, while your configuration shows unchecked. In my opinion, that should not make the difference.

I'm afraid, I cannot do much more for you.

@Caprico85 

I noticed that the device, configured as doorbell, always show as status: "Unknown".
Wouldn't it be better to show "On" / "Off" or "Active"/ "Inactive" instead?

I'm not sure, what the best option would be, but "Unknown" is rather "Unclear"

Regards

**Comment by JosepFarreLlados** [comment]
Hello,
A friend borrow me a Google Nest Mini and works perfect. So it means that I have a problem with my unit. I will replace it!
Many thanks for your support!
Best regards
