### ISSUE TITLE
Option to disable SSL

### ISSUE THREAD

**Issue by merlinschumacher** [mikejac/node-red-contrib-google-smarthome#4]
I would like to use a reverse proxy for all services on my machine that automatically takes care of SSL termination. Because of this it would be great to be able to disable SSL in the node.

**Comment by mikejac** [comment]
An "Use external SSL offload" option has now been added to the config node. Please update to 0.0.14 and give it a go.

/michael

**Comment by Webunity** [comment]
would this mean i would need the `use external ssl offload` whenever i am running behind Traefik or any other reverse proxy?

**Comment by Caprico85** [comment]
If your proxy does SSL termination (not only simple TCP forwarding) you would have to use "use external ssl offload".

**Comment by mikejac** [comment]
I have now tested this myself and for me it works fine. I ended up using [Caddy](https://caddyserver.com/v1/download) as my frontend.
