### ISSUE TITLE
Solved: Simple set up with a subdomain and NGINX reverse proxy

### ISSUE THREAD

**Issue by RichardUUU** [mikejac/node-red-contrib-google-smarthome#408]
Here's a slightly simpler way to set up if you use NGINX Reverse Proxy (HA add-on). 

Go into your domain DNS and create a subdomain: e.g. nr.example.com. Point that to your home IP.

In NGINX Reverse Proxy, create a new Proxy Host that sends nr.example.com to your HASSIO machine IP with a port of your choosing e.g. 192.168.1.101:1234 This should not expose your whole NodeRed, just the SmartHome server.

NGINX can request a new SSL certificate for you, or use a wildcard if you have one.

When installing google actions, account linking, service account, credentials etc. there is no need to list any ports. Just use nr.example.com

In Node Red, set the Google SmartHome configuration node to your chosen port: e.g. 1234

Now test: https://nr.example.com/check

Cheers, Richard

**Comment by Caprico85** [comment]
Thank you! Added this to the [reverse proxy page](https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/docs/reverse_proxies.md) in the docs.
