### ISSUE TITLE
@mikejac: Enable Discussions for repository

### ISSUE THREAD

**Issue by Caprico85** [mikejac/node-red-contrib-google-smarthome#409]
Hello Michael / @mikejac,

@NikAWing suggested in #404 to have a place for discussions, so we don't have to put everything in the issue tracker. I think GitHub's discussion feature is maybe the best place for that. Can you please enable discussions for the repo? 

This is done in the repository settings, in "General" > "Features" > "Discussions".

Thank you!

Regards,
Caprico

**Comment by mikejac** [comment]
Discussions are ON ! :-) 

... and thank you for all the great work that is going into this project.
