### ISSUE TITLE
no user loged in

### ISSUE THREAD

**Issue by T1mey** [mikejac/node-red-contrib-google-smarthome#414]
Hello,

I did the setup a year ago and for some reason my setup stopped working (2 months ago).
I'm getting the error:

"HttpActions:reportState(): skipped reporting states, no user logged in"

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/10464878/756b8bae-c495-4bbe-948a-716d10b16198)

Any idea what could be wrong? Activate google passkeys but I don't think this is the reason.

**Comment by T1mey** [comment]
found it...

**Comment by Caprico85** [comment]
Hello @T1mey!

"no user logged in" means there is something wrong with the oAuth2 tokens.

First thing you could try is logging out and in again. To do that, in the service list, select your service and select "Unlink account". Then relink as usual.

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/af0b8ccf-4287-4e05-b0a3-05349b5e2d35)

If this doesn't help, stop Node-RED. Then delete the file `google-smarthome-auth-*.json' in Node-RED's user directory (where your flows.json, settings.js, etc. are). Then restart Node-RED and relink your account as usual.
