### ISSUE TITLE
Setup Account linking  Step 5 does not work! An error occured, please try again later

### ISSUE THREAD

**Issue by hohmannc85** [mikejac/node-red-contrib-google-smarthome#417]
Hello! I did everything like your instruction. Everything works so far, I get also the success request.
now I am at step 5 Setup Account linking; I klick in my app on [test] XXXX (no device count below). and it says there is an error try again later. any idea?

as well I can run https://xxx/oauth, /token , /check and I see a result, but /smarthome does not exist! is that correct?

**Comment by Caprico85** [comment]
Hello @hohmannc85,

did you try https://xxx/smarthome in the browser? /smarthome only supports POST requests. You need a tool like https://resttesttest.com/ for that. Select the POST method.

If it works, you should get error 401 with "missing inputs" (as we gave no credentials).

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/d2c1d0d5-0bf2-4965-9a8e-2abc29a7b33a)

If you get another error (like 404) there is indeed something wrong.

**Comment by hohmannc85** [comment]
Hello thank you for your help, Google Need some Time and i Had to redownload the App. Everything works great- good job
