### ISSUE TITLE
Could not reach ... Please try again.

### ISSUE THREAD

**Issue by m1k3f15h** [mikejac/node-red-contrib-google-smarthome#429]
Hy
i have a problem by "Setup Account linking".

When i press on the Name of my "app" i get the message: Could not reach ... Please try again.
![Screenshot_2023-09-27-10-01-55-09_680d03679600f7af0b4c700c6b270fe7.jpg](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/26365771/b7a81e04-3cdb-4018-b10c-56ee7e09af8c)

Someone else hat this problem?

All urls are reachable from the internet
Reverseproxy Traefik

Greetings from Austria
Mike

**Comment by Caprico85** [comment]
I "finally" had the same problem when I tried to relink my account. Found a solution [here](https://community.home-assistant.io/t/can-no-longer-link-google-assistant/409495/19). For me, this fixed the problem.

Can you please try this:

1. Go to the [Google Actions Console](https://console.actions.google.com/project/wohnung-45a57/directoryinformation/).
![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/80c0642d-f9d6-4f8a-bfa5-a762a4170889)

2. Go to "Deploy" and "Directory Information".

3. Fill out the form. What you enter doesn't really matter. I filled it out like this. As small icon I used https://nodered.org/about/resources/media/node-red-icon.png. The large icon is some wallpaper I had lying around.

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/523694af-ea97-4c27-9b2a-c04b653762a4)
![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/505198bc-0675-4bcb-8092-0185cf45d334)

4. Save the form.

5. Try linking your account again. 

If you can confirm this helps, I'll add this to the setup instructions.

**Comment by m1k3f15h** [comment]
Hy
I tried it, but no change :(

**Comment by Caprico85** [comment]
Hi,
I admit, I'm out of ideas now.

I don't think, it's related to node-red-contrib-google-smarthome, as it works for me and others. I also don't think it's related to your setup, as all other web requests in the authentication process are going through. It's unlikely that only this request is blocked.

I did some more googling. There are reports (mainly [here](https://www.googlenestcommunity.com/t5/Apps-Account/Google-Home-app-quot-Could-not-reach-service-quot-for-any-Works-with-Google/m-p/305201)) that this happens from time to time and with all smart home services, not just ours. People suggest using a different phone linked to the same Google account to connect to the smart home service. If it's linked on one phone, it'll be linked on all phones. Others have suggested doing this:

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/d40a6fde-91d8-498a-a0ae-41704330f3fe)

**Comment by Caprico85** [comment]
Closing this now. Feel free to reopen if your problems persist.

**Comment by Aragur** [comment]
Now it's working, I had to press the "Test" button here:
<img width="1464" alt="image" src="https://github.com/mikejac/node-red-contrib-google-smarthome/assets/11004008/81c2e342-844b-4849-8ce6-4010558c9a82">
