### ISSUE TITLE
Adding to Google Home fails

### ISSUE THREAD

**Issue by Vitus-TL** [mikejac/node-red-contrib-google-smarthome#434]
Hi, 

I managed to do the whole bells and whistles, including HTTPS. All tests worked okay, including external. But when I try to add it to Google Home on the smartphone, I get a message something has gone wrong (using Google login).
When I try to open:
https://domain.tlc:3001/oauth?client_id=XXXXXX.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Foauth-redirect-sandbox.googleusercontent.com%2Fr%2F<project-id>&response_type=code&state=abc I get:
client_id .... invalid. I copied and paste the used ID and grepped it  on client_secret_XXXXXX.apps.googleusercontent.com.json and 100% match... (and reapplied it on Node-RED, to be sure).

Regards
PS I anonymized the syntax

**Comment by Caprico85** [comment]
Hi @Vitus-TL,

Does your client_id contain any special characters? We had (or still have?) problems with characters getting incorrectly URL-encoded and decoded. So for now, I'd recommend using only alphanumeric characters (a-z, A-Z, 0-9) in your client_id.

In Node-RED's debug panel, you should also get a message about the client_id, including the expected and received IDs. Any differences there?

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/b8881188-b8d6-4f11-9570-fbb597c1642d)

**Comment by Vitus-TL** [comment]
Hi @Caprico85,

I used the client ID for Google login to test, which is generated by Google and contains "-" and "." beside letters and digits

**Comment by Vitus-TL** [comment]
PS I found the mistake, I forgot to add "/smarthome" to the fulfilment URI.... Sorry for wasting your time..

**Comment by Caprico85** [comment]
So you got the client id and linking to work now? Or do you still have problems?
