### ISSUE TITLE
some devices don't obey discreteOnlyOpenClose attribute

### ISSUE THREAD

**Issue by patrik-malina** [mikejac/node-red-contrib-google-smarthome#475]
For instance I have garage door that can only open or close. Also with water valve.
Doors for instance obey this attribute.

**Comment by Caprico85** [comment]
I cannot reproduce this. I tested with windows, doors and valves. They all worked fine for me.

How are your devices configured? Mine are configured like this:

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/2081806/585589aa-6437-41d4-90cb-66aedb1cac0d)

PS: v0.4.9 fixes the missing "discrete only" label in the configuration.
