### ISSUE TITLE
"Could not reach ... Please try again", check all OK

### ISSUE THREAD

**Issue by ebanDev** [mikejac/node-red-contrib-google-smarthome#493]
Hello !

I've installed and configured the addon following your instructions, it's all working according to the check page 

![image](https://github.com/mikejac/node-red-contrib-google-smarthome/assets/57091497/9efa3440-d9a5-401c-a73b-433243007873)

But when I select my "device" from the google home app I get the error code "Could not reach ... Please try again". I checked the logs, I found nothing in the docker logs or the node-red logs.

I'm using the latest version of both node-red and your addon. I've verified that the configured Fulfillment, Authorization and Token URL are correct, and they are.

I'm kinda stuck, hope you'd be able to help ! :)

Best,
Eban

**Comment by Caprico85** [comment]
Hi @ebanDev,

unfortunately we haven't found a definitive reason for "Could not reach" yet. Usually it's not that something is actually not reachable.

One thine you could try is reset testing. Open the Actions Console (https://console.actions.google.com/). Go to Test > Simulator. On the top right click the `Settings` button. Disable `On device testing". then click `Start testing`.

You can also try disabling Wi-Fi on your smartphone and try to connect using the mobile network, in case it's related to internal/external connectivity.

Another thing to try is resetting the auth storage stop Node-RED, delete the file `google-smarthome-auth-*.json` from Node-RED`s user diirectory (where the settings.json, flows.json etc. are) then restart Node-RED.

If none of this helps ... well, let's just hope it helps 😄 

Regards,
Caprico

**Comment by ebanDev** [comment]
I tried all of this and still nothing working :( Guess i'm cursed 😅

**Comment by FireWizard52** [comment]
Hello @ebanDev,

Can you provide a little more details of your setup?

A few questions:

1.

> But when I select my "device" from the google home app

Which "device"? It should show "[test] Project-name".
The Project-name is the name, you inserted in your Google Actions Console

2.

> I'm using the latest version of both node-red and your addon.

Which version do you use of Node-RED, NodeJS and the Google Smarthome node.
Latest is not very clear, as that may change in the future.

3.

> I've verified that the configured Fulfillment, Authorization and Token URL are correct, and they are.

How do you know that?

I recommend to build it up.
Configure this Node-RED-contrib node first, as basic as possible and do not use "Google login" and "Local fulfillment".

1. Step 1: Configure it with Username/Password login and test that that works fine.
2. If you have success with step 1, move to "Google login" and test again.
3. If step 1 and/or 2 are successful, you can start to configure "local fulfillment"

> I've installed and configured the addon following your instructions, it's all working according to the check page.

This Node-RED-contrib-smarthome node is not an add-on, but just a community developed node, as many others.

Where did you carry out your check?  Has it been on the Local network by browsing to https://example.com:3001/check.
In or outside the docker container?
Did you also test from the Internet? 

`Use a tool such as https://reqbin.com/ to send a GET request to https://example.com:3001/check (using your domain name and port). It should respond with status 200 and the message "SUCCESS: Smart Home service is reachable!".`

If you are able the questions above, we might be able to give you a hint.

Regards

**Comment by Caprico85** [comment]
Thank you @FireWizard52! Web server settings in the smarthome configuration and validating URLs internally and externally would have been my next questions.

As a sidenote, this week my mother bought a smart food processor (Lidl Monsieur Cuisine). So far, I wasn't able to set it up using it's official account as I'm always greeted with "Could not reach ...". I'm glad even bigger companies are having the same problem 😄
