### ISSUE TITLE
Deploy newest version to NPM

### ISSUE THREAD

**Issue by Aragur** [mikejac/node-red-contrib-google-smarthome#51]
Hey, it would be nice, if the newest version could be deployed to the NPM registry.   
Maybe we could add an automated CI script to upgrade the NPM registry on a version bump.

**Comment by Caprico85** [comment]
@mikejac did the previous releases to NPM. I guess I am not having any permissions to deploy.

**Comment by ckhmer1** [comment]
Hi,
I don't understand, you have no permissions to deploy? Why?

**Comment by Caprico85** [comment]
I'm not the maintainer or owner of this project. I'm only a contributor who got write access to this repository some time ago.

Only the real owner Michael Jacobsen has the credentials to the NPM account. Therefore only he can publish new versions.

**Comment by mikejac** [comment]
@Caprico85 Do you have a username on npmjs? If so, I can make you maintainer ...

**Comment by Caprico85** [comment]
I registered a new account. Username "caprico85".

**Comment by mikejac** [comment]
@Caprico85 Did you get the maintainer invite from npmjs?

**Comment by Caprico85** [comment]
@mikejac No, I didn't get an invitation.

**Comment by ckhmer1** [comment]
Hi,
any news?

**Comment by mikejac** [comment]
Invited you again ...

**Comment by Caprico85** [comment]
Thank you!

It seems to to have worked this time. I didn't got an email or info from NPM, but the package now shows up in my account. I'll try later if I can publish new versions now.

**Comment by mikejac** [comment]
+1

**Comment by Caprico85** [comment]
I DID IT! v0.0.37 is now live on NPM.

I will publish the next versions manually and maybe later try to automate it.

**Comment by Caprico85** [comment]
Finally, the module is available is Node-REDs palette.
