### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by rockstar2020** [mikejac/node-red-contrib-google-smarthome#52]
Hi @mikejac ,
If I don't use the devices or invoke any commands on Google Home for 30min or so, then the devices are not reachable from within Google Home although I can receive "SUCCESS" response when I make GET request to https://myserver/check.
If I reconnect my account on Google Home everything goes back to online but then again it goes back offline after sometimes.
How can I fix this issue?

FYI I'm running my node-red on a raspberry Pi.

cheers
Mehdi

**Comment by Caprico85** [comment]
Hi,

I seem to have the same problem. /check requests are coming true normally. But devices can't be controlled via Google Home. Seems like Google is not even trying to reach my server, otherwise there would be log messages.

For me, devices started to work again after unlinking and relinking my project in the Google Home App. But I don't know for how long.

Never noticed it stops working after ~30 min. This makes me think if the problem is related to access or refresh tokens. Tokens are by default renewed every 60 min, but maybe this renewal process is broken. I will have a look into this on the weekend.


Greeting
Andreas

**Comment by Caprico85** [comment]
Somewhere in the config there is a field called "Access token duration". You could try setting that to a much higher value instead of the default 60 min. If it really is related to token refreshing, this should at least delay the problem a while.

**Comment by rockstar2020** [comment]
Thanks @Caprico85 for your quick response.
Yes, I noticed the Access Token Duration but then I thought even if it delays the issue it is not ideal.
I even tried to create a new Key in HomeGraph API and used the new jwt json file but it's still the same.
It looks like the issue is with state report because this is the error I get in debug window when I re-deploy the node:

code: 403
message: "The caller does not have permission"
status: "PERMISSION_DENIED"

Let me know if you could crack the code.

Cheers

**Comment by rockstar2020** [comment]
By the way, just FYI I increased the "Access Token Duration" but it didn't help.

**Comment by rockstar2020** [comment]
This is another error that I'm getting in case it helps with your troubleshooting.

code: 400
message: "Precondition check failed."
status: "FAILED_PRECONDITION"

**Comment by Caprico85** [comment]
I found the error. It was related to renewing expired access tokens. I published version 0.0.38, which fixes the problem.

You need to relink your project in the Google Home App to reset your tokens.

**Comment by rockstar2020** [comment]
Thanks @Caprico85,
This is great!
I'm relatively new to Node Red, should I run the npm install to update my node?
Also I have another questions.
When I add "Window" device, in Google Home it goes straight to device settings when I click on it. In other words you can't switch on off or adjust the added device.

Lastly are you planning to add other devices like switch and camera?

Many thanks

**Comment by rockstar2020** [comment]
Never mind my question regarding upgrade. I managed to upgrade the node. 
Thanks for your great work!

**Comment by Caprico85** [comment]
> When I add "Window" device, in Google Home it goes straight to device settings when I click on it. In other words you can't switch on off or adjust the added device.

Same here. Windows can only be controlled via voice. I read a while ago that several device types (e.g. fans, windows) are not yet implemented in the app. We can only wait for Google.

> Lastly are you planning to add other devices like switch and camera?

Maybe later. I currently don't have the time to do that. If somebody sends a pull requests, I would be happy to merge it.
I guess you can "misuse" the outlet device as a switch.
