### ISSUE TITLE
Cannot GET /smarthome

### ISSUE THREAD

**Issue by dr-boss** [mikejac/node-red-contrib-google-smarthome#55]
I getting SUCCESS for /check, "invalid client id or secret" answer for /token (it's ok for check), answer for /oauth but for /smarthome only information "Cannot GET /smarthome". What I do wrong for /smarthome? Please help me.

**Comment by Caprico85** [comment]
Where do you see these errors?

Do you try to open the URLs in the browser? This won't work. /token, /oauth and /smarthome need special authorization data in the request headers. This data is sent by Google when it calls your service. Your browser won't send this data.

**Comment by dr-boss** [comment]
Thanks, I resolved problem (on firewall). But I have new problem, on my mobile in Google Assist I find my project [test] XXX, after choosing the prompt for user and password is show. After login with my google login) without any error I'm turning back to list of services but but my site isn't on the added list. Any error in log on Google Cloud Platform.

**Comment by Caprico85** [comment]
Can you please enable debug output in the settings of the management node, redeploy and then have a look in Node-Red's logfile, especially when you login. There should be an error somewhere (besides many other debug messages).

**Comment by dr-boss** [comment]
thank you for your willingness to help. Only this (404 in last line)
HttpAuth:httpAuthRegister(/token): query = {}
HttpAuth:httpAuthRegister(/token): body = {"grant_type":"refresh_token","refresh_token":"5dNHfQKJTtmB9ffyt1jVq5hEENiWPnZGJk2oAj","client_id":"Google000000","client_secret":"000000"}
HttpAuth:handleRefreshToken(): ReferenceError: authCode is not defined
POST /smarthome/token 400 17.486 ms - 25
HttpAuth:httpAuthRegister(GET /oauth)
GET /smarthome/oauth?response_type=code&client_id=Google000000&redirect_uri=https://oauth-redirect.googleusercontent.com/r/local-b349e&state=000000XlUfiz91aqnpIEuPWob4Z7zHFCbIPn0sZ_GSuqgzbASrmxupbhMpd0a-tT4vG4R2qJY0F8OT2RvOENup_ANlADw3a9Ka3vxPA7g-_LA 200 92.657 ms - 7182
GET /favicon.ico 404 2.370 ms - 150
HttpAuth:httpAuthRegister(POST /oauth): body = {"username":0000@gmail.com","password":"000000","client_id":"GoogleLocal01","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/local-b349e","state":"000000XlUfiz91aqnpIEuPWob4Z7zHFCbIPn0sZ_GSuqgzbASrmxupbhMpd0a-tT4vG4R2qJY0F8OT2RvOENup_ANlADw3a9Ka3vxPA7g-_LA","response_type":"code"}
HttpAuth:httpAuthRegister(POST /oauth): login successful
HttpAuth:httpAuthRegister(POST /oauth): authCode successful; authCode = 5GPFXkJ
POST /smarthome/oauth 302 25.414 ms - 1502
9 Oct 23:52:15 - [info] [exec:apcaccess] /sbin/apcaccess
HttpAuth:httpAuthRegister(/token): query = {}
HttpAuth:httpAuthRegister(/token): body = {"grant_type":"authorization_code","code":"5GPFXkJ","redirect_uri":"https://oauth-redirect.googleusercontent.com/r/local-b349e","client_id":"GoogleLocal0000000","client_secret":"0000000000"}
Auth:renewAuthAccessToken(): new access token expires at Sat Oct 10 2020 00:52:17 GMT+0200 (Central European Summer Time)
Auth:renewAuthAccessToken(): auth data saved = {"accessToken":"WpzrsTmQ1X27","refreshToken":"ZGJk2oAj","expiresAt":1602283937726}
HttpAuth:handleAuthCode(): respond success; token = {"token_type":"bearer","access_token":"WpzrsTmQ1X27","refresh_token":"ZGJk2oAj","expires_in":3600}
POST /smarthome/token 200 14.105 ms - 166
**POST /smarthome 404 3.043 ms - 149**

**Comment by zecoj** [comment]
@dr-boss you might want to try changing the Fulfillment URL to be: "https://YOUR.DNS/smarthome/smarthome"

**Comment by Caprico85** [comment]
Exactly. You seem to have set an URL path. That means, every URL is below this path Without  a path set, the URLs are https://example.com/oauth, https://example.com/token and https://example.com/smarthome.
With an URL path of "smarthome", these URLs change to [https://example.com/<ins>smarthome</ins>/oauth](https://example.com/smarthome/oauth), [https://example.com/<ins>smarthome</ins>/token](https://example.com/smarthome/token) and [https://example.com/<ins>smarthome</ins>/smarthome](https://example.com/smarthome/smarthome).

**Comment by dr-boss** [comment]
Thanks this is my error. I don't know why I didn't see the lack of one from dual smarthome in path. Maybe because I do my implementation at the night after full day job.
After correction all work fine, thanks @Caprico85

**Comment by dr-boss** [comment]
But I have one more question. I created one device in node-red. I see one device in my {test]... after connection. But not on the list of home device for add to rooms. When I run test on action console I have message "We're sorry, but something went wrong. Please try again" and... any error in GCP log

**Comment by jaburges** [comment]
> Exactly. You seem to have set an URL path. That means, every URL is below this path Without a path set, the URLs are https://example.com/oauth, https://example.com/token and https://example.com/smarthome.
> With an URL path of "smarthome", these URLs change to https://example.com/smarthome/oauth, https://example.com/smarthome/token and https://example.com/smarthome/smarthome.

just had this problem - assumed adding `smarthome` would replace the default - not create `/smarthome/smarthome` 
glad i found the solution

**Comment by Caprico85** [comment]
Docs for `path` parameter really were a bit misleading. Will be improved in the next release.
