### ISSUE TITLE
Redirect Invalid

### ISSUE THREAD

**Issue by diagonali** [mikejac/node-red-contrib-google-smarthome#56]
First, thanks so much for putting this together and all your efforts. Looking great.

I've followed along the instructions (I'm running Node-RED inside a Home Assistant Installation.) and I'm at the stage where I've tapped the + icon in the Home Assistant app on my phone, tap "Set up device", then "Have something already set up", then I can see my app in the list of providers. When I tap on it, it brings up a login page with "Link your devices to Google" and a username and password field. I enter my username and password correctly... but then it says:

`redirect_uri https://oauth-redirect.googleusercontent.com/r/node-red-smarthome-f1848 invalid`

I'm really not sure why it's doing this. It _might_ have something to do with that on Home Assistant, I'm using the NGINX Home Assistant SSL proxy plugin to manage ssl connections into my device (Raspberry Pi 4). But having said that, otherwise, connections to my Pi4 seem to work fine.

Any ideas what could be causing this redirect_uri invalid error? Are there any things I need to check in terms of URL settings either on my Pi4 installation, NGINX, or on my Google Cloud dashboard?

The Status check test is working and responds with SUCCESS

Any help would be appreciated as it looks like I've fallen at the last step. So close!

**Comment by Caprico85** [comment]
I had the same error when my JWT key was wrong. The JWT key is that JSON file you download during the Homegraph API step. You may want to download the file again from https://console.cloud.google.com/apis/credentials. Check if the correct project is selected in the header bar on that page.

**Comment by Caprico85** [comment]
You can also open the JWT file in an editor. There is a line `"project_id": "..."`.
In your case the project_id should be "node-red-smarthome-f1848".

Also check that the path in Node-Red is set correctly and that file permissions are right.

**Comment by diagonali** [comment]
> You can also open the JWT file in an editor. There is a line `"project_id": "..."`.
> In your case the project_id should be "node-red-smarthome-f1848".
> 
> Also check that the path in Node-Red is set correctly and that file permissions are right.

Thanks for reply and suggestions. Turns out the issue was that I'd set credentials for a different (wrong) project under Google Cloud Platform. 

After fixing this, at first it wouldn't let me log in and said “couldn´t update the settings. Check your connection” and so I re-created the project from scratch and used firefox to authenticate and I've made some progress.

Unfortunately now when I add the app, the login seems successful with no errors. It says briefly "Linking your [test] NODE-RED" but then takes me back to the "Set up screen" while it hasn't added it to my Google Home devices. Again not sure what to do here apart from re-create from scratch again. Any ideas?

**Comment by Caprico85** [comment]
Hard to tell what is causing this. Enable Debug Output in the Management Node in Node-Red and look at Node-Red's log output.
There might also be messages in Google Actions Console -> Test tab -> View Google Cloud Platform logs.

**Comment by diagonali** [comment]
Ok so after a lot of trial and error, I finally got it working. I've got an entity in my Google Home app called "LIGHT" which I can tun on and off and this is reflected in the Google Home app and vice versa.

The thing is, I set all this up hoping that I'd be able to use it to control my Nest thermostat (change temps etc) from within Node-RED. My Nest thermostat is set up within the Google Home app but I don't think I'm able to access it using this project? Have I completely misunderstood the use of this app? Sorry if so! If not, how can I use this to send commands to my Nest Thermostat? Thanks

**Comment by Caprico85** [comment]
The basic use of this project is to handle the communication from Google Assistant to Node-Red. You place a thermostat node in Node-Red, you say "Hey Google, set thermostat to 25 degree" and the thermostat node will output "desiredTemperature = 25". Nothing more, nothing less.

How you send the temperature to your target device is up to you. This is not part of this project. In my case I use function nodes to compare current to target temparature and finally use MQTT outputs to switch a WiFi-controlled power socket, where my waterbed heater is plugged in. In your case you would need another project (node-red-contrib-nest maybe?) to send the commands to your Nest thermostat.
