### ISSUE TITLE
Account linking issue after migration

### ISSUE THREAD

**Issue by bartbutenaers** [mikejac/node-red-contrib-google-smarthome#579]
Dear,

My google-smarthome node has been working perfect for many years.  But it was time now to migrate my old Node-RED to a new fresh installation on a new Raspberry.

So I shutdown the old node on the old Node-RED and I started a new one on my new Node-RED.  I copied all the settings on the config screen, and I copied my json file.

When I restart Node-RED I can see this in my log:
```
GoogleSmartHome.constructor
Auth:loadAuthStorage(): data already persisted
Auth:loadAuthStorage(): me._authStorage = {"accessTokens":{},"refreshTokens":{},"localAuthCode":"xxxxx","nextLocalAuthCode":"yyy"}
SmartHome:Start(listen): using external SSL offload
SmartHome:Start(): registered routes:
SmartHome:Start(): url /oauth registered for get
SmartHome:Start(): url /oauth registered for post
SmartHome:Start(): url /token registered for all
SmartHome:Start(): url /smarthome registered for post
SmartHome:Start(): url /check registered for get
SmartHome:Start(): url /smarthome registered for options
GoogleSmartHomeNode(): register; type = mgmt 99e385da0b60785d
google-smarthome:DeviceNode[licht boom] .constructor config {"id" .....}
google-smarthome:DeviceNode[licht boom] .constructor: device = {"id":"...}
GoogleSmartHomeNode(): register; type = device fbf55e201a3cfaf4
Device:registerDevice(): new device {"id":"fbf55e201a3cfaf4",...}
...
Device:_devicesDoTimedSync(_devicesSyncTimer) skipped timed sync, no account linked yet
...
HttpActions:requestSync()
15 Sep 21:32:31 - [error] HttpActions:requestSync(): skipped requested sync, account is not linked. (Re-)link your account in the app.
```
Not sure what I did wrong or how I can solve this.
In my Actions console, the account linking looks ok to me:

![image](https://github.com/user-attachments/assets/f405df46-720a-4c60-bb75-b5859e922a3e)

Thanks in advance!
Bart

**Comment by bartbutenaers** [comment]
Problem solved.  Thanks to the excellent documentation of this node.  
I will create a PR for some extra troubleshooting tips.

**Comment by bartbutenaers** [comment]
Hmm looks like I cannot create a PR for a wiki page...
Would you be so kind to add the following info the [possible errors](https://github.com/mikejac/node-red-contrib-google-smarthome/wiki/Possible-errors) wiki page:

**Log message: skipped requested sync, account is not linked. (Re-)link your account in the app**

This can happen for example when you move the smarthome node to another Node-RED system on another host.  Your devices won't appear anymore in your Google Home app.

Repeat the steps from the [setup account linking](https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/docs/setup_instructions.md#setup-account-linking) tutorial.  If you had already executed those steps in the past (e.g. for the original host), there might be an extra step between steps 5 and 6 to repeat the process:

![image](https://github.com/user-attachments/assets/40365287-63f9-4b74-89bb-05e36525496b)

Follow the next steps from the tutorial.  If everything goes wel, a list of your devices will be showed:

![image](https://github.com/user-attachments/assets/b5f3363e-bf2c-4053-980a-aef8149a27f5)

After pressing *"Done"*, your devices should appear again in the Google Home app.

P.S. the link to that wiki page on the readme doesn't work.

Thanks!!

**Comment by Caprico85** [comment]
Hello,

Thank you. I added your suggestions to the "Possible errors" page.
I also moved this page from the Wiki into the repository, so PRs are possible from now on.

Regards
