### ISSUE TITLE
Refresh token error

### ISSUE THREAD

**Issue by simon-culverhouse** [mikejac/node-red-contrib-google-smarthome#58]
Hello,

Firstly, thank you for this project. I've been using IFTTT to link Google Home to Node-red, but this allows much better integration.

Following your detailed installation instructions, I've got it up and running and it works really well.

However, I've got an issue with the token refresh after the initial log in which means I have re-login after 60mins.

I think it is probably something that I've missed but would really appreciate some help in resolving the issue.

This is the error I get in the log file
```
HttpAuth:httpAuthRegister(/token): query = {}
HttpAuth:httpAuthRegister(/token): body = {"grant_type":"refresh_token","refresh_token":"####################################","client_id":"################","client_secret":"#################"}
HttpAuth:handleRefreshToken(): ReferenceError: authCode is not defined
```
My set up uses NGINX as a reverse proxy for Node-red.

Thanks again for the great project

**Comment by Caprico85** [comment]
Which version do you have installed? We had a similar error in 0.0.37. Should be fixed since 0.0.38.

**Comment by simon-culverhouse** [comment]
I'm using the default version from the manage palette, it's version 0.0.37.

Just updated using this repository and It seems to have fixed it (Google home automatically connected on Node Red restart).

Thanks

**Comment by Caprico85** [comment]
Oops, didn't realise there was an older version on the palette. I thought the palette would update automatically from NPM.

Newest version is now available on the palette too.
