### ISSUE TITLE
New functions

### ISSUE THREAD

**Issue by dr-boss** [mikejac/node-red-contrib-google-smarthome#59]
Do you plan add support for control volume (up/down/mute,1-ex.300 not 100) and channels switch by number?

**Comment by Caprico85** [comment]
I already thought about it. I have a Philips TV here that I want to make a bit smarter. Its native Google Integration can only switch it off, but can't control volume or channels.

But I can't say when I find the time to do it. Pull request very welcome though :smiley:

**Comment by dr-boss** [comment]
I have canalplus (ADB) decoder and in this moment I use thermostat like " set program to 120" (program is name of thermostat) and I use setPoint as program number. But maximum value to set is 199 and Google return info after setting that end with degree :-(
For channel by name I use "switch on BBC" (BBC  is outlet name), for Up Down channels and volume is use to outlet too because is accessible by Google Assistant GUI. IF I plan use only voice command I use "scene" for ex BBC turn on (BBC is scene name) etc.
I have too little time for my speed and programming experience in node.js to do something good now with knowledge from ex https://developers.google.com/assistant/smarthome/traits/volume#response-nodejs or https://developers.google.com/assistant/smarthome/traits/channel#response-nodejs :-(
