### ISSUE TITLE
Q: Run on different port?

### ISSUE THREAD

**Issue by Webunity** [mikejac/node-red-contrib-google-smarthome#6]
As mentioned here; https://flows.nodered.org/node/node-red-contrib-google-action

> The node runs an Express web server to listen for Action request from Google. By using a separate web server from Node Red, it allows the node to listen on a different port. **This allows the Action listener to be exposed to the Internet without having the rest of Node Red also exposed.**

Which i think is a great plus. Any thoughts on implementing thesame?

**Comment by Caprico85** [comment]
I think, node-red-contrib-google-smarthome already does the same. You can set the port in the smarthome management node. Then it runs a separate web server on this port.

**Comment by Webunity** [comment]
Great!
