### ISSUE TITLE
Problem addding to Google home app - Cannot GET /oath

### ISSUE THREAD

**Issue by Bram81** [mikejac/node-red-contrib-google-smarthome#608]
Hi, 

First of all, thanks for your amazing work and detailled documentation! It took me a while to set up a domain and the required certificates etc. Approaching one small step at a time. Now I got to the point where it seems everything is set up correctly. I can reach the https://mydomain:3001/check both local and external, but when I try to add the service tot my Google Home App, I just get the screen  Cannot GET /oath 

I've tried with newly generated passwords for use as a client Id and Secret, ruling out the problem being in the use of special characters, checked and re-checked every single thing in your instructions, but I'm running out of options.. Is there a way you can point me in the right direction? 

My Setup:

Node-red v 4.03 on a Raspi 3B
Dynamic DNS: noip.com
Running Apache2 webserver (issue remains with Apache2 removed)

Obviously I'd be happy to supply additional info / logs, but as said I don't really know where to look right now. 

Thanks in advance!

**Comment by Caprico85** [comment]
Hi @Bram81,

>  I just get the screen Cannot GET /oath

Check the Authorization URL you entered in the Actions Console. It's `oauth`, not `oath`.

![image](https://github.com/user-attachments/assets/0b59f75e-e77d-44a8-8a0f-dcc962b14673)

**Comment by Bram81** [comment]
I feel like an idiot that I missed that... Everything is working now, thank you very much!
