### ISSUE TITLE
@mikejac: Add NPM token to repository settings

### ISSUE THREAD

**Issue by Caprico85** [mikejac/node-red-contrib-google-smarthome#61]
Hello @mikejac,

I'm trying to automate NPM releases. I have already written [the workflow file](https://github.com/mikejac/node-red-contrib-google-smarthome/blob/master/.github/workflows/npm-publish.yml). Now, an NPM token needs to be added to the repository settings as a secret. Since only the repository owner can access the settings I have to ask you for help.

Can you please generate a token on NPM and add it to this repository as a secret with the name `NPM_TOKEN`? The process of adding a secret [is detailed here](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository).

Thank you very much!

Greetings
Caprico

**Comment by mikejac** [comment]
Hi @Caprico85,

Token generated on NPM and secret added to GitHub. Hope it works :-)

/michael

**Comment by Caprico85** [comment]
Thank you Michael,

I just published v0.0.43 via our new Github Action. It worked great!

Currently the action is triggered by creating a new release. Next step is to automatically create the release on a "Bump version" commit.

**Comment by Caprico85** [comment]
Nevermind. The token was still valid. Seems like Github or npm changed something on the publish workflow. Got it to work by switching to another workflow action for publishing.
