### ISSUE TITLE
Can not link account to Google Home

### ISSUE THREAD

**Issue by DirkHBo** [mikejac/node-red-contrib-google-smarthome#62]
Hi,

I am stuck on your instructions (very detailed - thanks for that!) within "Setup Account Linking" on step 5 + 6 "Log in to your service. Username and password are the ones you specified in the configuration node."
When I kick on the [test] Project, a blank screen is shown and then jumps back to the list of services. My [test] Project will not be linked to my Home-environment.
So I did some troubleshooting and checked every step in the instructions - but I did not find any glitch.
Next I took a look at the logs and there I found something.
Within the Node-Red Logs there are two things:

> Device:_devicesDoTimedSync(_devicesSyncTimer)
> HttpActions:requestSync()
> HttpActions:requestSync(): postData = {"agentUserId":"0"}
> HttpActions:requestSync(): error; {"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}

> Auth:loadAuth(): err: Error: ENOENT: no such file or directory, open '/data/google-somefilename.json'

The 404 will also be shown in the debug-msg within Node-Red.

> topic: "management"
> payload: object
> _type: "actions-requestsync"
> msg: object
> error: object
> code: 404
> message: "Requested entity was not found."
> status: "NOT_FOUND"

So I checked if the json-key is readable. I can read it within Node-Red using the file-in-node. I also misspelled the path and filename with the configuration-node. After deploying I got a lot of errors ""Error: ENOENT: no such file or directory, open '/data/somemisspelledname.json'" and "missing bridge".

I think this one is out of this context:

> SmartHome:Start(): registered routes:
> SmartHome:Start(): /oauth
> SmartHome:Start(): /oauth
> SmartHome:Start(): /token
> SmartHome:Start(): /smarthome
> SmartHome:Start(): /check
> SmartHome:Start(): /smarthome
Some folders seem to be started twice.

Some information about my environment:
Docker using latest node-red from hub (Node-Red 1.2.2; Node-Version: 10.22.0). This is the state after update - I got the same issues with Node-Red 1.1.3.

I have no clue how to troubleshoot any more.

**Comment by DirkHBo** [comment]
As I was reading through the issues, I found https://github.com/mikejac/node-red-contrib-google-smarthome/issues/36# .
My problem is related to this. The node was not able to write the token-file. After touching it, the login screen came up, while linking the service to google home.
Also the errors diesapeared from the loggings.

Now I am facing a problem "400: redirect_uri_mismatch". But this is another topic for me.

I will leave this issue open - maybe this is a general issue.

**Comment by DirkHBo** [comment]
For some reason I geht stuck in every single step while linking :-)

Now the linking process can be started. I switched to username / passwort to avoid problems with the google-authentication.


> 2020-10-24   21:43:41,stdout,[0mPOST /token [33m400[0m 2.864 ms -   27[0m
> --
>  
> 2020-10-24   21:43:41,stdout,HttpAuth:httpAuthRegister(/token): invalid client id
>  
> 2020-10-24   21:43:41,stdout,Auth:isValidClient(): clientId does not match!
>  
> 2020-10-24   21:43:41,stdout,"HttpAuth:httpAuthRegister(/token): body =   {\"grant_type\":\"authorization_code\",\"code\":\"9uFx*********************************QUW6t\",\"redirect_uri\":\"https://oauth-redirect.googleusercontent.com/r/homeautomation-nodered\",\"client_id\":\"***Client ID***\",\"client_secret\":\"***Client Secret***"}

(sorry for the ugly logging)

I compared the config-node, as well as the  account-linking credentials and they all match exactly with the once from the logging.

Maybe this error results in a problem with handling the google-smarthome-auth-*.json. After touching the file it does not get populated, while trying to link to Google Home.

**Comment by DirkHBo** [comment]
Finaly got it linked.
I stumbled upon these two problems:
- google-smarthome-auth-*.json was not created. After touching it, it was not populated and oAuth threw still errors. After filling some data into it (refering to #36 ), additional content was written into it and no more errors on this occured.
- ClientID was transfered wrong and "Auth:isValidClient(): clientId does not match!" occured. There was some extra string attached to the ClientID. It turned out that a special character "+" was not processed correctly. Presumably through the use of a reverse proxy, the character was escaped or something similar.

Maybe the first problem can be fixed, the second one will at least end up in my documentation.

**Comment by Caprico85** [comment]
I'm glad you got it working.

> google-smarthome-auth-*.json was not created.

The file not being created could be related to wrong folder permissions. I'm planning to at least add a check if the file is readable and writable.

>  After touching it, it was not populated and oAuth threw still errors. After filling some data into it (refering to #36 ), additional content was written into it and no more errors on this occured.

I'll need to check what happens if the file is empty. Could be possible that an empty file is not handled well.

> Presumably through the use of a reverse proxy, the character was escaped or something similar.

I'm using Traefik as reverse proxy and I was able to reproduce this. Not sure if this is really related to the reverse proxy as I never had problems with Traefik modifying requests or escaping chars. I rather think this module is incorrectly decoding the request. I'll have a deeper look into this. Until then it's better to use only alphanumeric client IDs and keys.

**Comment by DirkHBo** [comment]
I checked the new version 0.0.45 and the results were very satisfying.
> > google-smarthome-auth-*.json was not created.
> The file not being created could be related to wrong folder permissions. I'm planning to at least add a check if the file is readable and writable.
> > After touching it, it was not populated and oAuth threw still errors. After filling some data into it (refering to #36 ), additional content was written into it and no more errors on this occured.
> I'll need to check what happens if the file is empty. Could be possible that an empty file is not handled well.

As I do not have a testing evironment, I just created a second Management-Node with a second conf-Node. The file was created and filled with json-config. No errors in the logs. Issue fixed from my point of view.

> > Presumably through the use of a reverse proxy, the character was escaped or something similar.
> I'm using Traefik as reverse proxy and I was able to reproduce this. Not sure if this is really related to the reverse proxy as I never had problems with Traefik modifying requests or escaping chars. I rather think this module is incorrectly decoding the request. I'll have a deeper look into this. Until then it's better to use only alphanumeric client IDs and keys.

I inserted the "+" and the API still works. Good work on that two.

Only thing within the new version: If I send _msg.topic=ReportState_ to the Management-Node I do not recieve an answer. When the node starts up it throws a message.

So the issue can be closed. Thank you very much. The Node is running rock solid, I encountered no further problems. It would be nice if users could donate a little something. Unfortunately I can't find any information about it.

**Comment by Caprico85** [comment]
Yeah, I thought v0.0.45 would fix your problems.

> I inserted the "+" and the API still works. Good work on that too. Need to revert here. For some reasen the communcation worked for half an hour or so and then I ran into the wrong ClientID-error again.

Sounds like I fixed that for token creation, but not for token renewal. I will check this.

> Only thing within the new version: If I send msg.topic=ReportState to the Management-Node I do not recieve an answer. When the node starts up it throws a message.

"ReportState" won't give you a result. "report_state" is the command you are looking for.

> It would be nice if users could donate a little something. Unfortunately I can't find any information about it.

I am very happy to her that.
We aren't taking any donations currently. I leave that to mikejac as the founder and owner of this project.

**Comment by DirkHBo** [comment]
> "ReportState" won't give you a result. "report_state" is the command you are looking for.

c&p failure - I copied the name of the Node. Of course I am sending "report_state" and do not get any answer. I am pretty sure this worked in <0.0.44.

**Comment by Caprico85** [comment]
Sorry, almost forgot this issue. 

*Regarding client id:*
I haven't found issues with token refreshing. I added several special chars to my client id and secret a week ago and had no problems since then.
Nevertheless I changed the error message in v0.0.49 to show exactly which id and secret was received and which value was expected. Hopefully this helps us to find out more.

*Regarding report_state*
Works for me too. States get sent to Google and also reported in the logfile. Did you probably disable debug output in the config node?

**Comment by DirkHBo** [comment]
Sorry, did not have the time to check on these issues. It is on my todo for the weekend.
Schöne Grüße aus dem Ruhrpott.

**Comment by DirkHBo** [comment]
_client_id:_
I updated to version x.50, then I added a "+" to the client_id. I've been waiting ten minutes now and it still works. I'll report if it stops working.

_report_state:_
To not talk past each other, here is how I try to get the state of the Google-Connection:
`[{"id":"49bc34e9.de92a4","type":"google-mgmt","z":"ac0d7349.2dcc6","client":"903caf5f.c9a3f","name":"","x":1110,"y":40,"wires":[["e98e819d.d7e578"]]},{"id":"e98e819d.d7e578","type":"debug","z":"ac0d7349.2dcc6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1280,"y":40,"wires":[]},{"id":"b67ba1a3.48cfb","type":"inject","z":"ac0d7349.2dcc6","name":"ReportState","props":[{"p":"topic","vt":"str"},{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"report_state","payload":"","payloadType":"str","x":850,"y":40,"wires":[["49bc34e9.de92a4"]]}]`
Maybe I am on the wrong way.
"Enable Node Debug" is checked.

**Comment by Caprico85** [comment]
Oh, I see. There is a misunderstanding here. report_state does not report the state to you, it reports the state to Google. With debug output enabled, you will see the states reported to Google in Node-Reds log output (stdout or logfile). But you won't see anything in the debug panel.  Although that's a good idea, might add that in one of the next versions.

**Comment by ChutneyMary** [comment]
I'm not having any success at the step 'Add devices' to the Google Home app. 'Link your devices to Google' is displayed with Sign in. I select my gmail account, then it bounces back to 'Link your devices to Google' screen.

I'm running google-smarthome v 0.5.4.

I'm seeing an error in the Node-Red debug console "Error on loading auth storage: Error: EACCES: permission denied, mkdir '/home/.node-persist'"

I'm running a Raspberry Pi with a bespoke image called 'Loxberry' that's developed to support the Loxone Home Automation System. The normal user is called Loxberry. I've installed Node-Red as root. Any suggestions on what I need to do?

**Comment by ChutneyMary** [comment]
I've now had success using Local Authentication with Username and Password. Voice control is working fine now.

I can't get 'Use Google Login' to work. There's something I've missed somewhere. Any pointers welcome.

**Comment by Caprico85** [comment]
@ChutneyMary Please try version v0.0.60. This should fix the problem with `.node-persist` permissions (as `.node-persist` is now not used anymore).

**Comment by ChutneyMary** [comment]
Thanks! v0.0.60 links fine using Google Login.

**Comment by DirkHBo** [comment]
I thing the main issues are solved.
Thank you.
