### ISSUE TITLE
Another small problem with Windows node

### ISSUE THREAD

**Issue by dr-boss** [mikejac/node-red-contrib-google-smarthome#63]
Work without any problem if I initialize command from google assistant, the node change state (open/close). But if I send command to node in nodered:
    msg.topic = 'set'
    msg.payload = {
      openPercent: false,
      online: true
    }
or 
    msg.topic = 'openPercent'
    msg.payload = 100
 the "window" node don't change state. Why?

`[{"id":"6500e422.f0276c","type":"google-window","z":"2a1ee19a.08048e","client":"","name":"WindowOne","topic":"GoogleTest","passthru":false,"x":650,"y":3780,"wires":[["b6bd108b.bb5868"]]},{"id":"bcef809.273278","type":"change","z":"2a1ee19a.08048e","name":"topic = openPercent","rules":[{"t":"set","p":"topic","pt":"msg","to":"openPercent","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":440,"y":3780,"wires":[["6500e422.f0276c","25b4cf2d.0a4078"]]},{"id":"b6bd108b.bb5868","type":"function","z":"2a1ee19a.08048e","name":"Split","func":"return [\n    { payload: msg.payload.openPercent },\n];","outputs":1,"noerr":0,"x":850,"y":3780,"wires":[["9cf2d8f5.49d0d"]],"outputLabels":["openPercent"]},{"id":"651a3990.028b58","type":"inject","z":"2a1ee19a.08048e","name":"","topic":"","payload":"10","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":3760,"wires":[["bcef809.273278"]]},{"id":"f9f77015.343","type":"inject","z":"2a1ee19a.08048e","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":3700,"wires":[["bcef809.273278"]]},{"id":"5bd0b6dc.928f1","type":"inject","z":"2a1ee19a.08048e","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":3840,"wires":[["bcef809.273278"]]},{"id":"9cf2d8f5.49d0d","type":"debug","z":"2a1ee19a.08048e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":990,"y":3780,"wires":[]},{"id":"25b4cf2d.0a4078","type":"debug","z":"2a1ee19a.08048e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":630,"y":3720,"wires":[]}]`

**Comment by Caprico85** [comment]
You are right. I tested and discovered some mistakes in the window node:

- The internal state was updated but the status marker in the UI was not.
- true/false weren't interpreted correctly, only numeric values.

I'll try to release a new version this evening which will fix these bugs.

**Comment by dr-boss** [comment]
But I have problem with numeric value too :-(

**Comment by Caprico85** [comment]
I released version 0.0.44, which fixes the problems with state markers not being updated and with boolean inputs.

I don't know if I understand you right. Do you send different values or do you send the same value multiple values?

If you send the same value multiple times, it is only reported the first time. For example if you set openPercent to 10, then 10 again, the second time is filtered because the value has not changed. If you set openPercent to 10, then 20, then 10 again, the value has actually changed and you should see all three reports in the log. After a restart of Node-Red the internal values are cleared and you see a report for the first change again.

**Comment by dr-boss** [comment]
0.0.44 work fine, open/close and value is reported on GUI, thx
Thx for explication of update method, I things is happen in my situation.
