### ISSUE TITLE
Node Requests - Blinds

### ISSUE THREAD

**Issue by ChutneyMary** [mikejac/node-red-contrib-google-smarthome#66]
Great job with this project. Thankyou!
I would kindly request consideration for two nodes -
Blinds
Switch
Both are used extensively in my home automation system but currently don't have a voice input.

**Comment by Caprico85** [comment]
I'll see what I can do when I find the time for it,

In the meantime you can probably "misuse" outlets as switches. They can be switched on and off too.
Blinds can probably be replaced with window devices. They can be opened and closed as whole or to a certain degree.

**Comment by ChutneyMary** [comment]
Thankyou.

**Comment by 0rsa** [comment]
I upvote this request.
And I would like to say I love node author(s), this is just awesome work which makes Google Assistant essential with node red automation.

**Comment by Chrischi-** [comment]
@0rsa @ChutneyMary 
i added "Switch" Device suuport. PR https://github.com/mikejac/node-red-contrib-google-smarthome/pull/82

If you notice any unusual behaviour after it is merged and while using it, let me know.

**Comment by 0rsa** [comment]
Some labels and placeholders are missing for the form, see printscreen.

![smarthome](https://user-images.githubusercontent.com/769750/103203724-dbfe5e00-48f5-11eb-82d6-27135d669e22.png)

Otherwise it works well, thank you very much

**Comment by Chrischi-** [comment]
@0rsa 

**Thanks** for checking. I have added the missing "locales".

**Comment by ChutneyMary** [comment]
Thanks for the support.

**Comment by Chrischi-** [comment]
My pleasure.

Maybe you could change the Request to "Blinds" only.

**Comment by Caprico85** [comment]
Blinds added by @albgau and released in v0.0.58.
