### ISSUE TITLE
Saved wrong configuration now nodes are not visible anymore

### ISSUE THREAD

**Issue by nabbl** [mikejac/node-red-contrib-google-smarthome#69]
Hey there,

I tried to install and configure everything but had to stop before being able to complete the configuration of the googlesmarthome client config. I deployed the flows anyway. I immediately got configuration errors:

```" - google-smarthome : TypeError: Cannot match against 'undefined' or 'null'."``

I tried uninstalling the npm package and then reinstalling, but that doesnt seem to work. The googlesmarthome-client and
google-mgmt nodes are inactive and not visible in the node list.

I am sure that I have to delete some config file anywhere....
Can you please tell me what to do ? :+1: 

Greetings

**Comment by Caprico85** [comment]
You could try looking into Node-Red's menu for the config nodes.

![image](https://user-images.githubusercontent.com/2081806/100894592-f0009c80-34bc-11eb-9ee8-9710e443af68.png)

The config node is either listed in the group "googlesmarthome-client" or "unknown". Open that node and delete it (double-click, then click the delete button).

You may also have to delete the auth file. This is the file `google-smarthome-auth-549d8e9b.3a98f.json` (id will be different) in Node-Red's user directory.

**Comment by nabbl** [comment]
thank you for answering so quickly.
I have already deleted the config node.
 
The auth file isn't there at all and is not loaded. Still I get this error when starting node-red

**Comment by nabbl** [comment]
updated node-red and nodejs to most recent version ... now it works.

sorry for bothering you
