### ISSUE TITLE
Management node not available in palette

### ISSUE THREAD

**Issue by rbm78bln** [mikejac/node-red-contrib-google-smarthome#71]
After installing node-red-contrib-google-smarthome the management node doesn't show up in the palette. (see [screenshot.png](https://user-images.githubusercontent.com/43565949/101286385-86e59580-37ea-11eb-9fd9-8b233969c620.png))

Additionally this warning shows up while starting node-red:

    17:21:54 - [info] Node-RED version: v1.2.6
    17:21:54 - [info] Node.js  version: v12.20.0
    17:21:54 - [info] Linux 4.15.0-124-generic x64 LE
    17:21:56 - [info] Loading palette nodes
    17:22:13 - [info] Dashboard version 2.24.1 started at /
    17:22:13 - [warn] ------------------------------------------------------
    17:22:13 - [warn] [node-red-contrib-google-smarthome/google-smarthome] TypeError: typeMap[type].map is not a function
    17:22:13 - [warn] ------------------------------------------------------

These dependencies are installed as well: [deps.txt](https://github.com/mikejac/node-red-contrib-google-smarthome/files/5649131/deps.txt)

**Comment by Caprico85** [comment]
I never had this error before. Could be the same as [this error in the googleapis module](https://github.com/googleapis/google-api-nodejs-client/issues/2070).

My first advice would be to update to at least v0.0.49. This will also update `googleapis` which might already fix the problem.
If that doesn't help, I would try removing and reinstalling node_modules, as stated in that other issue.
