### ISSUE TITLE
Refused to load the script "script-src 'self'"

### ISSUE THREAD

**Issue by Damme** [mikejac/node-red-contrib-google-smarthome#73]
Hello

I was trying to install this and setup everything, but I get stuck at "link your device to google" page in Google Home
When loading the request url in a broswer I get the following message:
`oauth:1 Refused to load the script 'https://apis.google.com/js/platform.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

`oauth:210 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-NkkhJRMsgzAv51lXrrTBpU0jJ4V2k+iDzm4k6Ujs6qk='), or a nonce ('nonce-...') is required to enable inline execution.`

My setup is through docker with ha-proxy so I've run node-red-contrib-google-smarthome with  "Use external SSL offload" on.

**Comment by Damme** [comment]
I tried serving platform.js from SmartHome.js 
```
this.app.use('/static', express.static(path.join(__dirname, 'public')))
```
I get the sign in, but either google signin or static login works, I get the following;
`redirect_uri https://oauth-redirect.googleusercontent.com/r/node-red-655ae invalid`

**Comment by Damme** [comment]
I tried serving platform.js from SmartHome.js 
```
this.app.use('/static', express.static(path.join(__dirname, 'public')))
```
I get the sign in this time, but either google signin or static login works, I get the following;
`redirect_uri https://oauth-redirect.googleusercontent.com/r/xxxxxxxxxxxxxx invalid`

**Comment by Caprico85** [comment]
Where exactly do you get the error message? Immediately after selecting your service in the Google Home app? Or do you see the login page, submit it and then get the error?

And do you use login with username/password or Google SignIn? The technically simpler process would be username/password since it involves less redirects. Although Google SignIn should work too (at least it does in my case, with Traefik as reverse proxy).

**Comment by Damme** [comment]
I get it at first page load after selecting app in google home since it tries to include an external js file.

**Comment by valekrus** [comment]
I have the same issue. It seems that we need to set CSP somehow.

**Comment by valekrus** [comment]
> And do you use login with username/password or Google SignIn? The technically simpler process would be username/password since it involves less redirects. Although Google SignIn should work too (at least it does in my case, with Traefik as reverse proxy).

No matter what i use - in both cases i have the same problem.

**Comment by Caprico85** [comment]
Damn. My IDE didn't search through login.html. I didn' realize that we actually include platform.js and wondered what you were talking about.

Please try v0.0.50. Should be fixed now.

**Comment by navorobev** [comment]
hello. I have the same problem. I used dns service CloudFlare. This issue solved for me then i added Workers on CF by this note https://maxchadwick.xyz/blog/cloudflare-worker-csp

**Comment by Caprico85** [comment]
Relaxed the Content Security Policy a bit further in v0.0.51 (now includes *.google.com as trusted source instead of only api.google.com). Do you still get errors after upgrading?

**Comment by Caprico85** [comment]
Closing this now. Feel free to reopen/answer if the problem persists.
