### ISSUE TITLE
How to interact with a device created only in Google Home?

### ISSUE THREAD

**Issue by marcospg75** [mikejac/node-red-contrib-google-smarthome#75]
Hello,
I have a Thermostat that is created only en GH (I have no option to create/define it in NodeRed or Hassio).
How can I use this solution to interact with it?
Of course I can create a virtual Thermostate in NR but, in the end, I want to set temperature / get information from the real one that is only created in Google Home.

Thanks in advance

**Comment by Caprico85** [comment]
You can't. This module only creates new devices in the app. But it does not let you control existing devices from other smarthome providers in the app.

AFAIK there is no API to do that. You would need to use something like https://assistantrelay.com/ to "talk" to Google Assistant. But it is probably easier to use HomeMatic, Zigbee, MQTT or whatever your thermostat uses to communicate directly it.

**Comment by marcospg75** [comment]
> You can't. This module only creates new devices in the app. But it does not let you control existing devices from other smarthome providers in the app.
> 
> AFAIK there is no API to do that. You would need to use something like https://assistantrelay.com/ to "talk" to Google Assistant. But it is probably easier to use HomeMatic, Zigbee, MQTT or whatever your thermostat uses to communicate directly it.

Ok, thank you for the explanations. I'm ussing assistanrelay to do that, but I can't get the current state of the device. I only can give it instructions.

Thanks in advance!

**Comment by Caprico85** [comment]
Sorry, I never used assistantrelay, so I can't help you there.
