### ISSUE TITLE
Google home reports the state of multiple sensors although the request is for one single sensor

### ISSUE THREAD

**Issue by rockstar2020** [mikejac/node-red-contrib-google-smarthome#76]
Hi @mikejac,
It is great to see that you're constantly improving this project.
I am facing an odd issue on sensor device which I'm hoping you could give me hint to fix it.
I created two sensor devices one for temprature and one for humidity.
When I ask google "what's the room temprature?" it first says "I can't reach room humidity right now" then it states the correct room temprature. Also, if I ask google "what's the room humidity" it responds by saying correct humdity percentage but again it continues saying "I can't reach room temprature right now".

Any idea what could cause this problem?

cheers
Mehdi

**Comment by Caprico85** [comment]
My first guess is that Google is confused on what sensor to read.

A single sensor device has temperature and humidity values simultaneously, even if one of them is not set. If you are asking "what's the room temperature?", Google might not know which sensor to read (as you didn't say "what's the room temperature on <sensor name>?"). Sometimes it picks your temperature sensor, reads its temperature and succeeds. Sometimes it picks the humidity sensor, reads its temperature and fails. Google likes to give misleading error messages, so this is probably the reason for the "can't reach your device" message.

So I would recommend to send both temperature and humidity into the same sensor device and delete the other device.

**Comment by rockstar2020** [comment]
Thanks @Caprico85,
Your guess was right. :)
It was google being confused between two devices.

Much appreciate your help.

Happy Holiday!

Cheers
