### ISSUE TITLE
Unable to set ambient temp in thermostat

### ISSUE THREAD

**Issue by stonesrose** [mikejac/node-red-contrib-google-smarthome#85]
Hi, Ive tried a number of methods to set the ambient temp in a thermostat.

I've sent in the following jsons and can't get it to update in Google home:

{"topic":"set","_msgid":"bd5a58ba.9fc128","payload":{"online":true,"thermostatTemperatureAmbient":9.7}}{"_msgid":"62709033.1a135","payload":99,"topic":"thermostatTemperatureAmbient"}

I used the example with MQTT unsucessfully.
Ive tried the temp as a string and number.

is there something I'm missing?

**Comment by stonesrose** [comment]
Aslo unable to turn off a switch inside node-red. items don't seem to be accepting input.

**Comment by Chrischi-** [comment]
@stonesrose 
after merging PR #87 the problem should be solved.

Additionally I have extended the node status a bit.

T - Temperature Ambient
S - Setpoint

![Thermostat_Node](https://user-images.githubusercontent.com/6323217/103890327-29de4780-50e8-11eb-9ec3-0793fc883770.jpg)

**Comment by Caprico85** [comment]
PR #87 merged and released as v0.0.55
