### ISSUE TITLE
Recurring reportState error

### ISSUE THREAD

**Issue by Botched1** [mikejac/node-red-contrib-google-smarthome#88]
I see the below error on a recurring basis. I think it started when I added a scene node, but am not 100% sure.

Any way I can figure out what is causing this?

![image](https://user-images.githubusercontent.com/19985320/104076579-1ad8c180-51dc-11eb-907b-89e451ec1d13.png)

And all I see in the node-red log is this (not helpful):
![image](https://user-images.githubusercontent.com/19985320/104076729-920e5580-51dc-11eb-8a3c-fe6b216de8fe.png)

**Comment by Caprico85** [comment]
Can you please copy the error message with all branches expanded? I need to see the `states`object in the error message.

You can also use the small copy button which appears when you hover over the error messsage to copy it to the clipboard.
![image](https://user-images.githubusercontent.com/2081806/104083734-5194f300-5241-11eb-9d00-dac5a83c9a5c.png)

**Comment by Botched1** [comment]
Sorry about that!

Here is a more focused one. I just got this when triggering a state as a test. I got the expected message (so everything is working), but I also got this error:
```
{"msg":"Error in HttpActions:reportState()","org_msg":{"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT"},"data":{"states":{"online":true,"deactivate":false}}}
```

**Comment by Chrischi-** [comment]
@Botched1 
which `node-red-contrib-google-smarthome` version do you use?

i guess you are still using an old version.

**Comment by Caprico85** [comment]
Not a duplicate to #72. Version should not really matter.

I can reproduce this. This happens when a scene node is executed using voice/app. Executing the scene immediately reports the state of the scene back to Google. There is something in the reported state that Google doesn't like (or Google doesn't like receiving a state for scenes at all).

**Comment by Chrischi-** [comment]
you're right. i missed the part about the scene-node.

why not simply check if the states to be transmitted correspond to the predefined ones of the node and discard anything additional?

**Comment by Caprico85** [comment]
Should be fixed in v0.0.59.

**Comment by Caprico85** [comment]
> @Caprico85 I'm seeing this in 0.1.11 - whenever I activate a scene the reportstate error happens

OK, i'll check.

**Comment by ckhmer1** [comment]
I use the Google device node configured as a scene daily without problems.
Really I've replaced all my google nodes with the Google device node.

**Comment by Caprico85** [comment]
Try v0.1.13. Scene devices now internally use @ckhmer1's implementation, so they shouldn't have the state problem anymore.

@ckhmer1
I modified your generic device a little bit to serve as a base class for all other devices. Saves us lots of duplicate code.
Scene devices, on/off devices and open/close devices are already migrated to use the new base class. I'll migrate the remaining devices too after a bit more work and more testing.

**Comment by ckhmer1** [comment]
@Caprico85 this is a great idea, in this way, if we have a problem, we fix only one time.
I think we could remove some nodes, i.e. the media device node, just to start. In my opinion, the Node-RED palette is too full of nodes, and for the Google Smart home, the Device node is enough.

**Comment by Caprico85** [comment]
Problem should be fixed, so I am closing this now.
