### ISSUE TITLE
[error] Error: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by homefefeld** [mikejac/node-red-contrib-google-smarthome#91]
Hi there,

Sorry , this may not be an issue but more a configuration error.
I have followed step by step the installation guide but when I try to deploy the management node I get the following Errors in the nodered log :
**- [error] Error: ENOENT: no such file or directory, open**
**- [error] [google-mgmt:XXXXXXXX] missing bridge**

I may have done something wrong, Can someone help ? do you guys are on discord/telegram/slack ? 

Many thanks,

F.

**Comment by Caprico85** [comment]
Hi,

The path to the JWT key is probably wrong. This can either be an absolute path or a path relative to Node-Reds user dir (where flows.json, settings.js etc. is stored).

**Comment by homefefeld** [comment]
yep.. I didn't enable "Use http Node-RED root path "
