### ISSUE TITLE
Devices traits

### ISSUE THREAD

**Issue by homefefeld** [mikejac/node-red-contrib-google-smarthome#93]
Hello there,

Instead of having a different client connection for the various light configuration (light on-off, dimmable light,Color Light...) it would be good to have only one (light) but we should be able to select which traits we want to activate within the node configuration.

G.

**Comment by ckhmer1** [comment]
Hi,
I agree with You, for the media devices, which share several traits, I've done the same.
Are You implementing only one node for all the light type?

Claudio

**Comment by homefefeld** [comment]
Yes, I think it would make a lot of sens. been able to select the traits from the configuration. I may have a try when I will free up some time.

**Comment by ckhmer1** [comment]
Hi,
I've just created a new pull request for this.

**Comment by homefefeld** [comment]
👍 Sounds good.
I was wondering if it wouldn't be better to define/code all the traits then when defining a device we could select the traits we want.
as per Google documentation, each device has a set of prefered traits but could be extended :   
_**Recommended traits:**_
_These traits are recommended, if applicable to your device. However, you are free to mix and match from all available traits to best match your existing product functionality._

Do you see what I mean ?

**Comment by homefefeld** [comment]
not sure to understand the light type ...
![image](https://user-images.githubusercontent.com/3512839/109906159-3de59600-7ca0-11eb-8f72-fee56d8e1968.png)

**Comment by ckhmer1** [comment]
There are three traits:
- On/OFF
- Brightness 
- Color

The first is mandatory.
The last two, can be mixed in the following way:

- Brightness, no color -> Dimmable Light
- Color, No Brightness -> Not foreseen. Are there some lights?
- Color, Brightness -> RGB, HSV, Temperature, RGB and Temperature, HSV and Temperature (latter not foreseen, should I add it?)

**Comment by ChutneyMary** [comment]
> @ckhmer1 - HSV and Temperature (latter not foreseen, should I add it?)

What does the Light Node spit out when you say "Set the light to cool white" and "Set the light to warm white"?

I previously had this code to interpet those two actions from a NORA Google light node -

h = msg.payload.hue;
s = msg.payload.saturation;
v = msg.payload.value;

h = Math.round(h*100)/100
s = Math.round(s*100)/100
v = Math.round(v*100)/100

msg.payload = "hsv(" +h + ',' + s + ',' + v +')';

if (h === 29.6 && s === 58.82 && v === 100)
{
msg.payload = "temp(100,2700)"
}
if (h === 60 && s === 16 && v === 98.04)
{
msg.payload = "temp(100,6500)"
}
return msg;

Would support for HSV and Temperature possibly negate the need for this code?

**Comment by ckhmer1** [comment]
Currently, the RGB/Temp node outputs are: online, on, RGB and temperature.
Adding a light HSV/Temp, the output should be online, on, h, s, v, and temperature.

**Comment by homefefeld** [comment]
Idealy, the approach should be that each device could have many traits. more than just the ones recommended.
Things take a new dimention when you use Google Hub, as traits are visible in the interface.  (devices could have multiple "toggle" traits for example.)
the traits should be coded ones. then the each device should have a list of traits, but the list should be extendible.. them this node become a real killer app !!!

**Comment by homefefeld** [comment]
then for example it would be easy to add mode for thermostat :  ([issue 111](https://github.com/mikejac/node-red-contrib-google-smarthome/issues/111))

**Comment by ckhmer1** [comment]
> > @ckhmer1 - HSV and Temperature (latter not foreseen, should I add it?)
> 
> What does the Light Node spit out when you say "Set the light to cool white" and "Set the light to warm white"?
> 
> I previously had this code to interpet those two actions from a NORA Google light node -
> 
> h = msg.payload.hue;
> s = msg.payload.saturation;
> v = msg.payload.value;
> 
> h = Math.round(h_100)/100 s = Math.round(s_100)/100
> v = Math.round(v*100)/100
> 
> msg.payload = "hsv(" +h + ',' + s + ',' + v +')';
> 
> if (h === 29.6 && s === 58.82 && v === 100)
> {
> msg.payload = "temp(100,2700)"
> }
> if (h === 60 && s === 16 && v === 98.04)
> {
> msg.payload = "temp(100,6500)"
> }
> return msg;
> 
> Would support for HSV and Temperature possibly negate the need for this code?

I've just added an HSV/Temp light, which returns the temperature or the HSV values (depending on the input command).
So You don't need anymore this code.

**Comment by ckhmer1** [comment]
> then for example it would be easy to add mode for thermostat : ([issue 111](https://github.com/mikejac/node-red-contrib-google-smarthome/issues/111))

I've got Your point. Just one big node for all devices. You select the device type and the option traits.

The only problem I see is that actually, the code is expecting from google the value for the status.
I think it needed some general logic review.

**Comment by homefefeld** [comment]
you re probably right. but before I could suggest anythin, I'm going to test your PR.
I will start with a device with multiple "toggles".
I can see that I need to inject somehow the json file (toggles.json). I'm not sure to understand how..
![image](https://user-images.githubusercontent.com/3512839/110709252-3a03c780-81fc-11eb-825a-ae35d7add265.png)

could you please advice ?
I suppose that you want to provide something like this : 
{
  "availableToggles": [
    {
      "name": "sterilization_toggle",
      "name_values": [
        {
          "name_synonym": [
            "clean",
            "bio clean"
          ],
          "lang": "en"
        }
      ]
    },
    {
      "name": "energysaving_toggle",
      "name_values": [
        {
          "name_synonym": [
            "energy saving",
            "eco"
          ],
          "lang": "en"
        }
      ]
    }
  ]
}

**Comment by ckhmer1** [comment]
Hi,
for the traits already available in the MediaNode, please import the example flow related to the media nodes.
In this example, there are some hints how configure toggles, modes, channels, inputs and apps.

**Comment by homefefeld** [comment]
Sure, I understand is not terminated and would like to help if I free up some time.
It's getting definitively in the right direction !! well done !!
Btw, I like the new google device "BED"  😄 
but when I try to say "Hey Google, Make my Bed" it doesn't work 🤣 🤣 🤣 
![image](https://user-images.githubusercontent.com/3512839/110762484-20d93600-8251-11eb-816e-ee083390c8c2.png)

**Comment by ckhmer1** [comment]
🤣🤣🤣🤣🤣

**Comment by homefefeld** [comment]
creating a temporary discord channel to talk this topic
https://discord.gg/Byxgb4HF

**Comment by homefefeld** [comment]
@ckhmer1 , btw, the "device" should be called "generic device" instead of "multi-device", don't you think?

G,

**Comment by homefefeld** [comment]
@ckhmer1, do you think that it is possible to reorder the traits?
e.g: here set the control before the volume?
![image](https://user-images.githubusercontent.com/3512839/111876480-40820400-899f-11eb-8f30-b201ee895369.png)

btw,  this is great, the generic device is exactly what I had in mind !!!!! bravo !!!

**Comment by ckhmer1** [comment]
Hi,
i I don't understand your question.

**Comment by Vernando05** [comment]
Looking forward to this feature! I can compose traits for my custom devices in a few clicks!

**Comment by homefefeld** [comment]
> Hi,
> i I don't understand your question.

I wanted to set an order for traits, but apparently this is not possible... so forget it. thanks anyway.

G.

**Comment by homefefeld** [comment]
@ckhmer1 ,    Im trying to send back some status to google home. 
I'm using a lawnmower device with "cycle" and would like to send a msg to the node to change the currentRunCycle on google.
can you share an example?
I tried to send :  
msg.payload =  '{"currentRunCycle": {"currentCycle": "Mowing","lang": "en"}}';
msg.topic      = 'set'; 

many many thanks,

**Comment by ckhmer1** [comment]
Hi,
the correct payload is the following:

{
    "currentRunCycle": [
        {
            "currentCycle": "Mowing",
            "lang": "en"
        }
    ]
}

I've sent a merge request to fix a bug.

Best Regards
Claudio

**Comment by homefefeld** [comment]
it is working great,. thanks

**Comment by homefefeld** [comment]
I can consider this enhancement done. thanks to claudio.

**Comment by ckhmer1** [comment]
Thanks
