### ISSUE TITLE
Feature request - Add 'Room Hint' to each node

### ISSUE THREAD

**Issue by ChutneyMary** [mikejac/node-red-contrib-google-smarthome#99]
A slightly tedious aspect of unlinking then re-linking an account (eg. for fault-finding) is the need to define the room for every item when re-linking. 

A different version of Node-Red/Google fulfillment (node-red-contrib-nora), makes use of a 'Room Hint' feature. This feature appears to negate the step when re-linking an entire household of items.

Fortunately, node-red-contrib-google-smarthome is far better in all respects (and nora no longer works...). :)

**Comment by ckhmer1** [comment]
Hi,
I've just sent a merge request to support the room hint in the Google device node, for starting.
You can try it if You wish.

Claudio

**Comment by ChutneyMary** [comment]
Thanks for that, much appreciated!

I won't try it until it's merged (only because I'm not very confident installing the patch).

**Comment by Caprico85** [comment]
Room hints released in v0.0.66

**Comment by ChutneyMary** [comment]
Just upgraded to v0.0.66 and nearly everything works fine.

The Blinds node fails to respond to voice commands - "It looks like that device hasn't been set up yet....". I'm seeing an error in the debug for Blind nodes (I have 4 nodes and 4 errors) -

msg : error
ReferenceError: me is not defined

The only difference I can see for this Room Hint is that it has a double worded name - 'Master Bedroom'. The remainder of the Room hint additions have been single worded. eg. 'Kitchen'.

**Comment by ckhmer1** [comment]
Hi,
sorry for that,
I'll check it as soon as possible.
Thanks
Claudio

**Comment by ckhmer1** [comment]
Hi,
I've sent a pull request to fix this problem.

Best Regards
Claudio

**Comment by ckhmer1** [comment]
Hi,
this request should be fixed now, isn't it?

Claudio

**Comment by ChutneyMary** [comment]
Yes, fixed thank you.
